# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [1]:
import math
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm.notebook import trange

In [20]:
def process_input_dataframe(dataframe):
    # 1. Convert data types
    # 2. Remove lines with empty values
    # 3. Shuffle to introduce randomness
    # 4. Normalize values
    dataframe.apply(pd.to_numeric, errors='coerce')

    dataframe.dropna(inplace=True)

    return dataframe.sample(frac=1)


def normalize_array(array, min_value, max_value):
    return (array - min_value) / (max_value - min_value)


def calculate_normalization_boundaries_for_columns(dataframe, target_columns):
    boundaries = {}

    for column_name in target_columns:
        boundaries[column_name] = {
            'min': get_column_min(dataframe, column_name),
            'max': get_column_max(dataframe, column_name)
        }

    return boundaries


def normalize_dataframe(dataframe, normalization_boundaries_dict):
    for column_name, boundaries_dict in normalization_boundaries_dict.items():
        min_value = boundaries_dict['min']
        max_value = boundaries_dict['max']

        column_arr = np.array(dataframe[column_name])

        dataframe[column_name] = normalize_array(column_arr, min_value, max_value)


def get_column_min(dataframe, column_name):
    return dataframe[column_name].min()


def get_column_max(dataframe, column_name):
    return dataframe[column_name].max()

#### Reading and pre-processing data

In [38]:
file_path = 'data/iris/iris.csv'

data_columns = ['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'
]
result_columns = ['Species']
all_columns = data_columns + result_columns

df = pd.read_csv(file_path, header=None, names=all_columns)

train_df=df.sample(frac=0.7,random_state=200)
test_df=df.drop(train_df.index)

train_df = process_input_dataframe(train_df)
test_df = process_input_dataframe(test_df)

#### Displaying basic information about the initial data

In [39]:
def display_dataframe_info(dataframe):
    print('****** General Information ******')
    display(dataframe.info())
    display(dataframe.describe())

    print('****** Data Sample ******')
    display(dataframe.head())

In [40]:
print('==== Train Data Info ====')
display_dataframe_info(train_df)
print('========================', end='\n\n')

print('==== Test Data Info ====')
display_dataframe_info(test_df)
print('=========================')

==== Train Data Info ====
****** General Information ******
<class 'pandas.core.frame.DataFrame'>
Index: 105 entries, 48 to 8
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  105 non-null    float64
 1   SepalWidthCm   105 non-null    float64
 2   PetalLengthCm  105 non-null    float64
 3   PetalWidthCm   105 non-null    float64
 4   Species        105 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 4.9 KB

None

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
count     105.000000    105.000000     105.000000    105.000000  105.000000
mean        5.809524      3.019048       3.736190      1.179048    1.990476
std         0.833035      0.436572       1.755164      0.764312    0.814475
min         4.300000      2.000000       1.000000      0.100000    1.000000
25%         5.100000      2.800000       1.600000      0.300000    1.000000
50%         5.700000      3.000000       4.200000      1.300000    2.000000
75%         6.400000      3.300000       5.100000      1.800000    3.000000
max         7.900000      4.400000       6.900000      2.500000    3.000000

****** Data Sample ******

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
48             5.3           3.7            1.5           0.2        1
128            6.4           2.8            5.6           2.1        3
75             6.6           3.0            4.4           1.4        2
113            5.7           2.5            5.0           2.0        3
19             5.1           3.8            1.5           0.3        1

========================

==== Test Data Info ====
****** General Information ******
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 59 to 145
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  45 non-null     float64
 1   SepalWidthCm   45 non-null     float64
 2   PetalLengthCm  45 non-null     float64
 3   PetalWidthCm   45 non-null     float64
 4   Species        45 non-null     int64
dtypes: float64(4), int64(1)
memory usage: 2.1 KB

None

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species
count      45.000000     45.000000      45.000000     45.000000  45.000000
mean        5.922222      3.135556       3.811111      1.244444   2.022222
std         0.820169      0.420041       1.804694      0.767095   0.839071
min         4.400000      2.200000       1.200000      0.100000   1.000000
25%         5.200000      3.000000       1.500000      0.400000   1.000000
50%         5.900000      3.100000       4.500000      1.500000   2.000000
75%         6.500000      3.400000       5.200000      1.800000   3.000000
max         7.700000      4.200000       6.700000      2.400000   3.000000

****** Data Sample ******

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
59             5.2           2.7            3.9           1.4        2
14             5.8           4.0            1.2           0.2        1
32             5.2           4.1            1.5           0.1        1
7              5.0           3.4            1.5           0.2        1
130            7.4           2.8            6.1           1.9        3

=========================

#### Determining normalization boundaries and performing normalization fot both the training and testing sets

In [41]:
normalization_boundaries_dict = calculate_normalization_boundaries_for_columns(train_df, [])

print('====== Data Normalization ======', end='\n')

print('Based on the input training data, each column will be normalized using the following boundaries:', end='\n')

for column_name, boundaries_dict in normalization_boundaries_dict.items():
    min_value = boundaries_dict['min']
    max_value = boundaries_dict['max']

    print(f'{column_name}: [{min_value}; {max_value}]', end='\n')

normalize_dataframe(train_df, normalization_boundaries_dict)
normalize_dataframe(test_df, normalization_boundaries_dict)

print('\nData has been normalized')
print('================================', end='\n')

====== Data Normalization ======
Based on the input training data, each column will be normalized using the following boundaries:

Data has been normalized
================================

In [42]:
print('==== Train Data Normalized Info ====')
display_dataframe_info(train_df)
print('========================', end='\n\n')

print('==== Test Data Normalized Info ====')
display_dataframe_info(test_df)
print('=========================')

==== Train Data Normalized Info ====
****** General Information ******
<class 'pandas.core.frame.DataFrame'>
Index: 105 entries, 48 to 8
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  105 non-null    float64
 1   SepalWidthCm   105 non-null    float64
 2   PetalLengthCm  105 non-null    float64
 3   PetalWidthCm   105 non-null    float64
 4   Species        105 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 4.9 KB

None

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
count     105.000000    105.000000     105.000000    105.000000  105.000000
mean        5.809524      3.019048       3.736190      1.179048    1.990476
std         0.833035      0.436572       1.755164      0.764312    0.814475
min         4.300000      2.000000       1.000000      0.100000    1.000000
25%         5.100000      2.800000       1.600000      0.300000    1.000000
50%         5.700000      3.000000       4.200000      1.300000    2.000000
75%         6.400000      3.300000       5.100000      1.800000    3.000000
max         7.900000      4.400000       6.900000      2.500000    3.000000

****** Data Sample ******

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
48             5.3           3.7            1.5           0.2        1
128            6.4           2.8            5.6           2.1        3
75             6.6           3.0            4.4           1.4        2
113            5.7           2.5            5.0           2.0        3
19             5.1           3.8            1.5           0.3        1

========================

==== Test Data Normalized Info ====
****** General Information ******
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 59 to 145
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  45 non-null     float64
 1   SepalWidthCm   45 non-null     float64
 2   PetalLengthCm  45 non-null     float64
 3   PetalWidthCm   45 non-null     float64
 4   Species        45 non-null     int64
dtypes: float64(4), int64(1)
memory usage: 2.1 KB

None

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species
count      45.000000     45.000000      45.000000     45.000000  45.000000
mean        5.922222      3.135556       3.811111      1.244444   2.022222
std         0.820169      0.420041       1.804694      0.767095   0.839071
min         4.400000      2.200000       1.200000      0.100000   1.000000
25%         5.200000      3.000000       1.500000      0.400000   1.000000
50%         5.900000      3.100000       4.500000      1.500000   2.000000
75%         6.500000      3.400000       5.200000      1.800000   3.000000
max         7.700000      4.200000       6.700000      2.400000   3.000000

****** Data Sample ******

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
59             5.2           2.7            3.9           1.4        2
14             5.8           4.0            1.2           0.2        1
32             5.2           4.1            1.5           0.1        1
7              5.0           3.4            1.5           0.2        1
130            7.4           2.8            6.1           1.9        3

=========================

#### Declaring Utils for Layers

In [43]:
def kronecker_delta(i, j):
    return 1 if i == j else 0

#### Declaring Layers

Fuzzifying Layer

In [44]:
class FuzzifyingLayer:
    def __init__(self, membership_functions_count, input_vector_length, c_initial, s_initial):
        self.membership_functions_count = membership_functions_count
        self.input_vector_length = input_vector_length
        self.c = []
        self.s = []

        for i in range(self.input_vector_length):
            self.c.append(c_initial)
            self.s.append(s_initial)

    def fuzzify(self, input_vector):
        memberships_matrix = []

        for i in range(self.input_vector_length):
            x = input_vector[i]
            x_memberships = []

            for j in range(self.membership_functions_count):
                membership = self.calculate_membership_for_x(x, i, j)
                x_memberships.append(membership)

            memberships_matrix.append(x_memberships)

        # vector_memberships = [
        #     x1: [ mu1(x1), mu2(x1), ..., mu(x1)]
        #     x1: [ mu1(x1), mu2(x1), ..., mu(x1)]
        #     ...
        #     x: [ mu1(x), mu2(x), ..., mu(x)]
        # ]

        # print(f"memberships_matrix: {memberships_matrix}", end='\n\n')
        # print(f"s: {self.c}", end='\n\n')
        # print(f"c: {self.s}", end='\n\n')

        return memberships_matrix

    def calculate_membership_for_x(self, x, i, j):
        c, s = self.c[i][j], self.s[i][j]

        membership = 1 / (1 + (((x - c) / s) ** 2))

        return membership

    def train(self, v_c, v_s, predicted_value, actual_values, weights, input_vector):
        c_copy = np.empty_like(self.c)
        s_copy = np.empty_like(self.s)

        for r in range(len(self.c)):
            for l in range(len(self.c[r])):
                c_copy[r][l] = self.calculate_new_c(r, l, weights, v_c, predicted_value, actual_values, input_vector)
                s_copy[r][l] = self.calculate_new_s(r, l, weights, v_s, predicted_value, actual_values, input_vector)

        self.c = c_copy
        self.s = s_copy

    def calculate_new_c(self, r, j, weights, v_c, predicted_value, actual_value, input_vector):
        memberships_matrix = self.fuzzify(input_vector)

        return self.c[r][j] - v_c * self.calculate_de_to_dc(r, j, weights, predicted_value, actual_value, input_vector,
                                                            memberships_matrix)

    def calculate_new_s(self, r, j, weights, v_s, predicted_value, actual_value, input_vector):
        memberships_matrix = self.fuzzify(input_vector)

        return self.s[r][j] - v_s * self.calculate_de_to_ds(r, j, weights, predicted_value, actual_value,
                                                            input_vector, memberships_matrix)

    def calculate_de_to_dc(self, r, j, weights, predicted_value, actual_value, input_vector, memberships_matrix):
        error_derivative = np.sum(predicted_value - actual_value)

        weighted_outputs = 0

        for l in range(len(weights)):
            weighted_outputs += weights[l] * self.calculate_dy_to_dc(l, r, j, input_vector, memberships_matrix)

        return error_derivative * weighted_outputs

    def calculate_de_to_ds(self, r, j, weights, predicted_value, actual_value, input_vector, memberships_matrix):
        error_derivative = np.sum(predicted_value - actual_value)

        weighted_outputs = 0

        for l in range(len(weights)):
            weighted_outputs += weights[l] * self.calculate_dy_to_ds(l, r, j, input_vector, memberships_matrix)

        return error_derivative * weighted_outputs

    def calculate_dy_to_dc(self, l, r, j, input_vector, memberships_matrix):
        m = self.calculate_m(memberships_matrix)
        t = self.calculate_t(l, memberships_matrix)

        first_multiplier = (kronecker_delta(l, r) * m - t) / (m ** 2)
        second_multiplier = self.calculate_t_excluding(r, j, memberships_matrix)
        third_multiplier = self.calculate_dm_to_dc(r, j, input_vector)

        dy_to_dc = first_multiplier * second_multiplier * third_multiplier

        return dy_to_dc

    def calculate_dy_to_ds(self, l, r, j, input_vector, memberships_matrix):
        m = self.calculate_m(memberships_matrix)
        t = self.calculate_t(l, memberships_matrix)

        first_multiplier = (kronecker_delta(l, r) * m - t) / (m ** 2)
        second_multiplier = self.calculate_t_excluding(r, j, memberships_matrix)
        third_multiplier = self.calculate_dm_to_ds(r, j, input_vector)

        dy_to_dc = first_multiplier * second_multiplier * third_multiplier

        return dy_to_dc

    def calculate_dm_to_dc(self, r, j, input_vector):
        x = input_vector[r]
        c = self.c[r][j]
        s = self.s[r][j]

        return math.exp(-(((x - c) ** 2) / (2 * (s ** 2)))) * ((x - c) / (s ** 2))

    def calculate_dm_to_ds(self, r, j, input_vector):
        x = input_vector[r]
        c = self.c[r][j]
        s = self.s[r][j]

        return math.exp(-(((x - c) ** 2) / (2 * (s ** 2)))) * (((x - c) ** 2) / (s ** 3))

    def calculate_m(self, memberships_matrix):
        result = 0

        for p in range(self.membership_functions_count):
            result += self.calculate_t(p, memberships_matrix)

        return result

    def calculate_t(self, l, memberships_matrix):
        result = 1

        for i in range(self.input_vector_length):
            result *= memberships_matrix[i][l]

        return result

    def calculate_t_excluding(self, r, j, memberships_matrix):
        result = 1

        for i in range(self.input_vector_length):
            if i != j:
                result *= memberships_matrix[i][r]

        return result

Aggregation Layer

In [45]:
class AggregatingLayer:
    def __init__(self, membership_functions_count, input_vector_length):
        self.membership_functions_count = membership_functions_count
        self.input_vector_length = input_vector_length

    def aggregate(self, memberships_matrix):
        aggregated_memberships = []

        for i in range(self.membership_functions_count):
            product = 1

            for j in range(self.input_vector_length):
                product *= memberships_matrix[j][i]

            aggregated_memberships.append(product)

        return aggregated_memberships

Linear Layer

In [46]:
class LinearLayer:
    def __init__(self, membership_functions_count, input_vector_length):
        self.membership_functions_count = membership_functions_count
        self.input_vector_length = input_vector_length
        self.weights = np.random.uniform(low=-1, high=1, size=self.membership_functions_count).tolist()

    def process(self, aggregated_memberships):
        weighted_aggregated_memberships_sum = 0
        aggregated_memberships_sum = 0

        for i in range(self.membership_functions_count):
            weighted_aggregated_memberships_sum += self.weights[i] * aggregated_memberships[i]
            aggregated_memberships_sum += aggregated_memberships[i]

        return {
            'f1': weighted_aggregated_memberships_sum,
            'f2': aggregated_memberships_sum,
        }

    def train(self, input_data, expected_output_data, plot_weights=False):
        p_vs = []

        for input_vector in input_data:
            p_v = self.calculate_p_vs(input_vector)
            p_vs.append(p_v)

        pseudo_inverse = np.linalg.pinv(p_vs)
        new_weights = np.matmul(pseudo_inverse, expected_output_data)

        if plot_weights:
            plt.clf()
            plt.plot(self.weights, color='r', label='Previous Weights')
            plt.plot(new_weights, color='g', label='New Weights')
            plt.legend()
            plt.show()

        self.weights = new_weights

    def calculate_p_vs(self, memberships_matrix):
        values = []
        p_vs = []

        for i in range(self.membership_functions_count):
            value = 1

            for j in range(self.input_vector_length):
                value *= memberships_matrix[j][i]

            values.append(value)

        for i in range(len(values)):
            numerator = values[i]
            denominator = 0

            for j in range(len(values)):
                denominator += values[j]

            p_vs.append(numerator / denominator)

        return p_vs

Activation Layer

In [47]:
class ActivationLayer:
    def diffuzify(self, fs_dict):
        # return np.round(fs_dict['f1'] / fs_dict['f2'], 0)
        return fs_dict['f1'] / fs_dict['f2']

### WangMendel Fuzzy Neural Network

In [49]:
class WangMendelFuzzyNeuralNetwork:
    def __init__(self, membership_functions_count, input_vector_length, c_initial, s_initial):
        self.fuzzifying_layer = FuzzifyingLayer(membership_functions_count, input_vector_length, c_initial, s_initial)
        self.aggregating_layer = AggregatingLayer(membership_functions_count, input_vector_length)
        self.linear_layer = LinearLayer(membership_functions_count, input_vector_length)
        self.activation_layer = ActivationLayer()

    def predict_exact(self, input_vector):
        return np.round(self.predict(input_vector), 0)

    def predict(self, input_vector):
        fuzzifying_layer_output = self.fuzzifying_layer.fuzzify(input_vector)
        aggregating_layer_output = self.aggregating_layer.aggregate(fuzzifying_layer_output)
        linear_layer_output = self.linear_layer.process(aggregating_layer_output)
        activation_layer_output = self.activation_layer.diffuzify(linear_layer_output)

        return activation_layer_output

    def predict_for_matrix(self, input_data):
        predictions = []

        for input_vector in input_data:
            prediction = self.predict(input_vector)
            predictions.append(prediction)

        return predictions

    def predict_and_validate(self, input_data, expected_output_data, detailed_output=False):
        predicted_output_data = self.predict_for_matrix(input_data)

        total_predictions = len(predicted_output_data)
        correct_predictions = 0

        for i in range(total_predictions):
            predicted_value = predicted_output_data[i]
            predicted_value_rounded = np.round(predicted_value, 0)
            expected_value = expected_output_data[i]

            is_predicted_equal_to_expected = predicted_value_rounded == expected_value

            if is_predicted_equal_to_expected:
                correct_predictions += 1

            if detailed_output:
                print(
                    f'Predicted: {predicted_value}; Actual: {expected_value}; {'✅' if is_predicted_equal_to_expected else '❌'}')

        mse = (np.square(predicted_output_data - expected_output_data)).mean()
        accuracy = np.round(correct_predictions / total_predictions * 100, 0)

        print(f'MSE: {mse}')
        print(f'Accuracy: {accuracy}')

        return [mse, accuracy]

    def train(self, epochs, training_data_df, c_nu=0.5, s_nu=0.5, max_epochs_with_no_mse_change=2):
        print(f'Started training for {epochs} epochs', end='\n')

        input_data = np.array(training_data_df.iloc[:, :-1].values, dtype=float)
        expected_output_data = np.array(training_data_df.iloc[:, -1].values, dtype=float)

        start_time = time.time()

        current_mse = 1
        epochs_without_mse_change = 0
        completed_epochs = 0

        training_vectors_count = len(input_data)

        for i in trange(epochs, desc='Epochs progress'):
            print(f'Epoch {i + 1} started', end='\n')

            # print(f"====\nCs: {self.fuzzifying_layer.c}\n")
            # print(f"Ss: {self.fuzzifying_layer.s}\n\n====\n")

            self.train_linear_layer(input_data, expected_output_data)

            for j in trange(100, desc='Data passes per epoch progress', leave=False):
                predicted_data = self.predict_for_matrix(input_data)

                for k in range(training_vectors_count):
                    self.fuzzifying_layer.train(
                        c_nu,
                        s_nu,
                        predicted_data,
                        expected_output_data,
                        self.linear_layer.weights,
                        input_data[k]
                    )

            [mse, accuracy] = self.predict_and_validate(input_data, expected_output_data, detailed_output=True)

            previous_mse = current_mse
            current_mse = mse
            mse_change = previous_mse - current_mse

            if mse_change == 0:
                epochs_without_mse_change += 1

            if epochs_without_mse_change == max_epochs_with_no_mse_change:
                print(f'MSE hasn\'t changed during last {max_epochs_with_no_mse_change} epochs; Training ended',
                      end='\n')
                break

            completed_epochs += 1
            print(f'Epoch {i + 1} completed', end='\n')

        end_time = time.time()
        elapsed_time = np.round(end_time - start_time, 0)

        print(f'Finished training in {elapsed_time}s in {completed_epochs} epochs', end='\n')

    def train_linear_layer(self, input_data, expected_output_data):
        input_data_fuzzified = []

        for input_vector in input_data:
            fuzzified_vector = self.fuzzifying_layer.fuzzify(input_vector)
            input_data_fuzzified.append(fuzzified_vector)

        self.linear_layer.train(input_data_fuzzified, expected_output_data)

    def save_to_file(self, file_name):
        c = self.fuzzifying_layer.c
        s = self.fuzzifying_layer.s
        weights = self.linear_layer.weights

        np.savez(f"{file_name}.npz", c=c, s=s, weights=weights)

    def initialize_from_file(self, file_name):
        file = np.load(f"{file_name}.npz")

        self.fuzzifying_layer.c = file['c']
        self.fuzzifying_layer.s = file['s']
        self.linear_layer.weights = file['weights']

#### Training

In [50]:
min_class = get_column_min(train_df, result_columns[0])
max_class = get_column_max(train_df, result_columns[0])

membership_functions_count = 12

# TODO: add utility method to extract x_vector and y
input_vector_length = len(np.array(train_df.iloc[:, :-1].values, dtype=float)[0])

c_initial = np.linspace(min_class, max_class, membership_functions_count).tolist()
s_initial = np.full(membership_functions_count, 0.1).tolist()

wangMendelFuzzyNeuralNetwork = WangMendelFuzzyNeuralNetwork(membership_functions_count, input_vector_length, c_initial,
                                                            s_initial)

wangMendelFuzzyNeuralNetwork.train(10, train_df, 0.5, 0.5, 2)

Started training for 10 epochs

Epochs progress:   0%|          | 0/10 [00:00<?, ?it/s]

Epoch 1 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 0.269565534648848; Actual: 1.0; ❌
Predicted: 1.2873286286609937; Actual: 3.0; ❌
Predicted: 0.6251893121004694; Actual: 2.0; ❌
Predicted: 0.9998012295370279; Actual: 3.0; ❌
Predicted: 0.4439704892943457; Actual: 1.0; ❌
Predicted: 0.6244614291269123; Actual: 2.0; ❌
Predicted: 0.3003485691578028; Actual: 1.0; ❌
Predicted: 0.20639018807694812; Actual: 2.0; ❌
Predicted: 1.390495428418427; Actual: 3.0; ❌
Predicted: 0.2938298711522603; Actual: 2.0; ❌
Predicted: 2.0465533032573253; Actual: 3.0; ❌
Predicted: 0.46151459293700525; Actual: 2.0; ❌
Predicted: 0.21302406778342828; Actual: 1.0; ❌
Predicted: 0.2706946223317202; Actual: 1.0; ❌
Predicted: 0.16488990872812376; Actual: 1.0; ❌
Predicted: 0.252154657115005; Actual: 2.0; ❌
Predicted: 0.24253929912159428; Actual: 1.0; ❌
Predicted: 1.9028262375765992; Actual: 3.0; ❌
Predicted: 0.08771159743874937; Actual: 2.0; ❌
Predicted: 0.12334294647683047; Actual: 1.0; ❌
Predicted: 0.6224167469775951; Actual: 2.0; ❌
Predicted: 0.055290239114341444; Actual: 2.0; ❌
Predicted: 0.07653837666038935; Actual: 1.0; ❌
Predicted: -0.2197835689802147; Actual: 2.0; ❌
Predicted: 0.017330259838327765; Actual: 2.0; ❌
Predicted: 0.7981428772026092; Actual: 3.0; ❌
Predicted: 0.07037696646517778; Actual: 2.0; ❌
Predicted: 0.880137847064268; Actual: 3.0; ❌
Predicted: 0.16639695926990672; Actual: 1.0; ❌
Predicted: 1.0044011054391995; Actual: 3.0; ❌
Predicted: 0.6264335210378159; Actual: 1.0; ✅
Predicted: 0.39130608514215043; Actual: 1.0; ❌
Predicted: 0.44912284160010557; Actual: 1.0; ❌
Predicted: 1.549545328028637; Actual: 3.0; ❌
Predicted: 0.5570393284435289; Actual: 1.0; ✅
Predicted: 1.7766313136703844; Actual: 3.0; ❌
Predicted: 0.904386880540819; Actual: 3.0; ❌
Predicted: 0.8866353851368216; Actual: 2.0; ❌
Predicted: 0.2969794234195531; Actual: 2.0; ❌
Predicted: 0.473316548865439; Actual: 2.0; ❌
Predicted: 0.122783376066998; Actual: 1.0; ❌
Predicted: 0.681704251108897; Actual: 2.0; ❌
Predicted: 0.18249615365429356; Actual: 1.0; ❌
Predicted: 0.4202281978636212; Actual: 2.0; ❌
Predicted: 0.8282064101429112; Actual: 2.0; ❌
Predicted: 1.55694034403969; Actual: 3.0; ❌
Predicted: -0.057105108203766436; Actual: 1.0; ❌
Predicted: 0.5718033434351503; Actual: 2.0; ❌
Predicted: 0.5131378456374442; Actual: 1.0; ✅
Predicted: 0.8600689555845238; Actual: 2.0; ❌
Predicted: 1.8106541660295765; Actual: 3.0; ❌
Predicted: -0.019866105007197928; Actual: 1.0; ❌
Predicted: 0.6936546004569549; Actual: 2.0; ❌
Predicted: 0.097796097695204; Actual: 1.0; ❌
Predicted: 1.5434406234052178; Actual: 3.0; ❌
Predicted: 2.0699365189533467; Actual: 3.0; ❌
Predicted: 0.15820424040503067; Actual: 1.0; ❌
Predicted: -0.06571814300737693; Actual: 2.0; ❌
Predicted: 1.0243693562372413; Actual: 3.0; ❌
Predicted: 1.0461984695742779; Actual: 3.0; ❌
Predicted: 0.48714160183627536; Actual: 1.0; ❌
Predicted: 0.41097534080961645; Actual: 2.0; ❌
Predicted: -0.019866105007197928; Actual: 1.0; ❌
Predicted: 1.2460311360559897; Actual: 3.0; ❌
Predicted: 0.6240429410348309; Actual: 2.0; ❌
Predicted: 0.1868427920980143; Actual: 1.0; ❌
Predicted: 1.3765507418865364; Actual: 3.0; ❌
Predicted: 0.9275997771721708; Actual: 3.0; ❌
Predicted: 0.15934146105867486; Actual: 1.0; ❌
Predicted: 0.41377268698846525; Actual: 2.0; ❌
Predicted: 0.7796415897416914; Actual: 3.0; ❌
Predicted: 0.6705932720810645; Actual: 2.0; ❌
Predicted: 0.8708734844690296; Actual: 2.0; ❌
Predicted: 0.15345186127109878; Actual: 2.0; ❌
Predicted: 1.8750761228789457; Actual: 3.0; ❌
Predicted: 1.722336411549676; Actual: 3.0; ❌
Predicted: 0.5392385693211363; Actual: 2.0; ❌
Predicted: -0.019866105007197928; Actual: 1.0; ❌
Predicted: -0.01682072041695496; Actual: 2.0; ❌
Predicted: 0.7225216071352484; Actual: 3.0; ❌
Predicted: 0.2702872095525107; Actual: 1.0; ❌
Predicted: 0.3014552082284292; Actual: 1.0; ❌
Predicted: 0.4034257757379887; Actual: 1.0; ❌
Predicted: -0.056501040155642286; Actual: 1.0; ❌
Predicted: 0.9419726884161493; Actual: 3.0; ❌
Predicted: 0.9555014029958829; Actual: 2.0; ❌
Predicted: 1.0210795527863177; Actual: 3.0; ❌
Predicted: 0.2987345791886156; Actual: 1.0; ❌
Predicted: 0.8483882909777561; Actual: 3.0; ❌
Predicted: -0.2605761026547771; Actual: 2.0; ❌
Predicted: 2.0934698221540042; Actual: 3.0; ❌
Predicted: -0.35061047612017193; Actual: 1.0; ❌
Predicted: 1.0086996060326494; Actual: 3.0; ❌
Predicted: 1.352601844569205; Actual: 3.0; ❌
Predicted: 1.6230770033001691; Actual: 3.0; ❌
Predicted: 0.9842967296731476; Actual: 2.0; ❌
Predicted: 0.08758138095485721; Actual: 2.0; ❌
Predicted: 0.4363100249762311; Actual: 2.0; ❌
Predicted: 1.0009710835847951; Actual: 3.0; ❌
Predicted: 0.4766999372071304; Actual: 3.0; ❌
Predicted: 1.4428291033841034; Actual: 3.0; ❌
Predicted: 0.2792257749489618; Actual: 2.0; ❌
Predicted: 0.3134621063278343; Actual: 1.0; ❌
Predicted: 0.4529808759492121; Actual: 1.0; ❌
Predicted: 0.09640736241252473; Actual: 1.0; ❌
MSE: 2.1163094926445476
Accuracy: 3.0
Epoch 1 completed
Epoch 2 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 0.9678557535865484; Actual: 1.0; ✅
Predicted: 2.9924753616777378; Actual: 3.0; ✅
Predicted: 2.1484528140135724; Actual: 2.0; ✅
Predicted: 3.017368368232123; Actual: 3.0; ✅
Predicted: 1.1132236795144876; Actual: 1.0; ✅
Predicted: 2.110847014547276; Actual: 2.0; ✅
Predicted: 0.9949735490533348; Actual: 1.0; ✅
Predicted: 2.0205270078806254; Actual: 2.0; ✅
Predicted: 3.388889788029211; Actual: 3.0; ✅
Predicted: 2.0359484151420455; Actual: 2.0; ✅
Predicted: 2.988528009100123; Actual: 3.0; ✅
Predicted: 2.095071788531499; Actual: 2.0; ✅
Predicted: 1.0123487959142707; Actual: 1.0; ✅
Predicted: 1.0228229798573962; Actual: 1.0; ✅
Predicted: 0.9706470000789317; Actual: 1.0; ✅
Predicted: 2.0804060778866407; Actual: 2.0; ✅
Predicted: 0.9458338334696335; Actual: 1.0; ✅
Predicted: 2.9307983141388436; Actual: 3.0; ✅
Predicted: 1.7931356242071184; Actual: 2.0; ✅
Predicted: 0.927014786814685; Actual: 1.0; ✅
Predicted: 2.2066814603450635; Actual: 2.0; ✅
Predicted: 2.31369853629447; Actual: 2.0; ✅
Predicted: 0.9445616767571713; Actual: 1.0; ✅
Predicted: 2.1745364674251793; Actual: 2.0; ✅
Predicted: 1.9732274769830023; Actual: 2.0; ✅
Predicted: 2.9182393428744806; Actual: 3.0; ✅
Predicted: 1.9378356676532624; Actual: 2.0; ✅
Predicted: 2.8379968162817297; Actual: 3.0; ✅
Predicted: 1.0136102544570162; Actual: 1.0; ✅
Predicted: 2.751232022771089; Actual: 3.0; ✅
Predicted: 1.2062919726999632; Actual: 1.0; ✅
Predicted: 1.0517900668395754; Actual: 1.0; ✅
Predicted: 1.0774893048343428; Actual: 1.0; ✅
Predicted: 2.8701930678209027; Actual: 3.0; ✅
Predicted: 1.1216573509387768; Actual: 1.0; ✅
Predicted: 3.0077252453249117; Actual: 3.0; ✅
Predicted: 2.7776651254911413; Actual: 3.0; ✅
Predicted: 2.0932199952800956; Actual: 2.0; ✅
Predicted: 1.8766019273160677; Actual: 2.0; ✅
Predicted: 2.118567517351193; Actual: 2.0; ✅
Predicted: 0.9040421201389636; Actual: 1.0; ✅
Predicted: 2.187403693233379; Actual: 2.0; ✅
Predicted: 0.9962663170636611; Actual: 1.0; ✅
Predicted: 2.1500623508249883; Actual: 2.0; ✅
Predicted: 2.8604471452219533; Actual: 2.0; ❌
Predicted: 3.007272317968181; Actual: 3.0; ✅
Predicted: 0.8445056238919701; Actual: 1.0; ✅
Predicted: 2.070326540658144; Actual: 2.0; ✅
Predicted: 1.294457058992914; Actual: 1.0; ✅
Predicted: 2.1285908886444687; Actual: 2.0; ✅
Predicted: 3.0825914931418374; Actual: 3.0; ✅
Predicted: 0.8498735979893935; Actual: 1.0; ✅
Predicted: 2.1430983741117946; Actual: 2.0; ✅
Predicted: 0.8512737771125931; Actual: 1.0; ✅
Predicted: 2.829734708023284; Actual: 3.0; ✅
Predicted: 3.0016742673613876; Actual: 3.0; ✅
Predicted: 0.9378873275889164; Actual: 1.0; ✅
Predicted: 1.8535266922900904; Actual: 2.0; ✅
Predicted: 2.7653122353582473; Actual: 3.0; ✅
Predicted: 3.0303206664309084; Actual: 3.0; ✅
Predicted: 1.153012474012269; Actual: 1.0; ✅
Predicted: 2.1024896387260084; Actual: 2.0; ✅
Predicted: 0.8498735979893935; Actual: 1.0; ✅
Predicted: 2.8646376588129248; Actual: 3.0; ✅
Predicted: 2.2788776208744617; Actual: 2.0; ✅
Predicted: 0.9395547893644514; Actual: 1.0; ✅
Predicted: 2.915653145250745; Actual: 3.0; ✅
Predicted: 2.842284909035711; Actual: 3.0; ✅
Predicted: 0.9583130570557236; Actual: 1.0; ✅
Predicted: 2.084378114178826; Actual: 2.0; ✅
Predicted: 2.1828046710232605; Actual: 3.0; ❌
Predicted: 2.1360130631956333; Actual: 2.0; ✅
Predicted: 2.101722782965629; Actual: 2.0; ✅
Predicted: 2.295040338866279; Actual: 2.0; ✅
Predicted: 3.0260397420122462; Actual: 3.0; ✅
Predicted: 2.9798126347591674; Actual: 3.0; ✅
Predicted: 2.117698283206371; Actual: 2.0; ✅
Predicted: 0.8498735979893935; Actual: 1.0; ✅
Predicted: 1.878822522950153; Actual: 2.0; ✅
Predicted: 2.915306450734505; Actual: 3.0; ✅
Predicted: 1.0223876157604594; Actual: 1.0; ✅
Predicted: 1.0041322833096795; Actual: 1.0; ✅
Predicted: 1.1382601548795315; Actual: 1.0; ✅
Predicted: 0.8788651807924595; Actual: 1.0; ✅
Predicted: 2.80135554452613; Actual: 3.0; ✅
Predicted: 2.1216171665335604; Actual: 2.0; ✅
Predicted: 2.766149957921281; Actual: 3.0; ✅
Predicted: 1.0357987019645152; Actual: 1.0; ✅
Predicted: 2.804015029598168; Actual: 3.0; ✅
Predicted: 2.0109214469937124; Actual: 2.0; ✅
Predicted: 2.982029193116448; Actual: 3.0; ✅
Predicted: 1.0130184925253496; Actual: 1.0; ✅
Predicted: 2.7765418783367943; Actual: 3.0; ✅
Predicted: 2.948176566545814; Actual: 3.0; ✅
Predicted: 3.083402571642519; Actual: 3.0; ✅
Predicted: 2.127389597434074; Actual: 2.0; ✅
Predicted: 1.8418673401209267; Actual: 2.0; ✅
Predicted: 2.083893913084819; Actual: 2.0; ✅
Predicted: 2.836508041019261; Actual: 3.0; ✅
Predicted: 2.5021499749004636; Actual: 3.0; ✅
Predicted: 3.063352693382787; Actual: 3.0; ✅
Predicted: 1.9877219445769676; Actual: 2.0; ✅
Predicted: 0.9216028167291064; Actual: 1.0; ✅
Predicted: 1.1595111767796165; Actual: 1.0; ✅
Predicted: 0.998464171059288; Actual: 1.0; ✅
MSE: 0.033170067858676495
Accuracy: 98.0
Epoch 2 completed
Epoch 3 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 0.9678557535865453; Actual: 1.0; ✅
Predicted: 2.9924753616777404; Actual: 3.0; ✅
Predicted: 2.1484528140135657; Actual: 2.0; ✅
Predicted: 3.0173683682321175; Actual: 3.0; ✅
Predicted: 1.113223679514487; Actual: 1.0; ✅
Predicted: 2.1108470145472698; Actual: 2.0; ✅
Predicted: 0.9949735490533288; Actual: 1.0; ✅
Predicted: 2.0205270078806166; Actual: 2.0; ✅
Predicted: 3.3888897880292124; Actual: 3.0; ✅
Predicted: 2.0359484151420366; Actual: 2.0; ✅
Predicted: 2.9885280091001327; Actual: 3.0; ✅
Predicted: 2.0950717885314916; Actual: 2.0; ✅
Predicted: 1.0123487959142707; Actual: 1.0; ✅
Predicted: 1.022822979857394; Actual: 1.0; ✅
Predicted: 0.9706470000789321; Actual: 1.0; ✅
Predicted: 2.080406077886634; Actual: 2.0; ✅
Predicted: 0.9458338334696288; Actual: 1.0; ✅
Predicted: 2.9307983141388587; Actual: 3.0; ✅
Predicted: 1.7931356242071086; Actual: 2.0; ✅
Predicted: 0.9270147868146831; Actual: 1.0; ✅
Predicted: 2.2066814603450586; Actual: 2.0; ✅
Predicted: 2.3136985362944644; Actual: 2.0; ✅
Predicted: 0.9445616767571703; Actual: 1.0; ✅
Predicted: 2.174536467425154; Actual: 2.0; ✅
Predicted: 1.973227476982993; Actual: 2.0; ✅
Predicted: 2.9182393428744744; Actual: 3.0; ✅
Predicted: 1.937835667653254; Actual: 2.0; ✅
Predicted: 2.8379968162817306; Actual: 3.0; ✅
Predicted: 1.0136102544570171; Actual: 1.0; ✅
Predicted: 2.751232022771089; Actual: 3.0; ✅
Predicted: 1.2062919726999615; Actual: 1.0; ✅
Predicted: 1.051790066839574; Actual: 1.0; ✅
Predicted: 1.0774893048343475; Actual: 1.0; ✅
Predicted: 2.8701930678209107; Actual: 3.0; ✅
Predicted: 1.1216573509387768; Actual: 1.0; ✅
Predicted: 3.007725245324923; Actual: 3.0; ✅
Predicted: 2.7776651254911395; Actual: 3.0; ✅
Predicted: 2.093219995280096; Actual: 2.0; ✅
Predicted: 1.8766019273160617; Actual: 2.0; ✅
Predicted: 2.1185675173511855; Actual: 2.0; ✅
Predicted: 0.9040421201389601; Actual: 1.0; ✅
Predicted: 2.1874036932333754; Actual: 2.0; ✅
Predicted: 0.9962663170636608; Actual: 1.0; ✅
Predicted: 2.1500623508249808; Actual: 2.0; ✅
Predicted: 2.860447145221955; Actual: 2.0; ❌
Predicted: 3.0072723179681877; Actual: 3.0; ✅
Predicted: 0.84450562389197; Actual: 1.0; ✅
Predicted: 2.070326540658137; Actual: 2.0; ✅
Predicted: 1.2944570589929143; Actual: 1.0; ✅
Predicted: 2.1285908886444687; Actual: 2.0; ✅
Predicted: 3.082591493141844; Actual: 3.0; ✅
Predicted: 0.8498735979893917; Actual: 1.0; ✅
Predicted: 2.1430983741117884; Actual: 2.0; ✅
Predicted: 0.8512737771125893; Actual: 1.0; ✅
Predicted: 2.8297347080232895; Actual: 3.0; ✅
Predicted: 3.0016742673613983; Actual: 3.0; ✅
Predicted: 0.9378873275889139; Actual: 1.0; ✅
Predicted: 1.853526692290082; Actual: 2.0; ✅
Predicted: 2.765312235358248; Actual: 3.0; ✅
Predicted: 3.030320666430909; Actual: 3.0; ✅
Predicted: 1.153012474012266; Actual: 1.0; ✅
Predicted: 2.1024896387259995; Actual: 2.0; ✅
Predicted: 0.8498735979893917; Actual: 1.0; ✅
Predicted: 2.864637658812925; Actual: 3.0; ✅
Predicted: 2.2788776208744617; Actual: 2.0; ✅
Predicted: 0.9395547893644483; Actual: 1.0; ✅
Predicted: 2.9156531452507486; Actual: 3.0; ✅
Predicted: 2.8422849090357096; Actual: 3.0; ✅
Predicted: 0.9583130570557257; Actual: 1.0; ✅
Predicted: 2.084378114178817; Actual: 2.0; ✅
Predicted: 2.182804671023262; Actual: 3.0; ❌
Predicted: 2.136013063195627; Actual: 2.0; ✅
Predicted: 2.1017227829656298; Actual: 2.0; ✅
Predicted: 2.2950403388662695; Actual: 2.0; ✅
Predicted: 3.026039742012256; Actual: 3.0; ✅
Predicted: 2.9798126347591745; Actual: 3.0; ✅
Predicted: 2.1176982832063644; Actual: 2.0; ✅
Predicted: 0.8498735979893917; Actual: 1.0; ✅
Predicted: 1.8788225229501416; Actual: 2.0; ✅
Predicted: 2.9153064507345055; Actual: 3.0; ✅
Predicted: 1.0223876157604592; Actual: 1.0; ✅
Predicted: 1.0041322833096784; Actual: 1.0; ✅
Predicted: 1.138260154879533; Actual: 1.0; ✅
Predicted: 0.8788651807924579; Actual: 1.0; ✅
Predicted: 2.8013555445261296; Actual: 3.0; ✅
Predicted: 2.1216171665335626; Actual: 2.0; ✅
Predicted: 2.7661499579212823; Actual: 3.0; ✅
Predicted: 1.0357987019645156; Actual: 1.0; ✅
Predicted: 2.8040150295981663; Actual: 3.0; ✅
Predicted: 2.010921446993707; Actual: 2.0; ✅
Predicted: 2.9820291931164586; Actual: 3.0; ✅
Predicted: 1.0130184925253447; Actual: 1.0; ✅
Predicted: 2.776541878336795; Actual: 3.0; ✅
Predicted: 2.948176566545818; Actual: 3.0; ✅
Predicted: 3.0834025716425257; Actual: 3.0; ✅
Predicted: 2.1273895974340764; Actual: 2.0; ✅
Predicted: 1.841867340120917; Actual: 2.0; ✅
Predicted: 2.08389391308481; Actual: 2.0; ✅
Predicted: 2.8365080410192602; Actual: 3.0; ✅
Predicted: 2.502149974900465; Actual: 3.0; ✅
Predicted: 3.06335269338279; Actual: 3.0; ✅
Predicted: 1.9877219445769585; Actual: 2.0; ✅
Predicted: 0.9216028167291056; Actual: 1.0; ✅
Predicted: 1.1595111767796156; Actual: 1.0; ✅
Predicted: 0.9984641710592878; Actual: 1.0; ✅
MSE: 0.033170067858676267
Accuracy: 98.0
Epoch 3 completed
Epoch 4 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 0.9678557535865342; Actual: 1.0; ✅
Predicted: 2.9924753616777378; Actual: 3.0; ✅
Predicted: 2.148452814013588; Actual: 2.0; ✅
Predicted: 3.0173683682321135; Actual: 3.0; ✅
Predicted: 1.1132236795144779; Actual: 1.0; ✅
Predicted: 2.1108470145472946; Actual: 2.0; ✅
Predicted: 0.9949735490533215; Actual: 1.0; ✅
Predicted: 2.0205270078806503; Actual: 2.0; ✅
Predicted: 3.388889788029178; Actual: 3.0; ✅
Predicted: 2.0359484151420784; Actual: 2.0; ✅
Predicted: 2.9885280091001194; Actual: 3.0; ✅
Predicted: 2.09507178853152; Actual: 2.0; ✅
Predicted: 1.0123487959142632; Actual: 1.0; ✅
Predicted: 1.0228229798573831; Actual: 1.0; ✅
Predicted: 0.9706470000789214; Actual: 1.0; ✅
Predicted: 2.0804060778866718; Actual: 2.0; ✅
Predicted: 0.9458338334696176; Actual: 1.0; ✅
Predicted: 2.9307983141388587; Actual: 3.0; ✅
Predicted: 1.7931356242071517; Actual: 2.0; ✅
Predicted: 0.927014786814673; Actual: 1.0; ✅
Predicted: 2.2066814603450844; Actual: 2.0; ✅
Predicted: 2.313698536294503; Actual: 2.0; ✅
Predicted: 0.9445616767571676; Actual: 1.0; ✅
Predicted: 2.174536467425171; Actual: 2.0; ✅
Predicted: 1.9732274769830294; Actual: 2.0; ✅
Predicted: 2.918239342874478; Actual: 3.0; ✅
Predicted: 1.9378356676532917; Actual: 2.0; ✅
Predicted: 2.8379968162817395; Actual: 3.0; ✅
Predicted: 1.0136102544570078; Actual: 1.0; ✅
Predicted: 2.7512320227710942; Actual: 3.0; ✅
Predicted: 1.2062919726999501; Actual: 1.0; ✅
Predicted: 1.0517900668395679; Actual: 1.0; ✅
Predicted: 1.0774893048343295; Actual: 1.0; ✅
Predicted: 2.8701930678209147; Actual: 3.0; ✅
Predicted: 1.1216573509387797; Actual: 1.0; ✅
Predicted: 3.0077252453249144; Actual: 3.0; ✅
Predicted: 2.777665125491143; Actual: 3.0; ✅
Predicted: 2.0932199952801103; Actual: 2.0; ✅
Predicted: 1.876601927316089; Actual: 2.0; ✅
Predicted: 2.1185675173512117; Actual: 2.0; ✅
Predicted: 0.9040421201389479; Actual: 1.0; ✅
Predicted: 2.1874036932333993; Actual: 2.0; ✅
Predicted: 0.9962663170636584; Actual: 1.0; ✅
Predicted: 2.1500623508250087; Actual: 2.0; ✅
Predicted: 2.860447145221954; Actual: 2.0; ❌
Predicted: 3.0072723179681824; Actual: 3.0; ✅
Predicted: 0.8445056238919632; Actual: 1.0; ✅
Predicted: 2.0703265406581566; Actual: 2.0; ✅
Predicted: 1.2944570589929099; Actual: 1.0; ✅
Predicted: 2.128590888644482; Actual: 2.0; ✅
Predicted: 3.0825914931418277; Actual: 3.0; ✅
Predicted: 0.8498735979893869; Actual: 1.0; ✅
Predicted: 2.1430983741118124; Actual: 2.0; ✅
Predicted: 0.8512737771125723; Actual: 1.0; ✅
Predicted: 2.829734708023294; Actual: 3.0; ✅
Predicted: 3.001674267361386; Actual: 3.0; ✅
Predicted: 0.9378873275889055; Actual: 1.0; ✅
Predicted: 1.8535266922901221; Actual: 2.0; ✅
Predicted: 2.765312235358255; Actual: 3.0; ✅
Predicted: 3.0303206664309097; Actual: 3.0; ✅
Predicted: 1.1530124740122614; Actual: 1.0; ✅
Predicted: 2.102489638726033; Actual: 2.0; ✅
Predicted: 0.8498735979893869; Actual: 1.0; ✅
Predicted: 2.864637658812928; Actual: 3.0; ✅
Predicted: 2.278877620874481; Actual: 2.0; ✅
Predicted: 0.9395547893644385; Actual: 1.0; ✅
Predicted: 2.915653145250748; Actual: 3.0; ✅
Predicted: 2.8422849090357163; Actual: 3.0; ✅
Predicted: 0.9583130570557116; Actual: 1.0; ✅
Predicted: 2.084378114178843; Actual: 2.0; ✅
Predicted: 2.18280467102328; Actual: 3.0; ❌
Predicted: 2.1360130631956484; Actual: 2.0; ✅
Predicted: 2.1017227829656453; Actual: 2.0; ✅
Predicted: 2.295040338866297; Actual: 2.0; ✅
Predicted: 3.026039742012243; Actual: 3.0; ✅
Predicted: 2.979812634759165; Actual: 3.0; ✅
Predicted: 2.117698283206391; Actual: 2.0; ✅
Predicted: 0.8498735979893869; Actual: 1.0; ✅
Predicted: 1.878822522950171; Actual: 2.0; ✅
Predicted: 2.915306450734514; Actual: 3.0; ✅
Predicted: 1.022387615760455; Actual: 1.0; ✅
Predicted: 1.0041322833096669; Actual: 1.0; ✅
Predicted: 1.138260154879525; Actual: 1.0; ✅
Predicted: 0.8788651807924566; Actual: 1.0; ✅
Predicted: 2.8013555445261376; Actual: 3.0; ✅
Predicted: 2.1216171665335755; Actual: 2.0; ✅
Predicted: 2.76614995792129; Actual: 3.0; ✅
Predicted: 1.0357987019645019; Actual: 1.0; ✅
Predicted: 2.80401502959817; Actual: 3.0; ✅
Predicted: 2.0109214469937586; Actual: 2.0; ✅
Predicted: 2.982029193116447; Actual: 3.0; ✅
Predicted: 1.0130184925253416; Actual: 1.0; ✅
Predicted: 2.7765418783368037; Actual: 3.0; ✅
Predicted: 2.948176566545817; Actual: 3.0; ✅
Predicted: 3.08340257164251; Actual: 3.0; ✅
Predicted: 2.1273895974340893; Actual: 2.0; ✅
Predicted: 1.841867340120945; Actual: 2.0; ✅
Predicted: 2.083893913084839; Actual: 2.0; ✅
Predicted: 2.836508041019265; Actual: 3.0; ✅
Predicted: 2.5021499749004836; Actual: 3.0; ✅
Predicted: 3.0633526933827815; Actual: 3.0; ✅
Predicted: 1.9877219445769891; Actual: 2.0; ✅
Predicted: 0.9216028167291099; Actual: 1.0; ✅
Predicted: 1.1595111767796074; Actual: 1.0; ✅
Predicted: 0.9984641710592816; Actual: 1.0; ✅
MSE: 0.03317006785867628
Accuracy: 98.0
Epoch 4 completed
Epoch 5 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 0.9678557535865392; Actual: 1.0; ✅
Predicted: 2.9924753616777378; Actual: 3.0; ✅
Predicted: 2.148452814013576; Actual: 2.0; ✅
Predicted: 3.017368368232114; Actual: 3.0; ✅
Predicted: 1.113223679514483; Actual: 1.0; ✅
Predicted: 2.110847014547283; Actual: 2.0; ✅
Predicted: 0.9949735490533238; Actual: 1.0; ✅
Predicted: 2.0205270078806343; Actual: 2.0; ✅
Predicted: 3.3888897880291853; Actual: 3.0; ✅
Predicted: 2.0359484151420593; Actual: 2.0; ✅
Predicted: 2.988528009100128; Actual: 3.0; ✅
Predicted: 2.0950717885315053; Actual: 2.0; ✅
Predicted: 1.0123487959142685; Actual: 1.0; ✅
Predicted: 1.0228229798573887; Actual: 1.0; ✅
Predicted: 0.9706470000789278; Actual: 1.0; ✅
Predicted: 2.0804060778866558; Actual: 2.0; ✅
Predicted: 0.9458338334696222; Actual: 1.0; ✅
Predicted: 2.9307983141388636; Actual: 3.0; ✅
Predicted: 1.7931356242071321; Actual: 2.0; ✅
Predicted: 0.9270147868146784; Actual: 1.0; ✅
Predicted: 2.2066814603450715; Actual: 2.0; ✅
Predicted: 2.313698536294487; Actual: 2.0; ✅
Predicted: 0.9445616767571692; Actual: 1.0; ✅
Predicted: 2.174536467425162; Actual: 2.0; ✅
Predicted: 1.9732274769830147; Actual: 2.0; ✅
Predicted: 2.9182393428744744; Actual: 3.0; ✅
Predicted: 1.937835667653276; Actual: 2.0; ✅
Predicted: 2.837996816281732; Actual: 3.0; ✅
Predicted: 1.0136102544570142; Actual: 1.0; ✅
Predicted: 2.7512320227710894; Actual: 3.0; ✅
Predicted: 1.2062919726999564; Actual: 1.0; ✅
Predicted: 1.0517900668395712; Actual: 1.0; ✅
Predicted: 1.0774893048343408; Actual: 1.0; ✅
Predicted: 2.870193067820915; Actual: 3.0; ✅
Predicted: 1.1216573509387813; Actual: 1.0; ✅
Predicted: 3.00772524532492; Actual: 3.0; ✅
Predicted: 2.777665125491138; Actual: 3.0; ✅
Predicted: 2.0932199952800996; Actual: 2.0; ✅
Predicted: 1.87660192731608; Actual: 2.0; ✅
Predicted: 2.1185675173511984; Actual: 2.0; ✅
Predicted: 0.904042120138954; Actual: 1.0; ✅
Predicted: 2.187403693233387; Actual: 2.0; ✅
Predicted: 0.9962663170636606; Actual: 1.0; ✅
Predicted: 2.1500623508249967; Actual: 2.0; ✅
Predicted: 2.8604471452219475; Actual: 2.0; ❌
Predicted: 3.007272317968186; Actual: 3.0; ✅
Predicted: 0.8445056238919671; Actual: 1.0; ✅
Predicted: 2.070326540658147; Actual: 2.0; ✅
Predicted: 1.2944570589929132; Actual: 1.0; ✅
Predicted: 2.1285908886444727; Actual: 2.0; ✅
Predicted: 3.082591493141833; Actual: 3.0; ✅
Predicted: 0.8498735979893898; Actual: 1.0; ✅
Predicted: 2.143098374111798; Actual: 2.0; ✅
Predicted: 0.8512737771125793; Actual: 1.0; ✅
Predicted: 2.829734708023294; Actual: 3.0; ✅
Predicted: 3.001674267361395; Actual: 3.0; ✅
Predicted: 0.9378873275889099; Actual: 1.0; ✅
Predicted: 1.8535266922901064; Actual: 2.0; ✅
Predicted: 2.7653122353582495; Actual: 3.0; ✅
Predicted: 3.030320666430908; Actual: 3.0; ✅
Predicted: 1.1530124740122645; Actual: 1.0; ✅
Predicted: 2.1024896387260164; Actual: 2.0; ✅
Predicted: 0.8498735979893898; Actual: 1.0; ✅
Predicted: 2.864637658812927; Actual: 3.0; ✅
Predicted: 2.27887762087447; Actual: 2.0; ✅
Predicted: 0.9395547893644429; Actual: 1.0; ✅
Predicted: 2.9156531452507495; Actual: 3.0; ✅
Predicted: 2.8422849090357114; Actual: 3.0; ✅
Predicted: 0.9583130570557206; Actual: 1.0; ✅
Predicted: 2.0843781141788305; Actual: 2.0; ✅
Predicted: 2.1828046710232685; Actual: 3.0; ❌
Predicted: 2.136013063195636; Actual: 2.0; ✅
Predicted: 2.1017227829656346; Actual: 2.0; ✅
Predicted: 2.2950403388662854; Actual: 2.0; ✅
Predicted: 3.02603974201225; Actual: 3.0; ✅
Predicted: 2.979812634759169; Actual: 3.0; ✅
Predicted: 2.117698283206378; Actual: 2.0; ✅
Predicted: 0.8498735979893898; Actual: 1.0; ✅
Predicted: 1.878822522950159; Actual: 2.0; ✅
Predicted: 2.9153064507345086; Actual: 3.0; ✅
Predicted: 1.0223876157604586; Actual: 1.0; ✅
Predicted: 1.0041322833096733; Actual: 1.0; ✅
Predicted: 1.1382601548795312; Actual: 1.0; ✅
Predicted: 0.8788651807924579; Actual: 1.0; ✅
Predicted: 2.8013555445261313; Actual: 3.0; ✅
Predicted: 2.121617166533567; Actual: 2.0; ✅
Predicted: 2.7661499579212845; Actual: 3.0; ✅
Predicted: 1.0357987019645085; Actual: 1.0; ✅
Predicted: 2.804015029598164; Actual: 3.0; ✅
Predicted: 2.0109214469937418; Actual: 2.0; ✅
Predicted: 2.982029193116455; Actual: 3.0; ✅
Predicted: 1.0130184925253438; Actual: 1.0; ✅
Predicted: 2.776541878336797; Actual: 3.0; ✅
Predicted: 2.9481765665458184; Actual: 3.0; ✅
Predicted: 3.083402571642514; Actual: 3.0; ✅
Predicted: 2.1273895974340817; Actual: 2.0; ✅
Predicted: 1.8418673401209331; Actual: 2.0; ✅
Predicted: 2.0838939130848244; Actual: 2.0; ✅
Predicted: 2.8365080410192616; Actual: 3.0; ✅
Predicted: 2.5021499749004756; Actual: 3.0; ✅
Predicted: 3.063352693382784; Actual: 3.0; ✅
Predicted: 1.9877219445769743; Actual: 2.0; ✅
Predicted: 0.9216028167291099; Actual: 1.0; ✅
Predicted: 1.1595111767796125; Actual: 1.0; ✅
Predicted: 0.9984641710592858; Actual: 1.0; ✅
MSE: 0.03317006785867614
Accuracy: 98.0
Epoch 5 completed
Epoch 6 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 0.9678557535865407; Actual: 1.0; ✅
Predicted: 2.9924753616777346; Actual: 3.0; ✅
Predicted: 2.1484528140135715; Actual: 2.0; ✅
Predicted: 3.017368368232105; Actual: 3.0; ✅
Predicted: 1.113223679514485; Actual: 1.0; ✅
Predicted: 2.110847014547281; Actual: 2.0; ✅
Predicted: 0.9949735490533237; Actual: 1.0; ✅
Predicted: 2.020527007880634; Actual: 2.0; ✅
Predicted: 3.388889788029181; Actual: 3.0; ✅
Predicted: 2.035948415142059; Actual: 2.0; ✅
Predicted: 2.988528009100119; Actual: 3.0; ✅
Predicted: 2.095071788531502; Actual: 2.0; ✅
Predicted: 1.0123487959142725; Actual: 1.0; ✅
Predicted: 1.0228229798573913; Actual: 1.0; ✅
Predicted: 0.9706470000789322; Actual: 1.0; ✅
Predicted: 2.0804060778866544; Actual: 2.0; ✅
Predicted: 0.9458338334696229; Actual: 1.0; ✅
Predicted: 2.9307983141388645; Actual: 3.0; ✅
Predicted: 1.7931356242071321; Actual: 2.0; ✅
Predicted: 0.9270147868146822; Actual: 1.0; ✅
Predicted: 2.2066814603450684; Actual: 2.0; ✅
Predicted: 2.3136985362944875; Actual: 2.0; ✅
Predicted: 0.9445616767571742; Actual: 1.0; ✅
Predicted: 2.174536467425149; Actual: 2.0; ✅
Predicted: 1.9732274769830143; Actual: 2.0; ✅
Predicted: 2.9182393428744677; Actual: 3.0; ✅
Predicted: 1.9378356676532749; Actual: 2.0; ✅
Predicted: 2.837996816281733; Actual: 3.0; ✅
Predicted: 1.0136102544570187; Actual: 1.0; ✅
Predicted: 2.751232022771087; Actual: 3.0; ✅
Predicted: 1.2062919726999568; Actual: 1.0; ✅
Predicted: 1.0517900668395734; Actual: 1.0; ✅
Predicted: 1.077489304834345; Actual: 1.0; ✅
Predicted: 2.870193067820915; Actual: 3.0; ✅
Predicted: 1.1216573509387826; Actual: 1.0; ✅
Predicted: 3.007725245324919; Actual: 3.0; ✅
Predicted: 2.777665125491136; Actual: 3.0; ✅
Predicted: 2.093219995280094; Actual: 2.0; ✅
Predicted: 1.8766019273160799; Actual: 2.0; ✅
Predicted: 2.118567517351196; Actual: 2.0; ✅
Predicted: 0.9040421201389569; Actual: 1.0; ✅
Predicted: 2.187403693233384; Actual: 2.0; ✅
Predicted: 0.9962663170636646; Actual: 1.0; ✅
Predicted: 2.150062350824993; Actual: 2.0; ✅
Predicted: 2.860447145221948; Actual: 2.0; ❌
Predicted: 3.0072723179681833; Actual: 3.0; ✅
Predicted: 0.8445056238919735; Actual: 1.0; ✅
Predicted: 2.070326540658144; Actual: 2.0; ✅
Predicted: 1.2944570589929147; Actual: 1.0; ✅
Predicted: 2.1285908886444678; Actual: 2.0; ✅
Predicted: 3.082591493141826; Actual: 3.0; ✅
Predicted: 0.849873597989395; Actual: 1.0; ✅
Predicted: 2.1430983741117946; Actual: 2.0; ✅
Predicted: 0.8512737771125806; Actual: 1.0; ✅
Predicted: 2.8297347080232926; Actual: 3.0; ✅
Predicted: 3.001674267361387; Actual: 3.0; ✅
Predicted: 0.9378873275889121; Actual: 1.0; ✅
Predicted: 1.853526692290107; Actual: 2.0; ✅
Predicted: 2.7653122353582487; Actual: 3.0; ✅
Predicted: 3.0303206664309075; Actual: 3.0; ✅
Predicted: 1.153012474012265; Actual: 1.0; ✅
Predicted: 2.1024896387260137; Actual: 2.0; ✅
Predicted: 0.849873597989395; Actual: 1.0; ✅
Predicted: 2.8646376588129225; Actual: 3.0; ✅
Predicted: 2.278877620874467; Actual: 2.0; ✅
Predicted: 0.9395547893644451; Actual: 1.0; ✅
Predicted: 2.915653145250744; Actual: 3.0; ✅
Predicted: 2.8422849090357083; Actual: 3.0; ✅
Predicted: 0.9583130570557263; Actual: 1.0; ✅
Predicted: 2.084378114178827; Actual: 2.0; ✅
Predicted: 2.182804671023265; Actual: 3.0; ❌
Predicted: 2.136013063195632; Actual: 2.0; ✅
Predicted: 2.101722782965629; Actual: 2.0; ✅
Predicted: 2.2950403388662823; Actual: 2.0; ✅
Predicted: 3.026039742012245; Actual: 3.0; ✅
Predicted: 2.979812634759164; Actual: 3.0; ✅
Predicted: 2.1176982832063764; Actual: 2.0; ✅
Predicted: 0.849873597989395; Actual: 1.0; ✅
Predicted: 1.8788225229501576; Actual: 2.0; ✅
Predicted: 2.9153064507345086; Actual: 3.0; ✅
Predicted: 1.0223876157604617; Actual: 1.0; ✅
Predicted: 1.0041322833096766; Actual: 1.0; ✅
Predicted: 1.1382601548795344; Actual: 1.0; ✅
Predicted: 0.8788651807924626; Actual: 1.0; ✅
Predicted: 2.8013555445261313; Actual: 3.0; ✅
Predicted: 2.1216171665335612; Actual: 2.0; ✅
Predicted: 2.7661499579212836; Actual: 3.0; ✅
Predicted: 1.0357987019645114; Actual: 1.0; ✅
Predicted: 2.804015029598162; Actual: 3.0; ✅
Predicted: 2.010921446993745; Actual: 2.0; ✅
Predicted: 2.9820291931164467; Actual: 3.0; ✅
Predicted: 1.0130184925253476; Actual: 1.0; ✅
Predicted: 2.776541878336797; Actual: 3.0; ✅
Predicted: 2.948176566545815; Actual: 3.0; ✅
Predicted: 3.08340257164251; Actual: 3.0; ✅
Predicted: 2.1273895974340764; Actual: 2.0; ✅
Predicted: 1.8418673401209305; Actual: 2.0; ✅
Predicted: 2.0838939130848217; Actual: 2.0; ✅
Predicted: 2.8365080410192585; Actual: 3.0; ✅
Predicted: 2.502149974900473; Actual: 3.0; ✅
Predicted: 3.0633526933827793; Actual: 3.0; ✅
Predicted: 1.9877219445769718; Actual: 2.0; ✅
Predicted: 0.9216028167291132; Actual: 1.0; ✅
Predicted: 1.1595111767796136; Actual: 1.0; ✅
Predicted: 0.9984641710592912; Actual: 1.0; ✅
MSE: 0.03317006785867597
Accuracy: 98.0
Epoch 6 completed
Epoch 7 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 0.9678557535865461; Actual: 1.0; ✅
Predicted: 2.9924753616777413; Actual: 3.0; ✅
Predicted: 2.1484528140135466; Actual: 2.0; ✅
Predicted: 3.017368368232109; Actual: 3.0; ✅
Predicted: 1.1132236795144907; Actual: 1.0; ✅
Predicted: 2.110847014547255; Actual: 2.0; ✅
Predicted: 0.9949735490533229; Actual: 1.0; ✅
Predicted: 2.0205270078806046; Actual: 2.0; ✅
Predicted: 3.3888897880292124; Actual: 3.0; ✅
Predicted: 2.0359484151420224; Actual: 2.0; ✅
Predicted: 2.988528009100128; Actual: 3.0; ✅
Predicted: 2.095071788531473; Actual: 2.0; ✅
Predicted: 1.0123487959142798; Actual: 1.0; ✅
Predicted: 1.0228229798573982; Actual: 1.0; ✅
Predicted: 0.9706470000789418; Actual: 1.0; ✅
Predicted: 2.080406077886625; Actual: 2.0; ✅
Predicted: 0.9458338334696279; Actual: 1.0; ✅
Predicted: 2.930798314138874; Actual: 3.0; ✅
Predicted: 1.7931356242070946; Actual: 2.0; ✅
Predicted: 0.9270147868146895; Actual: 1.0; ✅
Predicted: 2.2066814603450453; Actual: 2.0; ✅
Predicted: 2.3136985362944693; Actual: 2.0; ✅
Predicted: 0.9445616767571757; Actual: 1.0; ✅
Predicted: 2.1745364674251197; Actual: 2.0; ✅
Predicted: 1.9732274769829876; Actual: 2.0; ✅
Predicted: 2.918239342874467; Actual: 3.0; ✅
Predicted: 1.9378356676532464; Actual: 2.0; ✅
Predicted: 2.837996816281728; Actual: 3.0; ✅
Predicted: 1.0136102544570273; Actual: 1.0; ✅
Predicted: 2.7512320227710823; Actual: 3.0; ✅
Predicted: 1.2062919726999624; Actual: 1.0; ✅
Predicted: 1.0517900668395772; Actual: 1.0; ✅
Predicted: 1.0774893048343637; Actual: 1.0; ✅
Predicted: 2.8701930678209187; Actual: 3.0; ✅
Predicted: 1.1216573509387817; Actual: 1.0; ✅
Predicted: 3.00772524532493; Actual: 3.0; ✅
Predicted: 2.777665125491129; Actual: 3.0; ✅
Predicted: 2.093219995280081; Actual: 2.0; ✅
Predicted: 1.8766019273160657; Actual: 2.0; ✅
Predicted: 2.11856751735117; Actual: 2.0; ✅
Predicted: 0.9040421201389639; Actual: 1.0; ✅
Predicted: 2.18740369323336; Actual: 2.0; ✅
Predicted: 0.9962663170636672; Actual: 1.0; ✅
Predicted: 2.150062350824968; Actual: 2.0; ✅
Predicted: 2.860447145221944; Actual: 2.0; ❌
Predicted: 3.0072723179681935; Actual: 3.0; ✅
Predicted: 0.8445056238919811; Actual: 1.0; ✅
Predicted: 2.0703265406581215; Actual: 2.0; ✅
Predicted: 1.294457058992917; Actual: 1.0; ✅
Predicted: 2.1285908886444567; Actual: 2.0; ✅
Predicted: 3.0825914931418366; Actual: 3.0; ✅
Predicted: 0.8498735979894001; Actual: 1.0; ✅
Predicted: 2.1430983741117675; Actual: 2.0; ✅
Predicted: 0.8512737771125908; Actual: 1.0; ✅
Predicted: 2.829734708023291; Actual: 3.0; ✅
Predicted: 3.001674267361399; Actual: 3.0; ✅
Predicted: 0.937887327588917; Actual: 1.0; ✅
Predicted: 1.853526692290079; Actual: 2.0; ✅
Predicted: 2.765312235358243; Actual: 3.0; ✅
Predicted: 3.0303206664309155; Actual: 3.0; ✅
Predicted: 1.1530124740122658; Actual: 1.0; ✅
Predicted: 2.102489638725981; Actual: 2.0; ✅
Predicted: 0.8498735979894001; Actual: 1.0; ✅
Predicted: 2.864637658812922; Actual: 3.0; ✅
Predicted: 2.2788776208744586; Actual: 2.0; ✅
Predicted: 0.9395547893644502; Actual: 1.0; ✅
Predicted: 2.915653145250748; Actual: 3.0; ✅
Predicted: 2.842284909035706; Actual: 3.0; ✅
Predicted: 0.9583130570557399; Actual: 1.0; ✅
Predicted: 2.0843781141788003; Actual: 2.0; ✅
Predicted: 2.1828046710232534; Actual: 3.0; ❌
Predicted: 2.1360130631956062; Actual: 2.0; ✅
Predicted: 2.101722782965615; Actual: 2.0; ✅
Predicted: 2.2950403388662624; Actual: 2.0; ✅
Predicted: 3.0260397420122565; Actual: 3.0; ✅
Predicted: 2.9798126347591705; Actual: 3.0; ✅
Predicted: 2.1176982832063493; Actual: 2.0; ✅
Predicted: 0.8498735979894001; Actual: 1.0; ✅
Predicted: 1.8788225229501323; Actual: 2.0; ✅
Predicted: 2.9153064507345103; Actual: 3.0; ✅
Predicted: 1.0223876157604646; Actual: 1.0; ✅
Predicted: 1.0041322833096844; Actual: 1.0; ✅
Predicted: 1.1382601548795417; Actual: 1.0; ✅
Predicted: 0.8788651807924648; Actual: 1.0; ✅
Predicted: 2.8013555445261265; Actual: 3.0; ✅
Predicted: 2.121617166533553; Actual: 2.0; ✅
Predicted: 2.766149957921278; Actual: 3.0; ✅
Predicted: 1.0357987019645214; Actual: 1.0; ✅
Predicted: 2.804015029598156; Actual: 3.0; ✅
Predicted: 2.01092144699372; Actual: 2.0; ✅
Predicted: 2.982029193116457; Actual: 3.0; ✅
Predicted: 1.0130184925253476; Actual: 1.0; ✅
Predicted: 2.776541878336789; Actual: 3.0; ✅
Predicted: 2.948176566545821; Actual: 3.0; ✅
Predicted: 3.0834025716425244; Actual: 3.0; ✅
Predicted: 2.1273895974340684; Actual: 2.0; ✅
Predicted: 1.8418673401209065; Actual: 2.0; ✅
Predicted: 2.083893913084791; Actual: 2.0; ✅
Predicted: 2.8365080410192562; Actual: 3.0; ✅
Predicted: 2.5021499749004725; Actual: 3.0; ✅
Predicted: 3.0633526933827904; Actual: 3.0; ✅
Predicted: 1.9877219445769434; Actual: 2.0; ✅
Predicted: 0.9216028167291108; Actual: 1.0; ✅
Predicted: 1.1595111767796185; Actual: 1.0; ✅
Predicted: 0.9984641710592959; Actual: 1.0; ✅
MSE: 0.03317006785867553
Accuracy: 98.0
Epoch 7 completed
Epoch 8 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 0.9678557535865078; Actual: 1.0; ✅
Predicted: 2.992475361677726; Actual: 3.0; ✅
Predicted: 2.148452814013631; Actual: 2.0; ✅
Predicted: 3.0173683682320935; Actual: 3.0; ✅
Predicted: 1.113223679514458; Actual: 1.0; ✅
Predicted: 2.1108470145473435; Actual: 2.0; ✅
Predicted: 0.9949735490533009; Actual: 1.0; ✅
Predicted: 2.020527007880711; Actual: 2.0; ✅
Predicted: 3.388889788029089; Actual: 3.0; ✅
Predicted: 2.035948415142159; Actual: 2.0; ✅
Predicted: 2.9885280091000905; Actual: 3.0; ✅
Predicted: 2.0950717885315746; Actual: 2.0; ✅
Predicted: 1.0123487959142476; Actual: 1.0; ✅
Predicted: 1.0228229798573567; Actual: 1.0; ✅
Predicted: 0.970647000078898; Actual: 1.0; ✅
Predicted: 2.0804060778867437; Actual: 2.0; ✅
Predicted: 0.9458338334695884; Actual: 1.0; ✅
Predicted: 2.93079831413887; Actual: 3.0; ✅
Predicted: 1.7931356242072345; Actual: 2.0; ✅
Predicted: 0.9270147868146492; Actual: 1.0; ✅
Predicted: 2.2066814603451355; Actual: 2.0; ✅
Predicted: 2.313698536294572; Actual: 2.0; ✅
Predicted: 0.9445616767571613; Actual: 1.0; ✅
Predicted: 2.1745364674251704; Actual: 2.0; ✅
Predicted: 1.9732274769830955; Actual: 2.0; ✅
Predicted: 2.918239342874472; Actual: 3.0; ✅
Predicted: 1.9378356676533617; Actual: 2.0; ✅
Predicted: 2.837996816281762; Actual: 3.0; ✅
Predicted: 1.0136102544569896; Actual: 1.0; ✅
Predicted: 2.751232022771109; Actual: 3.0; ✅
Predicted: 1.2062919726999246; Actual: 1.0; ✅
Predicted: 1.0517900668395521; Actual: 1.0; ✅
Predicted: 1.0774893048342946; Actual: 1.0; ✅
Predicted: 2.8701930678209266; Actual: 3.0; ✅
Predicted: 1.121657350938787; Actual: 1.0; ✅
Predicted: 3.007725245324903; Actual: 3.0; ✅
Predicted: 2.777665125491154; Actual: 3.0; ✅
Predicted: 2.0932199952801405; Actual: 2.0; ✅
Predicted: 1.8766019273161418; Actual: 2.0; ✅
Predicted: 2.118567517351262; Actual: 2.0; ✅
Predicted: 0.9040421201389198; Actual: 1.0; ✅
Predicted: 2.1874036932334477; Actual: 2.0; ✅
Predicted: 0.9962663170636525; Actual: 1.0; ✅
Predicted: 2.150062350825063; Actual: 2.0; ✅
Predicted: 2.860447145221964; Actual: 2.0; ❌
Predicted: 3.0072723179681713; Actual: 3.0; ✅
Predicted: 0.8445056238919493; Actual: 1.0; ✅
Predicted: 2.070326540658194; Actual: 2.0; ✅
Predicted: 1.2944570589928999; Actual: 1.0; ✅
Predicted: 2.12859088864451; Actual: 2.0; ✅
Predicted: 3.082591493141793; Actual: 3.0; ✅
Predicted: 0.8498735979893747; Actual: 1.0; ✅
Predicted: 2.14309837411186; Actual: 2.0; ✅
Predicted: 0.8512737771125305; Actual: 1.0; ✅
Predicted: 2.829734708023306; Actual: 3.0; ✅
Predicted: 3.001674267361359; Actual: 3.0; ✅
Predicted: 0.9378873275888847; Actual: 1.0; ✅
Predicted: 1.853526692290197; Actual: 2.0; ✅
Predicted: 2.7653122353582726; Actual: 3.0; ✅
Predicted: 3.0303206664309026; Actual: 3.0; ✅
Predicted: 1.1530124740122496; Actual: 1.0; ✅
Predicted: 2.102489638726096; Actual: 2.0; ✅
Predicted: 0.8498735979893747; Actual: 1.0; ✅
Predicted: 2.8646376588129283; Actual: 3.0; ✅
Predicted: 2.2788776208745167; Actual: 2.0; ✅
Predicted: 0.9395547893644152; Actual: 1.0; ✅
Predicted: 2.915653145250746; Actual: 3.0; ✅
Predicted: 2.8422849090357243; Actual: 3.0; ✅
Predicted: 0.9583130570556844; Actual: 1.0; ✅
Predicted: 2.08437811417889; Actual: 2.0; ✅
Predicted: 2.1828046710233173; Actual: 3.0; ❌
Predicted: 2.1360130631956906; Actual: 2.0; ✅
Predicted: 2.101722782965679; Actual: 2.0; ✅
Predicted: 2.2950403388663405; Actual: 2.0; ✅
Predicted: 3.0260397420122214; Actual: 3.0; ✅
Predicted: 2.979812634759149; Actual: 3.0; ✅
Predicted: 2.1176982832064435; Actual: 2.0; ✅
Predicted: 0.8498735979893747; Actual: 1.0; ✅
Predicted: 1.8788225229502198; Actual: 2.0; ✅
Predicted: 2.9153064507345317; Actual: 3.0; ✅
Predicted: 1.0223876157604463; Actual: 1.0; ✅
Predicted: 1.0041322833096427; Actual: 1.0; ✅
Predicted: 1.1382601548795102; Actual: 1.0; ✅
Predicted: 0.8788651807924515; Actual: 1.0; ✅
Predicted: 2.801355544526158; Actual: 3.0; ✅
Predicted: 2.1216171665336043; Actual: 2.0; ✅
Predicted: 2.766149957921311; Actual: 3.0; ✅
Predicted: 1.0357987019644719; Actual: 1.0; ✅
Predicted: 2.804015029598179; Actual: 3.0; ✅
Predicted: 2.010921446993855; Actual: 2.0; ✅
Predicted: 2.98202919311642; Actual: 3.0; ✅
Predicted: 1.0130184925253287; Actual: 1.0; ✅
Predicted: 2.776541878336826; Actual: 3.0; ✅
Predicted: 2.9481765665458135; Actual: 3.0; ✅
Predicted: 3.0834025716424756; Actual: 3.0; ✅
Predicted: 2.127389597434118; Actual: 2.0; ✅
Predicted: 1.8418673401209942; Actual: 2.0; ✅
Predicted: 2.083893913084894; Actual: 2.0; ✅
Predicted: 2.8365080410192727; Actual: 3.0; ✅
Predicted: 2.5021499749005156; Actual: 3.0; ✅
Predicted: 3.063352693382757; Actual: 3.0; ✅
Predicted: 1.9877219445770449; Actual: 2.0; ✅
Predicted: 0.9216028167291194; Actual: 1.0; ✅
Predicted: 1.1595111767795885; Actual: 1.0; ✅
Predicted: 0.9984641710592699; Actual: 1.0; ✅
MSE: 0.033170067858676086
Accuracy: 98.0
Epoch 8 completed
Epoch 9 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 0.9678557535865324; Actual: 1.0; ✅
Predicted: 2.992475361677735; Actual: 3.0; ✅
Predicted: 2.1484528140135906; Actual: 2.0; ✅
Predicted: 3.017368368232109; Actual: 3.0; ✅
Predicted: 1.1132236795144774; Actual: 1.0; ✅
Predicted: 2.1108470145472986; Actual: 2.0; ✅
Predicted: 0.9949735490533195; Actual: 1.0; ✅
Predicted: 2.020527007880658; Actual: 2.0; ✅
Predicted: 3.3888897880291626; Actual: 3.0; ✅
Predicted: 2.0359484151420886; Actual: 2.0; ✅
Predicted: 2.9885280091001114; Actual: 3.0; ✅
Predicted: 2.0950717885315244; Actual: 2.0; ✅
Predicted: 1.0123487959142654; Actual: 1.0; ✅
Predicted: 1.0228229798573825; Actual: 1.0; ✅
Predicted: 0.9706470000789218; Actual: 1.0; ✅
Predicted: 2.080406077886681; Actual: 2.0; ✅
Predicted: 0.9458338334696155; Actual: 1.0; ✅
Predicted: 2.9307983141388605; Actual: 3.0; ✅
Predicted: 1.7931356242071628; Actual: 2.0; ✅
Predicted: 0.9270147868146739; Actual: 1.0; ✅
Predicted: 2.2066814603450884; Actual: 2.0; ✅
Predicted: 2.3136985362945146; Actual: 2.0; ✅
Predicted: 0.9445616767571703; Actual: 1.0; ✅
Predicted: 2.174536467425166; Actual: 2.0; ✅
Predicted: 1.9732274769830398; Actual: 2.0; ✅
Predicted: 2.918239342874474; Actual: 3.0; ✅
Predicted: 1.937835667653302; Actual: 2.0; ✅
Predicted: 2.837996816281743; Actual: 3.0; ✅
Predicted: 1.0136102544570098; Actual: 1.0; ✅
Predicted: 2.7512320227710956; Actual: 3.0; ✅
Predicted: 1.2062919726999477; Actual: 1.0; ✅
Predicted: 1.0517900668395672; Actual: 1.0; ✅
Predicted: 1.077489304834329; Actual: 1.0; ✅
Predicted: 2.870193067820916; Actual: 3.0; ✅
Predicted: 1.1216573509387846; Actual: 1.0; ✅
Predicted: 3.007725245324913; Actual: 3.0; ✅
Predicted: 2.777665125491142; Actual: 3.0; ✅
Predicted: 2.0932199952801076; Actual: 2.0; ✅
Predicted: 1.8766019273160974; Actual: 2.0; ✅
Predicted: 2.1185675173512166; Actual: 2.0; ✅
Predicted: 0.9040421201389478; Actual: 1.0; ✅
Predicted: 2.1874036932334024; Actual: 2.0; ✅
Predicted: 0.9962663170636608; Actual: 1.0; ✅
Predicted: 2.150062350825015; Actual: 2.0; ✅
Predicted: 2.8604471452219538; Actual: 2.0; ❌
Predicted: 3.0072723179681793; Actual: 3.0; ✅
Predicted: 0.8445056238919664; Actual: 1.0; ✅
Predicted: 2.0703265406581597; Actual: 2.0; ✅
Predicted: 1.2944570589929099; Actual: 1.0; ✅
Predicted: 2.12859088864448; Actual: 2.0; ✅
Predicted: 3.0825914931418192; Actual: 3.0; ✅
Predicted: 0.8498735979893896; Actual: 1.0; ✅
Predicted: 2.143098374111815; Actual: 2.0; ✅
Predicted: 0.8512737771125687; Actual: 1.0; ✅
Predicted: 2.829734708023296; Actual: 3.0; ✅
Predicted: 3.001674267361379; Actual: 3.0; ✅
Predicted: 0.9378873275889051; Actual: 1.0; ✅
Predicted: 1.8535266922901346; Actual: 2.0; ✅
Predicted: 2.7653122353582558; Actual: 3.0; ✅
Predicted: 3.0303206664309106; Actual: 3.0; ✅
Predicted: 1.1530124740122611; Actual: 1.0; ✅
Predicted: 2.1024896387260394; Actual: 2.0; ✅
Predicted: 0.8498735979893896; Actual: 1.0; ✅
Predicted: 2.864637658812926; Actual: 3.0; ✅
Predicted: 2.278877620874482; Actual: 2.0; ✅
Predicted: 0.9395547893644377; Actual: 1.0; ✅
Predicted: 2.9156531452507464; Actual: 3.0; ✅
Predicted: 2.842284909035716; Actual: 3.0; ✅
Predicted: 0.9583130570557132; Actual: 1.0; ✅
Predicted: 2.0843781141788473; Actual: 2.0; ✅
Predicted: 2.1828046710232805; Actual: 3.0; ❌
Predicted: 2.13601306319565; Actual: 2.0; ✅
Predicted: 2.1017227829656435; Actual: 2.0; ✅
Predicted: 2.2950403388663028; Actual: 2.0; ✅
Predicted: 3.026039742012238; Actual: 3.0; ✅
Predicted: 2.9798126347591607; Actual: 3.0; ✅
Predicted: 2.117698283206397; Actual: 2.0; ✅
Predicted: 0.8498735979893896; Actual: 1.0; ✅
Predicted: 1.8788225229501785; Actual: 2.0; ✅
Predicted: 2.9153064507345174; Actual: 3.0; ✅
Predicted: 1.0223876157604568; Actual: 1.0; ✅
Predicted: 1.0041322833096666; Actual: 1.0; ✅
Predicted: 1.1382601548795261; Actual: 1.0; ✅
Predicted: 0.8788651807924599; Actual: 1.0; ✅
Predicted: 2.8013555445261398; Actual: 3.0; ✅
Predicted: 2.121617166533573; Actual: 2.0; ✅
Predicted: 2.7661499579212916; Actual: 3.0; ✅
Predicted: 1.0357987019645012; Actual: 1.0; ✅
Predicted: 2.80401502959817; Actual: 3.0; ✅
Predicted: 2.010921446993777; Actual: 2.0; ✅
Predicted: 2.9820291931164387; Actual: 3.0; ✅
Predicted: 1.013018492525345; Actual: 1.0; ✅
Predicted: 2.776541878336806; Actual: 3.0; ✅
Predicted: 2.9481765665458166; Actual: 3.0; ✅
Predicted: 3.0834025716425035; Actual: 3.0; ✅
Predicted: 2.127389597434087; Actual: 2.0; ✅
Predicted: 1.8418673401209518; Actual: 2.0; ✅
Predicted: 2.0838939130848444; Actual: 2.0; ✅
Predicted: 2.836508041019265; Actual: 3.0; ✅
Predicted: 2.5021499749004863; Actual: 3.0; ✅
Predicted: 3.063352693382775; Actual: 3.0; ✅
Predicted: 1.9877219445769951; Actual: 2.0; ✅
Predicted: 0.9216028167291165; Actual: 1.0; ✅
Predicted: 1.159511176779607; Actual: 1.0; ✅
Predicted: 0.998464171059285; Actual: 1.0; ✅
MSE: 0.033170067858676086
Accuracy: 98.0
Epoch 9 completed
Epoch 10 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 0.9678557535865343; Actual: 1.0; ✅
Predicted: 2.9924753616777364; Actual: 3.0; ✅
Predicted: 2.148452814013579; Actual: 2.0; ✅
Predicted: 3.0173683682321104; Actual: 3.0; ✅
Predicted: 1.1132236795144792; Actual: 1.0; ✅
Predicted: 2.1108470145472866; Actual: 2.0; ✅
Predicted: 0.9949735490533185; Actual: 1.0; ✅
Predicted: 2.0205270078806397; Actual: 2.0; ✅
Predicted: 3.388889788029175; Actual: 3.0; ✅
Predicted: 2.0359484151420673; Actual: 2.0; ✅
Predicted: 2.988528009100117; Actual: 3.0; ✅
Predicted: 2.0950717885315098; Actual: 2.0; ✅
Predicted: 1.0123487959142663; Actual: 1.0; ✅
Predicted: 1.0228229798573842; Actual: 1.0; ✅
Predicted: 0.9706470000789247; Actual: 1.0; ✅
Predicted: 2.0804060778866633; Actual: 2.0; ✅
Predicted: 0.9458338334696166; Actual: 1.0; ✅
Predicted: 2.930798314138865; Actual: 3.0; ✅
Predicted: 1.7931356242071406; Actual: 2.0; ✅
Predicted: 0.9270147868146748; Actual: 1.0; ✅
Predicted: 2.2066814603450764; Actual: 2.0; ✅
Predicted: 2.3136985362944986; Actual: 2.0; ✅
Predicted: 0.9445616767571683; Actual: 1.0; ✅
Predicted: 2.174536467425157; Actual: 2.0; ✅
Predicted: 1.9732274769830223; Actual: 2.0; ✅
Predicted: 2.918239342874473; Actual: 3.0; ✅
Predicted: 1.937835667653283; Actual: 2.0; ✅
Predicted: 2.8379968162817373; Actual: 3.0; ✅
Predicted: 1.013610254457012; Actual: 1.0; ✅
Predicted: 2.7512320227710916; Actual: 3.0; ✅
Predicted: 1.206291972699951; Actual: 1.0; ✅
Predicted: 1.0517900668395679; Actual: 1.0; ✅
Predicted: 1.0774893048343368; Actual: 1.0; ✅
Predicted: 2.8701930678209178; Actual: 3.0; ✅
Predicted: 1.1216573509387795; Actual: 1.0; ✅
Predicted: 3.0077252453249175; Actual: 3.0; ✅
Predicted: 2.7776651254911404; Actual: 3.0; ✅
Predicted: 2.0932199952801023; Actual: 2.0; ✅
Predicted: 1.8766019273160872; Actual: 2.0; ✅
Predicted: 2.118567517351203; Actual: 2.0; ✅
Predicted: 0.904042120138949; Actual: 1.0; ✅
Predicted: 2.1874036932333913; Actual: 2.0; ✅
Predicted: 0.9962663170636599; Actual: 1.0; ✅
Predicted: 2.1500623508250007; Actual: 2.0; ✅
Predicted: 2.8604471452219524; Actual: 2.0; ❌
Predicted: 3.0072723179681837; Actual: 3.0; ✅
Predicted: 0.844505623891966; Actual: 1.0; ✅
Predicted: 2.070326540658149; Actual: 2.0; ✅
Predicted: 1.2944570589929105; Actual: 1.0; ✅
Predicted: 2.1285908886444758; Actual: 2.0; ✅
Predicted: 3.082591493141825; Actual: 3.0; ✅
Predicted: 0.8498735979893888; Actual: 1.0; ✅
Predicted: 2.1430983741118013; Actual: 2.0; ✅
Predicted: 0.8512737771125726; Actual: 1.0; ✅
Predicted: 2.829734708023296; Actual: 3.0; ✅
Predicted: 3.001674267361386; Actual: 3.0; ✅
Predicted: 0.937887327588906; Actual: 1.0; ✅
Predicted: 1.853526692290116; Actual: 2.0; ✅
Predicted: 2.765312235358253; Actual: 3.0; ✅
Predicted: 3.0303206664309097; Actual: 3.0; ✅
Predicted: 1.1530124740122605; Actual: 1.0; ✅
Predicted: 2.102489638726022; Actual: 2.0; ✅
Predicted: 0.8498735979893888; Actual: 1.0; ✅
Predicted: 2.864637658812926; Actual: 3.0; ✅
Predicted: 2.278877620874476; Actual: 2.0; ✅
Predicted: 0.9395547893644391; Actual: 1.0; ✅
Predicted: 2.9156531452507477; Actual: 3.0; ✅
Predicted: 2.8422849090357127; Actual: 3.0; ✅
Predicted: 0.9583130570557183; Actual: 1.0; ✅
Predicted: 2.084378114178833; Actual: 2.0; ✅
Predicted: 2.1828046710232747; Actual: 3.0; ❌
Predicted: 2.1360130631956387; Actual: 2.0; ✅
Predicted: 2.1017227829656377; Actual: 2.0; ✅
Predicted: 2.295040338866291; Actual: 2.0; ✅
Predicted: 3.0260397420122436; Actual: 3.0; ✅
Predicted: 2.979812634759165; Actual: 3.0; ✅
Predicted: 2.117698283206383; Actual: 2.0; ✅
Predicted: 0.8498735979893888; Actual: 1.0; ✅
Predicted: 1.8788225229501638; Actual: 2.0; ✅
Predicted: 2.9153064507345134; Actual: 3.0; ✅
Predicted: 1.0223876157604561; Actual: 1.0; ✅
Predicted: 1.004132283309669; Actual: 1.0; ✅
Predicted: 1.1382601548795286; Actual: 1.0; ✅
Predicted: 0.8788651807924573; Actual: 1.0; ✅
Predicted: 2.8013555445261367; Actual: 3.0; ✅
Predicted: 2.1216171665335706; Actual: 2.0; ✅
Predicted: 2.7661499579212885; Actual: 3.0; ✅
Predicted: 1.035798701964504; Actual: 1.0; ✅
Predicted: 2.8040150295981667; Actual: 3.0; ✅
Predicted: 2.010921446993756; Actual: 2.0; ✅
Predicted: 2.982029193116446; Actual: 3.0; ✅
Predicted: 1.0130184925253436; Actual: 1.0; ✅
Predicted: 2.7765418783368; Actual: 3.0; ✅
Predicted: 2.948176566545817; Actual: 3.0; ✅
Predicted: 3.0834025716425093; Actual: 3.0; ✅
Predicted: 2.1273895974340853; Actual: 2.0; ✅
Predicted: 1.8418673401209382; Actual: 2.0; ✅
Predicted: 2.083893913084829; Actual: 2.0; ✅
Predicted: 2.836508041019263; Actual: 3.0; ✅
Predicted: 2.5021499749004823; Actual: 3.0; ✅
Predicted: 3.0633526933827797; Actual: 3.0; ✅
Predicted: 1.9877219445769791; Actual: 2.0; ✅
Predicted: 0.9216028167291083; Actual: 1.0; ✅
Predicted: 1.1595111767796087; Actual: 1.0; ✅
Predicted: 0.9984641710592846; Actual: 1.0; ✅
MSE: 0.033170067858675996
Accuracy: 98.0
Epoch 10 completed
Finished training in 1013.0s in 10 epochs

In [51]:
wangMendelFuzzyNeuralNetwork.save_to_file('models/regular/iris/model_98')

#### Testing

In [54]:
# wangMendelFuzzyNeuralNetwork.predict([0.1525, 0.3146, 0.4696, 0.0633])

c_initial = np.linspace(min_class, max_class, membership_functions_count).tolist()
s_initial = np.full(membership_functions_count, 0.2).tolist()

wangMendelFuzzyNeuralNetwork1 = WangMendelFuzzyNeuralNetwork(membership_functions_count,4, c_initial,
                                                             s_initial)
wangMendelFuzzyNeuralNetwork1.initialize_from_file('models/regular/iris/model_98')

input_data = np.array(test_df.iloc[:, :-1].values, dtype=float)
expected_output_data = np.array(test_df.iloc[:, -1].values, dtype=float)

wangMendelFuzzyNeuralNetwork1.predict_and_validate(input_data, expected_output_data, detailed_output=True)

# wangMendelFuzzyNeuralNetwork.predict([0.1525, 0.3146, 0.4696, 0.0633])

Predicted: 2.220716172608676; Actual: 2.0; ✅
Predicted: 0.8999943872723294; Actual: 1.0; ✅
Predicted: 1.031856187195457; Actual: 1.0; ✅
Predicted: 0.9621809914084838; Actual: 1.0; ✅
Predicted: 2.8625255949867716; Actual: 3.0; ✅
Predicted: 2.961181301096235; Actual: 3.0; ✅
Predicted: 2.9635131138104596; Actual: 3.0; ✅
Predicted: 2.147795804247407; Actual: 2.0; ✅
Predicted: 2.748157754206854; Actual: 3.0; ✅
Predicted: 2.0765286011320634; Actual: 2.0; ✅
Predicted: 0.9802776747396426; Actual: 1.0; ✅
Predicted: 2.1910901730211827; Actual: 2.0; ✅
Predicted: 0.9520467754212943; Actual: 1.0; ✅
Predicted: 2.8063748297277846; Actual: 2.0; ❌
Predicted: 2.818046475140141; Actual: 3.0; ✅
Predicted: 2.772685865372632; Actual: 3.0; ✅
Predicted: 1.9994718615085099; Actual: 2.0; ✅
Predicted: 2.776771576238151; Actual: 3.0; ✅
Predicted: 2.801147339967607; Actual: 2.0; ❌
Predicted: 2.8437957021951425; Actual: 3.0; ✅
Predicted: 2.981325002710255; Actual: 2.0; ❌
Predicted: 0.8781436101208855; Actual: 1.0; ✅
Predicted: 2.1558428799163147; Actual: 2.0; ✅
Predicted: 2.353878341008798; Actual: 3.0; ❌
Predicted: 2.096315633038505; Actual: 2.0; ✅
Predicted: 2.992249992502521; Actual: 3.0; ✅
Predicted: 2.204727777873931; Actual: 2.0; ✅
Predicted: 1.1186490228012334; Actual: 1.0; ✅
Predicted: 1.070157663833762; Actual: 1.0; ✅
Predicted: 1.0412516909710332; Actual: 1.0; ✅
Predicted: 3.004848430777117; Actual: 3.0; ✅
Predicted: 1.74996283778134; Actual: 2.0; ✅
Predicted: 2.836508041019263; Actual: 3.0; ✅
Predicted: 2.470538143399817; Actual: 2.0; ✅
Predicted: 1.1116520506367638; Actual: 1.0; ✅
Predicted: 2.7284321597756724; Actual: 2.0; ❌
Predicted: 2.882318895071059; Actual: 3.0; ✅
Predicted: 0.8873991874272368; Actual: 1.0; ✅
Predicted: 0.8815931584783304; Actual: 1.0; ✅
Predicted: 0.994760999251152; Actual: 1.0; ✅
Predicted: 3.037505601247897; Actual: 3.0; ✅
Predicted: 1.137716744769571; Actual: 1.0; ✅
Predicted: 1.01859530618386; Actual: 1.0; ✅
Predicted: 2.995879217459438; Actual: 3.0; ✅
Predicted: 3.0128563432732283; Actual: 3.0; ✅
MSE: 0.09046907070515525
Accuracy: 89.0

[0.09046907070515525, 89.0]