# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [2]:
import math
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm.notebook import trange

In [26]:
def process_input_dataframe(dataframe):
    # 1. Convert data types
    # 2. Remove lines with empty values
    # 3. Shuffle to introduce randomness
    # 4. Normalize values
    dataframe.apply(pd.to_numeric, errors='coerce')

    dataframe.dropna(inplace=True)

    return dataframe.sample(frac=1)


def normalize_array(array, min_value, max_value):
    return (array - min_value) / (max_value - min_value)


def calculate_normalization_boundaries_for_columns(dataframe, target_columns):
    boundaries = {}

    for column_name in target_columns:
        boundaries[column_name] = {
            'min': get_column_min(dataframe, column_name),
            'max': get_column_max(dataframe, column_name)
        }

    return boundaries


def normalize_dataframe(dataframe, normalization_boundaries_dict):
    for column_name, boundaries_dict in normalization_boundaries_dict.items():
        min_value = boundaries_dict['min']
        max_value = boundaries_dict['max']

        column_arr = np.array(dataframe[column_name])

        dataframe[column_name] = normalize_array(column_arr, min_value, max_value)


def get_column_min(dataframe, column_name):
    return dataframe[column_name].min()


def get_column_max(dataframe, column_name):
    return dataframe[column_name].max()

#### Reading and pre-processing data

In [117]:
train_file_path = 'data/biogas/biogas_training_with_type.csv'
test_file_name_path = 'data/biogas/biogas_testing_with_type.csv'


data_columns = ['Input', 'Humidity', 'Temperature', 'Holding Time']
result_columns = ['Output']
all_columns = data_columns + result_columns

train_df = pd.read_csv(train_file_path, header=None, names=all_columns)
test_df = pd.read_csv(test_file_name_path, header=None, names=all_columns)

train_df = process_input_dataframe(train_df)
test_df = process_input_dataframe(test_df)

#### Displaying basic information about the initial data

In [105]:
def display_dataframe_info(dataframe):
    print('****** General Information ******')
    display(dataframe.info())
    display(dataframe.describe())

    print('****** Data Sample ******')
    display(dataframe.head())

In [106]:
print('==== Train Data Info ====')
display_dataframe_info(train_df)
print('========================', end='\n\n')

print('==== Test Data Info ====')
display_dataframe_info(test_df)
print('=========================')

==== Train Data Info ====
****** General Information ******
<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 77 to 29
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Input         200 non-null    int64
 1   Humidity      200 non-null    float64
 2   Temperature   200 non-null    float64
 3   Holding Time  200 non-null    int64
 4   Output        200 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 9.4 KB

None

            Input    Humidity  Temperature  Holding Time      Output
count  200.000000  200.000000   200.000000    200.000000  200.000000
mean   277.285000   76.160253    41.601574     25.200000    2.375000
std    128.118208    9.166107     7.032012      8.674459    0.759777
min     50.000000   60.325130    30.501780     10.000000    1.000000
25%    168.500000   68.740083    35.128928     17.000000    2.000000
50%    291.500000   76.790133    41.081841     26.000000    3.000000
75%    386.000000   84.384748    47.403338     32.000000    3.000000
max    499.000000   89.991530    54.749006     39.000000    3.000000

****** Data Sample ******

     Input   Humidity  Temperature  Holding Time  Output
77     404  62.505022    42.461055            31       2
89     169  79.476309    54.662881            30       2
171    433  80.151021    42.568010            31       2
166     65  73.516324    40.978373            23       1
55     107  86.631125    48.686773            17       1

========================

==== Test Data Info ====
****** General Information ******
<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 495 to 152
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Input         50 non-null     float64
 1   Humidity      50 non-null     float64
 2   Temperature   50 non-null     int64
 3   Holding Time  50 non-null     float64
 4   Output        50 non-null     int64
dtypes: float64(3), int64(2)
memory usage: 2.3 KB

None

           Input   Humidity  Temperature  Holding Time     Output
count  50.000000  50.000000    50.000000     50.000000  50.000000
mean   75.043101  41.833958    24.820000      7.483660   2.500000
std     8.556196   6.727222     9.475403      0.591379   0.646813
min    60.397949  30.013009    10.000000      6.518394   1.000000
25%    68.411143  36.502108    15.250000      6.958562   2.000000
50%    75.907896  41.324816    26.000000      7.590975   3.000000
75%    81.698685  46.702788    32.750000      7.934402   3.000000
max    88.957659  54.292802    39.000000      8.373460   3.000000

****** Data Sample ******

         Input   Humidity  Temperature  Holding Time  Output
495  71.846446  33.052199           11      8.274173       3
369  87.789026  37.619531           32      6.518394       3
463  71.854507  44.081889           12      7.182133       3
363  85.336015  44.971637           26      7.610402       1
493  77.113319  43.496027           33      7.015883       2

=========================

#### Determining normalization boundaries and performing normalization fot both the training and testing sets

In [118]:
normalization_boundaries_dict = calculate_normalization_boundaries_for_columns(train_df, [])

print('====== Data Normalization ======', end='\n')

print('Based on the input training data, each column will be normalized using the following boundaries:', end='\n')

for column_name, boundaries_dict in normalization_boundaries_dict.items():
    min_value = boundaries_dict['min']
    max_value = boundaries_dict['max']

    print(f'{column_name}: [{min_value}; {max_value}]', end='\n')

normalize_dataframe(train_df, normalization_boundaries_dict)
normalize_dataframe(test_df, normalization_boundaries_dict)

print('\nData has been normalized')
print('================================', end='\n')

====== Data Normalization ======
Based on the input training data, each column will be normalized using the following boundaries:

Data has been normalized
================================

In [119]:
print('==== Train Data Normalized Info ====')
display_dataframe_info(train_df)
print('========================', end='\n\n')

print('==== Test Data Normalized Info ====')
display_dataframe_info(test_df)
print('=========================')

==== Train Data Normalized Info ====
****** General Information ******
<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 186 to 70
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Input         200 non-null    int64
 1   Humidity      200 non-null    float64
 2   Temperature   200 non-null    float64
 3   Holding Time  200 non-null    int64
 4   Output        200 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 9.4 KB

None

            Input    Humidity  Temperature  Holding Time      Output
count  200.000000  200.000000   200.000000    200.000000  200.000000
mean   277.285000   76.160253    41.601574     25.200000    2.375000
std    128.118208    9.166107     7.032012      8.674459    0.759777
min     50.000000   60.325130    30.501780     10.000000    1.000000
25%    168.500000   68.740083    35.128928     17.000000    2.000000
50%    291.500000   76.790133    41.081841     26.000000    3.000000
75%    386.000000   84.384748    47.403338     32.000000    3.000000
max    499.000000   89.991530    54.749006     39.000000    3.000000

****** Data Sample ******

     Input   Humidity  Temperature  Holding Time  Output
186    372  82.654118    52.347315            19       2
181    494  76.828139    38.372640            38       2
68     157  62.545131    30.501780            20       3
123    398  70.600567    45.265501            10       1
39     192  88.501859    49.985260            39       2

========================

==== Test Data Normalized Info ====
****** General Information ******
<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 343 to 393
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Input         50 non-null     float64
 1   Humidity      50 non-null     float64
 2   Temperature   50 non-null     int64
 3   Holding Time  50 non-null     float64
 4   Output        50 non-null     int64
dtypes: float64(3), int64(2)
memory usage: 2.3 KB

None

           Input   Humidity  Temperature  Holding Time     Output
count  50.000000  50.000000    50.000000     50.000000  50.000000
mean   75.043101  41.833958    24.820000      7.483660   2.500000
std     8.556196   6.727222     9.475403      0.591379   0.646813
min    60.397949  30.013009    10.000000      6.518394   1.000000
25%    68.411143  36.502108    15.250000      6.958562   2.000000
50%    75.907896  41.324816    26.000000      7.590975   3.000000
75%    81.698685  46.702788    32.750000      7.934402   3.000000
max    88.957659  54.292802    39.000000      8.373460   3.000000

****** Data Sample ******

         Input   Humidity  Temperature  Holding Time  Output
343  87.799766  47.387902           26      6.726947       3
98   78.211027  32.637356           32      8.300836       3
241  69.796223  45.110434           26      8.254679       3
219  68.888205  35.461011           10      7.178060       1
71   82.419603  47.369623           11      7.559301       3

=========================

#### Declaring Utils for Layers

In [90]:
def kronecker_delta(i, j):
    return 1 if i == j else 0

#### Declaring Layers

Fuzzifying Layer

In [91]:
class FuzzifyingLayer:
    def __init__(self, membership_functions_count, input_vector_length, c_initial, s_initial):
        self.membership_functions_count = membership_functions_count
        self.input_vector_length = input_vector_length
        self.c = []
        self.s = []

        for i in range(self.input_vector_length):
            self.c.append(c_initial)
            self.s.append(s_initial)

    def fuzzify(self, input_vector):
        memberships_matrix = []

        for i in range(self.input_vector_length):
            x = input_vector[i]
            x_memberships = []

            for j in range(self.membership_functions_count):
                membership = self.calculate_membership_for_x(x, i, j)
                x_memberships.append(membership)

            memberships_matrix.append(x_memberships)

        # vector_memberships = [
        #     x1: [ mu1(x1), mu2(x1), ..., mu(x1)]
        #     x1: [ mu1(x1), mu2(x1), ..., mu(x1)]
        #     ...
        #     x: [ mu1(x), mu2(x), ..., mu(x)]
        # ]

        # print(f"memberships_matrix: {memberships_matrix}", end='\n\n')
        # print(f"s: {self.c}", end='\n\n')
        # print(f"c: {self.s}", end='\n\n')

        return memberships_matrix

    def calculate_membership_for_x(self, x, i, j):
        c, s = self.c[i][j], self.s[i][j]

        membership = 1 / (1 + (((x - c) / s) ** 2))

        return membership

    def train(self, v_c, v_s, predicted_value, actual_values, weights, input_vector):
        c_copy = np.empty_like(self.c)
        s_copy = np.empty_like(self.s)

        for r in range(len(self.c)):
            for l in range(len(self.c[r])):
                c_copy[r][l] = self.calculate_new_c(r, l, weights, v_c, predicted_value, actual_values, input_vector)
                s_copy[r][l] = self.calculate_new_s(r, l, weights, v_s, predicted_value, actual_values, input_vector)

        self.c = c_copy
        self.s = s_copy

    def calculate_new_c(self, r, j, weights, v_c, predicted_value, actual_value, input_vector):
        memberships_matrix = self.fuzzify(input_vector)

        return self.c[r][j] - v_c * self.calculate_de_to_dc(r, j, weights, predicted_value, actual_value, input_vector,
                                                            memberships_matrix)

    def calculate_new_s(self, r, j, weights, v_s, predicted_value, actual_value, input_vector):
        memberships_matrix = self.fuzzify(input_vector)

        return self.s[r][j] - v_s * self.calculate_de_to_ds(r, j, weights, predicted_value, actual_value,
                                                            input_vector, memberships_matrix)

    def calculate_de_to_dc(self, r, j, weights, predicted_value, actual_value, input_vector, memberships_matrix):
        error_derivative = np.sum(predicted_value - actual_value)

        weighted_outputs = 0

        for l in range(len(weights)):
            weighted_outputs += weights[l] * self.calculate_dy_to_dc(l, r, j, input_vector, memberships_matrix)

        return error_derivative * weighted_outputs

    def calculate_de_to_ds(self, r, j, weights, predicted_value, actual_value, input_vector, memberships_matrix):
        error_derivative = np.sum(predicted_value - actual_value)

        weighted_outputs = 0

        for l in range(len(weights)):
            weighted_outputs += weights[l] * self.calculate_dy_to_ds(l, r, j, input_vector, memberships_matrix)

        return error_derivative * weighted_outputs

    def calculate_dy_to_dc(self, l, r, j, input_vector, memberships_matrix):
        m = self.calculate_m(memberships_matrix)
        t = self.calculate_t(l, memberships_matrix)

        first_multiplier = (kronecker_delta(l, r) * m - t) / (m ** 2)
        second_multiplier = self.calculate_t_excluding(r, j, memberships_matrix)
        third_multiplier = self.calculate_dm_to_dc(r, j, input_vector)

        dy_to_dc = first_multiplier * second_multiplier * third_multiplier

        return dy_to_dc

    def calculate_dy_to_ds(self, l, r, j, input_vector, memberships_matrix):
        m = self.calculate_m(memberships_matrix)
        t = self.calculate_t(l, memberships_matrix)

        first_multiplier = (kronecker_delta(l, r) * m - t) / (m ** 2)
        second_multiplier = self.calculate_t_excluding(r, j, memberships_matrix)
        third_multiplier = self.calculate_dm_to_ds(r, j, input_vector)

        dy_to_dc = first_multiplier * second_multiplier * third_multiplier

        return dy_to_dc

    def calculate_dm_to_dc(self, r, j, input_vector):
        x = input_vector[r]
        c = self.c[r][j]
        s = self.s[r][j]

        return math.exp(-(((x - c) ** 2) / (2 * (s ** 2)))) * ((x - c) / (s ** 2))

    def calculate_dm_to_ds(self, r, j, input_vector):
        x = input_vector[r]
        c = self.c[r][j]
        s = self.s[r][j]

        return math.exp(-(((x - c) ** 2) / (2 * (s ** 2)))) * (((x - c) ** 2) / (s ** 3))

    def calculate_m(self, memberships_matrix):
        result = 0

        for p in range(self.membership_functions_count):
            result += self.calculate_t(p, memberships_matrix)

        return result

    def calculate_t(self, l, memberships_matrix):
        result = 1

        for i in range(self.input_vector_length):
            result *= memberships_matrix[i][l]

        return result

    def calculate_t_excluding(self, r, j, memberships_matrix):
        result = 1

        for i in range(self.input_vector_length):
            if i != j:
                result *= memberships_matrix[i][r]

        return result

Aggregation Layer

In [92]:
class AggregatingLayer:
    def __init__(self, membership_functions_count, input_vector_length):
        self.membership_functions_count = membership_functions_count
        self.input_vector_length = input_vector_length

    def aggregate(self, memberships_matrix):
        aggregated_memberships = []

        for i in range(self.membership_functions_count):
            product = 1

            for j in range(self.input_vector_length):
                product *= memberships_matrix[j][i]

            aggregated_memberships.append(product)

        return aggregated_memberships

Linear Layer

In [93]:
class LinearLayer:
    def __init__(self, membership_functions_count, input_vector_length):
        self.membership_functions_count = membership_functions_count
        self.input_vector_length = input_vector_length
        self.weights = np.random.uniform(low=-1, high=1, size=self.membership_functions_count).tolist()

    def process(self, aggregated_memberships):
        weighted_aggregated_memberships_sum = 0
        aggregated_memberships_sum = 0

        for i in range(self.membership_functions_count):
            weighted_aggregated_memberships_sum += self.weights[i] * aggregated_memberships[i]
            aggregated_memberships_sum += aggregated_memberships[i]

        return {
            'f1': weighted_aggregated_memberships_sum,
            'f2': aggregated_memberships_sum,
        }

    def train(self, input_data, expected_output_data, plot_weights=False):
        p_vs = []

        for input_vector in input_data:
            p_v = self.calculate_p_vs(input_vector)
            p_vs.append(p_v)

        pseudo_inverse = np.linalg.pinv(p_vs)
        new_weights = np.matmul(pseudo_inverse, expected_output_data)

        if plot_weights:
            plt.clf()
            plt.plot(self.weights, color='r', label='Previous Weights')
            plt.plot(new_weights, color='g', label='New Weights')
            plt.legend()
            plt.show()

        self.weights = new_weights

    def calculate_p_vs(self, memberships_matrix):
        values = []
        p_vs = []

        for i in range(self.membership_functions_count):
            value = 1

            for j in range(self.input_vector_length):
                value *= memberships_matrix[j][i]

            values.append(value)

        for i in range(len(values)):
            numerator = values[i]
            denominator = 0

            for j in range(len(values)):
                denominator += values[j]

            p_vs.append(numerator / denominator)

        return p_vs

Activation Layer

In [94]:
class ActivationLayer:
    def diffuzify(self, fs_dict):
        # return np.round(fs_dict['f1'] / fs_dict['f2'], 0)
        return fs_dict['f1'] / fs_dict['f2']

### WangMendel Fuzzy Neural Network

In [112]:
class WangMendelFuzzyNeuralNetwork:
    def __init__(self, membership_functions_count, input_vector_length, c_initial, s_initial):
        self.fuzzifying_layer = FuzzifyingLayer(membership_functions_count, input_vector_length, c_initial, s_initial)
        self.aggregating_layer = AggregatingLayer(membership_functions_count, input_vector_length)
        self.linear_layer = LinearLayer(membership_functions_count, input_vector_length)
        self.activation_layer = ActivationLayer()

    def predict_exact(self, input_vector):
        return np.round(self.predict(input_vector), 0)

    def predict(self, input_vector):
        fuzzifying_layer_output = self.fuzzifying_layer.fuzzify(input_vector)
        aggregating_layer_output = self.aggregating_layer.aggregate(fuzzifying_layer_output)
        linear_layer_output = self.linear_layer.process(aggregating_layer_output)
        activation_layer_output = self.activation_layer.diffuzify(linear_layer_output)

        return activation_layer_output

    def predict_for_matrix(self, input_data):
        predictions = []

        for input_vector in input_data:
            prediction = self.predict(input_vector)
            predictions.append(prediction)

        return predictions

    def predict_and_validate(self, input_data, expected_output_data, detailed_output=False):
        predicted_output_data = self.predict_for_matrix(input_data)

        total_predictions = len(predicted_output_data)
        correct_predictions = 0

        for i in range(total_predictions):
            predicted_value = predicted_output_data[i]
            predicted_value_rounded = np.round(predicted_value, 0)
            expected_value = expected_output_data[i]

            is_predicted_equal_to_expected = predicted_value_rounded == expected_value

            if is_predicted_equal_to_expected:
                correct_predictions += 1

            if detailed_output:
                print(
                    f'Predicted: {predicted_value}; Actual: {expected_value}; {'✅' if is_predicted_equal_to_expected else '❌'}')

        mse = (np.square(predicted_output_data - expected_output_data)).mean()
        accuracy = np.round(correct_predictions / total_predictions * 100, 0)

        print(f'MSE: {mse}')
        print(f'Accuracy: {accuracy}')

        return [mse, accuracy]

    def train(self, epochs, training_data_df, c_nu=0.5, s_nu=0.5, max_epochs_with_no_mse_change=2):
        print(f'Started training for {epochs} epochs', end='\n')

        input_data = np.array(training_data_df.iloc[:, :-1].values, dtype=float)
        expected_output_data = np.array(training_data_df.iloc[:, -1].values, dtype=float)

        start_time = time.time()

        current_mse = 1
        epochs_without_mse_change = 0
        completed_epochs = 0

        training_vectors_count = len(input_data)

        for i in trange(epochs, desc='Epochs progress'):
            print(f'Epoch {i + 1} started', end='\n')

            # print(f"====\nCs: {self.fuzzifying_layer.c}\n")
            # print(f"Ss: {self.fuzzifying_layer.s}\n\n====\n")

            self.train_linear_layer(input_data, expected_output_data)

            for j in trange(100, desc='Data passes per epoch progress', leave=False):
                predicted_data = self.predict_for_matrix(input_data)

                for k in range(training_vectors_count):
                    self.fuzzifying_layer.train(
                        c_nu,
                        s_nu,
                        predicted_data,
                        expected_output_data,
                        self.linear_layer.weights,
                        input_data[k]
                    )

            [mse, accuracy] = self.predict_and_validate(input_data, expected_output_data, detailed_output=True)

            previous_mse = current_mse
            current_mse = mse
            mse_change = previous_mse - current_mse

            if mse_change == 0:
                epochs_without_mse_change += 1

            if epochs_without_mse_change == max_epochs_with_no_mse_change:
                print(f'MSE hasn\'t changed during last {max_epochs_with_no_mse_change} epochs; Training ended',
                      end='\n')
                break

            completed_epochs += 1
            print(f'Epoch {i + 1} completed', end='\n')

        end_time = time.time()
        elapsed_time = np.round(end_time - start_time, 0)

        print(f'Finished training in {elapsed_time}s in {completed_epochs} epochs', end='\n')

    def train_linear_layer(self, input_data, expected_output_data):
        input_data_fuzzified = []

        for input_vector in input_data:
            fuzzified_vector = self.fuzzifying_layer.fuzzify(input_vector)
            input_data_fuzzified.append(fuzzified_vector)

        self.linear_layer.train(input_data_fuzzified, expected_output_data)

    def save_to_file(self, file_name):
        c = self.fuzzifying_layer.c
        s = self.fuzzifying_layer.s
        weights = self.linear_layer.weights

        np.savez(f"{file_name}.npz", c=c, s=s, weights=weights)

    def initialize_from_file(self, file_name):
        file = np.load(f"{file_name}.npz")

        self.fuzzifying_layer.c = file['c']
        self.fuzzifying_layer.s = file['s']
        self.linear_layer.weights = file['weights']

#### Training

In [121]:
min_class = get_column_min(train_df, result_columns[0])
max_class = get_column_max(train_df, result_columns[0])

membership_functions_count = 12

# TODO: add utility method to extract x_vector and y
input_vector_length = len(np.array(train_df.iloc[:, :-1].values, dtype=float)[0])

c_initial = np.linspace(0, 400, membership_functions_count).tolist()
s_initial = np.full(membership_functions_count, 0.1).tolist()

wangMendelFuzzyNeuralNetwork = WangMendelFuzzyNeuralNetwork(membership_functions_count, input_vector_length, c_initial,
                                                            s_initial)

wangMendelFuzzyNeuralNetwork.train(10, train_df, 0.5, 0.5, 2)

Started training for 10 epochs

Epochs progress:   0%|          | 0/10 [00:00<?, ?it/s]

Epoch 1 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 2.351781103950021; Actual: 2.0; ✅
Predicted: 2.3516564327731606; Actual: 2.0; ✅
Predicted: 2.351646829750353; Actual: 3.0; ❌
Predicted: 2.351653434787033; Actual: 1.0; ❌
Predicted: 2.352320900428375; Actual: 2.0; ✅
Predicted: 2.3524750409952007; Actual: 3.0; ❌
Predicted: 2.3516487212407826; Actual: 3.0; ❌
Predicted: 2.351866759584631; Actual: 3.0; ❌
Predicted: 2.3518148543283144; Actual: 1.0; ❌
Predicted: 2.351652736233603; Actual: 2.0; ✅
Predicted: 2.35164996907674; Actual: 3.0; ❌
Predicted: 2.351646150138441; Actual: 3.0; ❌
Predicted: 2.351812498057523; Actual: 3.0; ❌
Predicted: 2.3516462901639295; Actual: 3.0; ❌
Predicted: 2.351658244743562; Actual: 3.0; ❌
Predicted: 2.3516498117167446; Actual: 3.0; ❌
Predicted: 2.3522775529663407; Actual: 3.0; ❌
Predicted: 2.351645825874325; Actual: 1.0; ❌
Predicted: 2.3520154587831557; Actual: 3.0; ❌
Predicted: 2.3517141876296472; Actual: 3.0; ❌
Predicted: 2.351682559441392; Actual: 3.0; ❌
Predicted: 2.351645443957642; Actual: 1.0; ❌
Predicted: 2.35201635437855; Actual: 3.0; ❌
Predicted: 2.3517004297208786; Actual: 3.0; ❌
Predicted: 2.3516455152846243; Actual: 2.0; ✅
Predicted: 2.351720173989104; Actual: 3.0; ❌
Predicted: 2.3517263336994723; Actual: 3.0; ❌
Predicted: 2.3516481543258254; Actual: 3.0; ❌
Predicted: 2.351646747773789; Actual: 3.0; ❌
Predicted: 2.351650838912381; Actual: 3.0; ❌
Predicted: 2.3517299136172247; Actual: 3.0; ❌
Predicted: 2.351652908264664; Actual: 3.0; ❌
Predicted: 2.35181236593885; Actual: 2.0; ✅
Predicted: 2.3516996883560317; Actual: 3.0; ❌
Predicted: 2.351958200554432; Actual: 1.0; ❌
Predicted: 2.35169434624924; Actual: 1.0; ❌
Predicted: 2.3516463963658327; Actual: 1.0; ❌
Predicted: 2.351652115506321; Actual: 3.0; ❌
Predicted: 2.3517006247031818; Actual: 3.0; ❌
Predicted: 2.3516576614188156; Actual: 1.0; ❌
Predicted: 2.351648496808767; Actual: 2.0; ✅
Predicted: 2.351958743326681; Actual: 1.0; ❌
Predicted: 2.3516485595573733; Actual: 1.0; ❌
Predicted: 2.351688270655386; Actual: 2.0; ✅
Predicted: 2.3516458650654295; Actual: 2.0; ✅
Predicted: 2.3516947519267393; Actual: 2.0; ✅
Predicted: 2.352425610516688; Actual: 3.0; ❌
Predicted: 2.351887796570312; Actual: 3.0; ❌
Predicted: 2.351645334426107; Actual: 3.0; ❌
Predicted: 2.3516531648732903; Actual: 3.0; ❌
Predicted: 2.351682385131223; Actual: 3.0; ❌
Predicted: 2.3516661112458586; Actual: 1.0; ❌
Predicted: 2.351651400987333; Actual: 3.0; ❌
Predicted: 2.351656086989092; Actual: 1.0; ❌
Predicted: 2.351661881601379; Actual: 2.0; ✅
Predicted: 2.35165964913277; Actual: 3.0; ❌
Predicted: 2.3516470896545014; Actual: 3.0; ❌
Predicted: 2.3516979278539147; Actual: 3.0; ❌
Predicted: 2.351646394699647; Actual: 3.0; ❌
Predicted: 2.351645729549896; Actual: 3.0; ❌
Predicted: 2.3516475429465142; Actual: 3.0; ❌
Predicted: 2.351667140231929; Actual: 3.0; ❌
Predicted: 2.351928319769177; Actual: 3.0; ❌
Predicted: 2.3516464222380886; Actual: 3.0; ❌
Predicted: 2.3516519779906844; Actual: 2.0; ✅
Predicted: 2.3516524382264077; Actual: 3.0; ❌
Predicted: 2.3521611662568196; Actual: 2.0; ✅
Predicted: 2.3516510805611888; Actual: 2.0; ✅
Predicted: 2.3516504732703147; Actual: 1.0; ❌
Predicted: 2.351652249636301; Actual: 1.0; ❌
Predicted: 2.3523954155427416; Actual: 2.0; ✅
Predicted: 2.351750364410784; Actual: 3.0; ❌
Predicted: 2.351660609246984; Actual: 2.0; ✅
Predicted: 2.35200999080612; Actual: 2.0; ✅
Predicted: 2.351645150430661; Actual: 1.0; ❌
Predicted: 2.3518189838531662; Actual: 2.0; ✅
Predicted: 2.351645494747568; Actual: 1.0; ❌
Predicted: 2.351811129138675; Actual: 3.0; ❌
Predicted: 2.3516410428786596; Actual: 3.0; ❌
Predicted: 2.351646216072329; Actual: 3.0; ❌
Predicted: 2.351659349346613; Actual: 3.0; ❌
Predicted: 2.3516460478310806; Actual: 2.0; ✅
Predicted: 2.351666368482644; Actual: 3.0; ❌
Predicted: 2.3516626800298317; Actual: 2.0; ✅
Predicted: 2.3516717583787115; Actual: 3.0; ❌
Predicted: 2.3518899246544778; Actual: 3.0; ❌
Predicted: 2.3516456268526307; Actual: 1.0; ❌
Predicted: 2.351768823820464; Actual: 2.0; ✅
Predicted: 2.3521920212845986; Actual: 1.0; ❌
Predicted: 2.351645895840981; Actual: 2.0; ✅
Predicted: 2.351645345693032; Actual: 2.0; ✅
Predicted: 2.3516768038771327; Actual: 2.0; ✅
Predicted: 2.3516495976493186; Actual: 3.0; ❌
Predicted: 2.351649565668654; Actual: 3.0; ❌
Predicted: 2.3516514768501087; Actual: 3.0; ❌
Predicted: 2.3516509953976867; Actual: 2.0; ✅
Predicted: 2.3518303782801664; Actual: 3.0; ❌
Predicted: 2.351649284360398; Actual: 2.0; ✅
Predicted: 2.351920054631806; Actual: 3.0; ❌
Predicted: 2.3516448075577987; Actual: 3.0; ❌
Predicted: 2.352739453935196; Actual: 3.0; ❌
Predicted: 2.3519671935119826; Actual: 2.0; ✅
Predicted: 2.3516453359559226; Actual: 3.0; ❌
Predicted: 2.351645545489096; Actual: 2.0; ✅
Predicted: 2.351750805555219; Actual: 2.0; ✅
Predicted: 2.351650605725074; Actual: 3.0; ❌
Predicted: 2.3518207671504894; Actual: 3.0; ❌
Predicted: 2.351648969173856; Actual: 3.0; ❌
Predicted: 2.3516659339909936; Actual: 3.0; ❌
Predicted: 2.3516521217803557; Actual: 3.0; ❌
Predicted: 2.3516736564087304; Actual: 3.0; ❌
Predicted: 2.351692032045556; Actual: 2.0; ✅
Predicted: 2.3516453569462805; Actual: 3.0; ❌
Predicted: 2.351628728005584; Actual: 1.0; ❌
Predicted: 2.35167503212902; Actual: 3.0; ❌
Predicted: 2.3517645669214757; Actual: 2.0; ✅
Predicted: 2.3516501958005835; Actual: 2.0; ✅
Predicted: 2.351646931407773; Actual: 3.0; ❌
Predicted: 2.35166479329117; Actual: 2.0; ✅
Predicted: 2.351653480769664; Actual: 1.0; ❌
Predicted: 2.35164971842042; Actual: 3.0; ❌
Predicted: 2.3516918288660045; Actual: 3.0; ❌
Predicted: 2.35183163210052; Actual: 2.0; ✅
Predicted: 2.351668746872413; Actual: 2.0; ✅
Predicted: 2.3516483335964566; Actual: 3.0; ❌
Predicted: 2.3519569364752146; Actual: 3.0; ❌
Predicted: 2.388858228324742; Actual: 3.0; ❌
Predicted: 2.3516481503285274; Actual: 1.0; ❌
Predicted: 2.351645238460244; Actual: 2.0; ✅
Predicted: 2.351655552588048; Actual: 2.0; ✅
Predicted: 2.351789165925699; Actual: 1.0; ❌
Predicted: 2.3516874105436565; Actual: 3.0; ❌
Predicted: 2.3516802483461827; Actual: 1.0; ❌
Predicted: 2.351648464627164; Actual: 2.0; ✅
Predicted: 2.3518552342099803; Actual: 3.0; ❌
Predicted: 2.35165011355545; Actual: 3.0; ❌
Predicted: 2.3517310891392036; Actual: 3.0; ❌
Predicted: 2.35164919011912; Actual: 2.0; ✅
Predicted: 2.351700481692366; Actual: 1.0; ❌
Predicted: 2.3516466026465275; Actual: 3.0; ❌
Predicted: 2.3518133312277465; Actual: 3.0; ❌
Predicted: 2.351646216203219; Actual: 3.0; ❌
Predicted: 2.351653285738131; Actual: 2.0; ✅
Predicted: 2.3522083517162953; Actual: 2.0; ✅
Predicted: 2.3516474513477093; Actual: 3.0; ❌
Predicted: 2.3516618577977586; Actual: 1.0; ❌
Predicted: 2.3533292521335465; Actual: 2.0; ✅
Predicted: 2.3516630268404572; Actual: 3.0; ❌
Predicted: 2.3519881939264944; Actual: 3.0; ❌
Predicted: 2.351649095836932; Actual: 3.0; ❌
Predicted: 2.351872065980958; Actual: 3.0; ❌
Predicted: 2.3516452722289913; Actual: 3.0; ❌
Predicted: 2.351738565346517; Actual: 1.0; ❌
Predicted: 2.3516573767240825; Actual: 2.0; ✅
Predicted: 2.3516453421388017; Actual: 1.0; ❌
Predicted: 2.35164784151494; Actual: 2.0; ✅
Predicted: 2.3516464518561655; Actual: 3.0; ❌
Predicted: 2.3518516511034497; Actual: 3.0; ❌
Predicted: 2.351826137992779; Actual: 3.0; ❌
Predicted: 2.351694269407158; Actual: 1.0; ❌
Predicted: 2.351888731100156; Actual: 3.0; ❌
Predicted: 2.351659661159056; Actual: 2.0; ✅
Predicted: 2.352189370099904; Actual: 3.0; ❌
Predicted: 2.3516486988593996; Actual: 3.0; ❌
Predicted: 2.3516467548633737; Actual: 1.0; ❌
Predicted: 2.35166136729798; Actual: 2.0; ✅
Predicted: 2.3516492181065702; Actual: 3.0; ❌
Predicted: 2.3519188524987813; Actual: 3.0; ❌
Predicted: 2.3516474705391937; Actual: 3.0; ❌
Predicted: 2.351645728519575; Actual: 2.0; ✅
Predicted: 2.3516458149119064; Actual: 2.0; ✅
Predicted: 2.355064170259408; Actual: 2.0; ✅
Predicted: 2.3516649795566202; Actual: 3.0; ❌
Predicted: 2.3518886494887443; Actual: 3.0; ❌
Predicted: 2.3516975283655106; Actual: 1.0; ❌
Predicted: 2.3516564276172356; Actual: 3.0; ❌
Predicted: 2.3516457671747766; Actual: 2.0; ✅
Predicted: 2.351645766883211; Actual: 3.0; ❌
Predicted: 2.351649201291394; Actual: 2.0; ✅
Predicted: 2.351647385135905; Actual: 1.0; ❌
Predicted: 2.3516516735128326; Actual: 2.0; ✅
Predicted: 2.3516482890518056; Actual: 3.0; ❌
Predicted: 2.3516458509629503; Actual: 1.0; ❌
Predicted: 2.3516618396541853; Actual: 3.0; ❌
Predicted: 2.3516593534764705; Actual: 3.0; ❌
Predicted: 2.352545480217844; Actual: 3.0; ❌
Predicted: 2.351645577373231; Actual: 3.0; ❌
Predicted: 2.351727415582653; Actual: 3.0; ❌
Predicted: 2.3516924128656584; Actual: 2.0; ✅
Predicted: 2.3516459178577107; Actual: 2.0; ✅
Predicted: 2.3515684483500316; Actual: 3.0; ❌
Predicted: 2.3516469811914913; Actual: 3.0; ❌
Predicted: 2.3517255008087528; Actual: 3.0; ❌
Predicted: 2.3516449105813004; Actual: 1.0; ❌
Predicted: 2.351643385676551; Actual: 2.0; ✅
Predicted: 2.3516465786813034; Actual: 3.0; ❌
Predicted: 2.351648356075579; Actual: 2.0; ✅
Predicted: 2.3516737621592205; Actual: 3.0; ❌
Predicted: 2.3516451975947197; Actual: 2.0; ✅
Predicted: 2.3516451627901964; Actual: 1.0; ❌
MSE: 0.5746730589129131
Accuracy: 28.0
Epoch 1 completed
Epoch 2 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 2.4407438676443776; Actual: 2.0; ✅
Predicted: 2.3772091435106337; Actual: 2.0; ✅
Predicted: 2.3775932921179073; Actual: 3.0; ❌
Predicted: 2.3242343192758455; Actual: 1.0; ❌
Predicted: 2.272146862316288; Actual: 2.0; ✅
Predicted: 2.3820488346146345; Actual: 3.0; ❌
Predicted: 2.3768473322453536; Actual: 3.0; ❌
Predicted: 2.3691473094074214; Actual: 3.0; ❌
Predicted: 2.378245356254388; Actual: 1.0; ❌
Predicted: 2.3755970319653414; Actual: 2.0; ✅
Predicted: 2.3770210153386104; Actual: 3.0; ❌
Predicted: 2.377705412121098; Actual: 3.0; ❌
Predicted: 2.410588479628182; Actual: 3.0; ❌
Predicted: 2.40711722529574; Actual: 3.0; ❌
Predicted: 2.375163784144516; Actual: 3.0; ❌
Predicted: 2.3664510702300783; Actual: 3.0; ❌
Predicted: 2.3884212383717913; Actual: 3.0; ❌
Predicted: 2.378529883999021; Actual: 1.0; ❌
Predicted: 2.2455906167123687; Actual: 3.0; ❌
Predicted: 2.384005103731489; Actual: 3.0; ❌
Predicted: 2.378532903094964; Actual: 3.0; ❌
Predicted: 2.378790029697416; Actual: 1.0; ❌
Predicted: 2.237457196193492; Actual: 3.0; ❌
Predicted: 2.3814900989367582; Actual: 3.0; ❌
Predicted: 2.3783938817698727; Actual: 2.0; ✅
Predicted: 2.510914315894908; Actual: 3.0; ✅
Predicted: 2.384543838106906; Actual: 3.0; ❌
Predicted: 2.3768375135130744; Actual: 3.0; ❌
Predicted: 2.3772701971644064; Actual: 3.0; ❌
Predicted: 2.3768337611525316; Actual: 3.0; ❌
Predicted: 2.3796998865654637; Actual: 3.0; ❌
Predicted: 2.3757311234354233; Actual: 3.0; ❌
Predicted: 2.3629062840613955; Actual: 2.0; ✅
Predicted: 2.4257760652408145; Actual: 3.0; ❌
Predicted: 2.403198292830485; Actual: 1.0; ❌
Predicted: 2.378585873542346; Actual: 1.0; ❌
Predicted: 2.376664140547147; Actual: 1.0; ❌
Predicted: 2.3762228005847352; Actual: 3.0; ❌
Predicted: 2.3875281844874157; Actual: 3.0; ❌
Predicted: 2.3786042951781514; Actual: 1.0; ❌
Predicted: 2.3769885490449205; Actual: 2.0; ✅
Predicted: 2.4199547062650795; Actual: 1.0; ❌
Predicted: 2.3752002149826312; Actual: 1.0; ❌
Predicted: 2.3900253409156327; Actual: 2.0; ✅
Predicted: 2.377029597247416; Actual: 2.0; ✅
Predicted: 2.554219120403143; Actual: 2.0; ❌
Predicted: 2.256850185768628; Actual: 3.0; ❌
Predicted: 2.3783855527442856; Actual: 3.0; ❌
Predicted: 2.3778018218680534; Actual: 3.0; ❌
Predicted: 2.3800603750860176; Actual: 3.0; ❌
Predicted: 2.3747715660985484; Actual: 3.0; ❌
Predicted: 2.3930830407019075; Actual: 1.0; ❌
Predicted: 2.3783015035577044; Actual: 3.0; ❌
Predicted: 2.3779049797928047; Actual: 1.0; ❌
Predicted: 2.3793100316704674; Actual: 2.0; ✅
Predicted: 2.375932041234515; Actual: 3.0; ❌
Predicted: 2.376448175679987; Actual: 3.0; ❌
Predicted: 2.3791193230656167; Actual: 3.0; ❌
Predicted: 2.3776219089555632; Actual: 3.0; ❌
Predicted: 2.377478808249055; Actual: 3.0; ❌
Predicted: 2.3822081053934787; Actual: 3.0; ❌
Predicted: 2.378992565678036; Actual: 3.0; ❌
Predicted: 2.3807653826343893; Actual: 3.0; ❌
Predicted: 2.379202399646739; Actual: 3.0; ❌
Predicted: 2.3771961028489597; Actual: 2.0; ✅
Predicted: 2.3767966982524773; Actual: 3.0; ❌
Predicted: 1.9673820772248058; Actual: 2.0; ✅
Predicted: 2.3743129980404154; Actual: 2.0; ✅
Predicted: 2.376878543948708; Actual: 1.0; ❌
Predicted: 2.379615114971716; Actual: 1.0; ❌
Predicted: 2.353834700302546; Actual: 2.0; ✅
Predicted: 2.3762765375299084; Actual: 3.0; ❌
Predicted: 2.3636375948648305; Actual: 2.0; ✅
Predicted: 2.3639969146477506; Actual: 2.0; ✅
Predicted: 2.37690534653432; Actual: 1.0; ❌
Predicted: 2.372527167681734; Actual: 2.0; ✅
Predicted: 2.377682393935535; Actual: 1.0; ❌
Predicted: 2.4054185385597884; Actual: 3.0; ❌
Predicted: 2.9486505929162488; Actual: 3.0; ✅
Predicted: 2.3767179723910554; Actual: 3.0; ❌
Predicted: 2.3810442616464917; Actual: 3.0; ❌
Predicted: 2.376602966018165; Actual: 2.0; ✅
Predicted: 2.3772617803113296; Actual: 3.0; ❌
Predicted: 2.3819256523182544; Actual: 2.0; ✅
Predicted: 2.375576561895102; Actual: 3.0; ❌
Predicted: 2.333807352177448; Actual: 3.0; ❌
Predicted: 2.3769573854350017; Actual: 1.0; ❌
Predicted: 2.350152778118216; Actual: 2.0; ✅
Predicted: 2.3892265056143414; Actual: 1.0; ❌
Predicted: 2.3787969501151767; Actual: 2.0; ✅
Predicted: 2.3774461595359515; Actual: 2.0; ✅
Predicted: 2.379056606641392; Actual: 2.0; ✅
Predicted: 2.3763158941204106; Actual: 3.0; ❌
Predicted: 2.3762028433346174; Actual: 3.0; ❌
Predicted: 2.382442548548975; Actual: 3.0; ❌
Predicted: 2.376435045071491; Actual: 2.0; ✅
Predicted: 2.3927171029073846; Actual: 3.0; ❌
Predicted: 2.3771810661933723; Actual: 2.0; ✅
Predicted: 2.3885793186754087; Actual: 3.0; ❌
Predicted: 2.3859598407509695; Actual: 3.0; ❌
Predicted: 3.0102542230604685; Actual: 3.0; ✅
Predicted: 2.3399313249373765; Actual: 2.0; ✅
Predicted: 2.380012364978002; Actual: 3.0; ❌
Predicted: 2.376565966973286; Actual: 2.0; ✅
Predicted: 2.394723954440603; Actual: 2.0; ✅
Predicted: 2.3815179796478514; Actual: 3.0; ❌
Predicted: 2.3846787039137554; Actual: 3.0; ❌
Predicted: 2.3952574928773074; Actual: 3.0; ❌
Predicted: 2.3852072009098064; Actual: 3.0; ❌
Predicted: 2.382388785114067; Actual: 3.0; ❌
Predicted: 2.378080143928307; Actual: 3.0; ❌
Predicted: 2.362908073510273; Actual: 2.0; ✅
Predicted: 2.3771863307928554; Actual: 3.0; ❌
Predicted: 1.6202792953541796; Actual: 1.0; ❌
Predicted: 2.3771732205345906; Actual: 3.0; ❌
Predicted: 2.377281909166323; Actual: 2.0; ✅
Predicted: 2.3764232835260857; Actual: 2.0; ✅
Predicted: 2.3856585700129775; Actual: 3.0; ❌
Predicted: 2.3803120195910843; Actual: 2.0; ✅
Predicted: 2.3725211419124124; Actual: 1.0; ❌
Predicted: 2.3757023174359913; Actual: 3.0; ❌
Predicted: 2.3797624390135717; Actual: 3.0; ❌
Predicted: 2.1266835220975606; Actual: 2.0; ✅
Predicted: 2.4418077618754834; Actual: 2.0; ✅
Predicted: 2.383459498676582; Actual: 3.0; ❌
Predicted: 2.3613864505072484; Actual: 3.0; ❌
Predicted: 3.0019900383998066; Actual: 3.0; ✅
Predicted: 2.378608309256487; Actual: 1.0; ❌
Predicted: 2.3781608740188434; Actual: 2.0; ✅
Predicted: 2.382994718671578; Actual: 2.0; ✅
Predicted: 2.3818132813284003; Actual: 1.0; ❌
Predicted: 2.385037508452683; Actual: 3.0; ❌
Predicted: 2.3848320491527946; Actual: 1.0; ❌
Predicted: 2.377768667999545; Actual: 2.0; ✅
Predicted: 2.358634698244564; Actual: 3.0; ❌
Predicted: 2.376263985608576; Actual: 3.0; ❌
Predicted: 2.3729376486705775; Actual: 3.0; ❌
Predicted: 2.3831485670274652; Actual: 2.0; ✅
Predicted: 2.3798866655524273; Actual: 1.0; ❌
Predicted: 2.3773161664791287; Actual: 3.0; ❌
Predicted: 2.986614043089611; Actual: 3.0; ✅
Predicted: 2.377963141117428; Actual: 3.0; ❌
Predicted: 2.397744879316552; Actual: 2.0; ✅
Predicted: 2.3864534469682117; Actual: 2.0; ✅
Predicted: 2.3767388191358947; Actual: 3.0; ❌
Predicted: 2.378403960747738; Actual: 1.0; ❌
Predicted: 2.4185239423696356; Actual: 2.0; ✅
Predicted: 2.3767214953554565; Actual: 3.0; ❌
Predicted: 2.3939308511801753; Actual: 3.0; ❌
Predicted: 2.362239323093889; Actual: 3.0; ❌
Predicted: 2.434276283021709; Actual: 3.0; ❌
Predicted: 2.3769451374482022; Actual: 3.0; ❌
Predicted: 2.378350392097975; Actual: 1.0; ❌
Predicted: 2.3458936022940815; Actual: 2.0; ✅
Predicted: 2.378429501623355; Actual: 1.0; ❌
Predicted: 2.3777688715061047; Actual: 2.0; ✅
Predicted: 2.3767691239741193; Actual: 3.0; ❌
Predicted: 2.3836512686372346; Actual: 3.0; ❌
Predicted: 2.322530081405738; Actual: 3.0; ❌
Predicted: 1.0019974350519012; Actual: 1.0; ✅
Predicted: 2.3824982377382176; Actual: 3.0; ❌
Predicted: 2.376398499913518; Actual: 2.0; ✅
Predicted: 2.5259878922671475; Actual: 3.0; ✅
Predicted: 2.376149610166601; Actual: 3.0; ❌
Predicted: 2.377396283163719; Actual: 1.0; ❌
Predicted: 2.379383509650092; Actual: 2.0; ✅
Predicted: 2.3606162896977074; Actual: 3.0; ❌
Predicted: 2.3814119626744725; Actual: 3.0; ❌
Predicted: 2.3770688898715058; Actual: 3.0; ❌
Predicted: 2.3760106795070106; Actual: 2.0; ✅
Predicted: 2.377018907337337; Actual: 2.0; ✅
Predicted: 2.433667769280649; Actual: 2.0; ✅
Predicted: 2.393896473649154; Actual: 3.0; ❌
Predicted: 2.382241167141832; Actual: 3.0; ❌
Predicted: 2.439352440300046; Actual: 1.0; ❌
Predicted: 2.3855973504838666; Actual: 3.0; ❌
Predicted: 2.3752135313998615; Actual: 2.0; ✅
Predicted: 2.377010603649006; Actual: 3.0; ❌
Predicted: 2.3767356096519916; Actual: 2.0; ✅
Predicted: 2.376656214355168; Actual: 1.0; ❌
Predicted: 2.3752134909454288; Actual: 2.0; ✅
Predicted: 2.3800093559296; Actual: 3.0; ❌
Predicted: 2.3767350168440653; Actual: 1.0; ❌
Predicted: 2.393509489915212; Actual: 3.0; ❌
Predicted: 2.3790735467096074; Actual: 3.0; ❌
Predicted: 2.392183551330308; Actual: 3.0; ❌
Predicted: 2.2988842461784147; Actual: 3.0; ❌
Predicted: 2.3807555140193104; Actual: 3.0; ❌
Predicted: 2.3803803674860506; Actual: 2.0; ✅
Predicted: 2.384588181975041; Actual: 2.0; ✅
Predicted: 2.0359658631512265; Actual: 3.0; ❌
Predicted: 2.376959732296212; Actual: 3.0; ❌
Predicted: 2.383541011878723; Actual: 3.0; ❌
Predicted: 2.237053282449821; Actual: 1.0; ❌
Predicted: 2.341199659277253; Actual: 2.0; ✅
Predicted: 2.377880375112615; Actual: 3.0; ❌
Predicted: 2.3719294814404495; Actual: 2.0; ✅
Predicted: 2.377136408827361; Actual: 3.0; ❌
Predicted: 2.3814178551510294; Actual: 2.0; ✅
Predicted: 2.377189578337423; Actual: 1.0; ❌
MSE: 0.5518442485276875
Accuracy: 32.0
Epoch 2 completed
Epoch 3 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 2.4407438312065164; Actual: 2.0; ✅
Predicted: 2.3772091701183626; Actual: 2.0; ✅
Predicted: 2.3775933215574643; Actual: 3.0; ❌
Predicted: 2.3242344736186027; Actual: 1.0; ❌
Predicted: 2.2721465873335083; Actual: 2.0; ✅
Predicted: 2.382048465623331; Actual: 3.0; ❌
Predicted: 2.376847357208855; Actual: 3.0; ❌
Predicted: 2.3691472672865497; Actual: 3.0; ❌
Predicted: 2.378245407362667; Actual: 1.0; ❌
Predicted: 2.375597041625912; Actual: 2.0; ✅
Predicted: 2.377021041888004; Actual: 3.0; ❌
Predicted: 2.37770544870493; Actual: 3.0; ❌
Predicted: 2.410588468058736; Actual: 3.0; ❌
Predicted: 2.4071174860362885; Actual: 3.0; ❌
Predicted: 2.37516380428743; Actual: 3.0; ❌
Predicted: 2.366450761468832; Actual: 3.0; ❌
Predicted: 2.3884212437533545; Actual: 3.0; ❌
Predicted: 2.378529919122184; Actual: 1.0; ❌
Predicted: 2.2455867954824438; Actual: 3.0; ❌
Predicted: 2.3840051388816224; Actual: 3.0; ❌
Predicted: 2.37853292693607; Actual: 3.0; ❌
Predicted: 2.378790072011622; Actual: 1.0; ❌
Predicted: 2.2374570607451223; Actual: 3.0; ❌
Predicted: 2.3814901224709337; Actual: 3.0; ❌
Predicted: 2.3783939232840026; Actual: 2.0; ✅
Predicted: 2.5109142080138547; Actual: 3.0; ✅
Predicted: 2.3845438476959404; Actual: 3.0; ❌
Predicted: 2.376837540239064; Actual: 3.0; ❌
Predicted: 2.377270226304569; Actual: 3.0; ❌
Predicted: 2.3768337870357144; Actual: 3.0; ❌
Predicted: 2.379699904837522; Actual: 3.0; ❌
Predicted: 2.375731148955807; Actual: 3.0; ❌
Predicted: 2.362906026092876; Actual: 2.0; ✅
Predicted: 2.42577617918737; Actual: 3.0; ❌
Predicted: 2.403198274487216; Actual: 1.0; ❌
Predicted: 2.378585901120307; Actual: 1.0; ❌
Predicted: 2.3766641672695505; Actual: 1.0; ❌
Predicted: 2.37622282444969; Actual: 3.0; ❌
Predicted: 2.387528245910604; Actual: 3.0; ❌
Predicted: 2.3786043387984654; Actual: 1.0; ❌
Predicted: 2.3769885756831663; Actual: 2.0; ✅
Predicted: 2.4199545742387225; Actual: 1.0; ❌
Predicted: 2.375200234929279; Actual: 1.0; ❌
Predicted: 2.3900254140018697; Actual: 2.0; ✅
Predicted: 2.377029628181259; Actual: 2.0; ✅
Predicted: 2.5542189893035228; Actual: 2.0; ❌
Predicted: 2.2568503392669514; Actual: 3.0; ❌
Predicted: 2.3783853262926336; Actual: 3.0; ❌
Predicted: 2.377801859539517; Actual: 3.0; ❌
Predicted: 2.380060433865141; Actual: 3.0; ❌
Predicted: 2.3747716033666317; Actual: 3.0; ❌
Predicted: 2.3930830588154053; Actual: 1.0; ❌
Predicted: 2.3783015357400554; Actual: 3.0; ❌
Predicted: 2.3779050071600794; Actual: 1.0; ❌
Predicted: 2.3793100586150575; Actual: 2.0; ✅
Predicted: 2.3759320618527364; Actual: 3.0; ❌
Predicted: 2.3764481998133156; Actual: 3.0; ❌
Predicted: 2.3791193360180145; Actual: 3.0; ❌
Predicted: 2.3776219436969677; Actual: 3.0; ❌
Predicted: 2.377478843916222; Actual: 3.0; ❌
Predicted: 2.38220815701031; Actual: 3.0; ❌
Predicted: 2.3789925943039654; Actual: 3.0; ❌
Predicted: 2.380765386240882; Actual: 3.0; ❌
Predicted: 2.3792024411940065; Actual: 3.0; ❌
Predicted: 2.377196129643817; Actual: 2.0; ✅
Predicted: 2.3767967223004205; Actual: 3.0; ❌
Predicted: 1.9673819085770585; Actual: 2.0; ✅
Predicted: 2.3743129955887157; Actual: 2.0; ✅
Predicted: 2.376878565790519; Actual: 1.0; ❌
Predicted: 2.3796151504669503; Actual: 1.0; ❌
Predicted: 2.353834565004511; Actual: 2.0; ✅
Predicted: 2.3762765233869074; Actual: 3.0; ❌
Predicted: 2.3636376286960084; Actual: 2.0; ✅
Predicted: 2.3639968708130876; Actual: 2.0; ✅
Predicted: 2.376905376624039; Actual: 1.0; ❌
Predicted: 2.3725271909408514; Actual: 2.0; ✅
Predicted: 2.3776824292805343; Actual: 1.0; ❌
Predicted: 2.4054185892092517; Actual: 3.0; ❌
Predicted: 2.9486504248857717; Actual: 3.0; ✅
Predicted: 2.3767179993136995; Actual: 3.0; ❌
Predicted: 2.3810443096130256; Actual: 3.0; ❌
Predicted: 2.376602992812348; Actual: 2.0; ✅
Predicted: 2.3772618112631396; Actual: 3.0; ❌
Predicted: 2.381925694419927; Actual: 2.0; ✅
Predicted: 2.3755765364070993; Actual: 3.0; ❌
Predicted: 2.333807268313603; Actual: 3.0; ❌
Predicted: 2.3769574162338754; Actual: 1.0; ❌
Predicted: 2.350152578015475; Actual: 2.0; ✅
Predicted: 2.3892265158809614; Actual: 1.0; ❌
Predicted: 2.3787969887268203; Actual: 2.0; ✅
Predicted: 2.3774461974686996; Actual: 2.0; ✅
Predicted: 2.379056635756469; Actual: 2.0; ✅
Predicted: 2.3763159188444827; Actual: 3.0; ❌
Predicted: 2.376202855758389; Actual: 3.0; ❌
Predicted: 2.3824425989986766; Actual: 3.0; ❌
Predicted: 2.3764350672709766; Actual: 2.0; ✅
Predicted: 2.3927171340615696; Actual: 3.0; ❌
Predicted: 2.377181093639684; Actual: 2.0; ✅
Predicted: 2.388579326329765; Actual: 3.0; ❌
Predicted: 2.385959936944248; Actual: 3.0; ❌
Predicted: 3.0102532672297158; Actual: 3.0; ✅
Predicted: 2.339931127643623; Actual: 2.0; ✅
Predicted: 2.380012421686361; Actual: 3.0; ❌
Predicted: 2.376565992818273; Actual: 2.0; ✅
Predicted: 2.394724019341258; Actual: 2.0; ✅
Predicted: 2.3815180279798422; Actual: 3.0; ❌
Predicted: 2.384678697393411; Actual: 3.0; ❌
Predicted: 2.3952575622801358; Actual: 3.0; ❌
Predicted: 2.3852072593037814; Actual: 3.0; ❌
Predicted: 2.3823888586655606; Actual: 3.0; ❌
Predicted: 2.3780801647011502; Actual: 3.0; ❌
Predicted: 2.362908047386294; Actual: 2.0; ✅
Predicted: 2.3771863655905827; Actual: 3.0; ❌
Predicted: 1.6202601904651768; Actual: 1.0; ❌
Predicted: 2.3771732435564945; Actual: 3.0; ❌
Predicted: 2.3772818786150633; Actual: 2.0; ✅
Predicted: 2.376423306265929; Actual: 2.0; ✅
Predicted: 2.3856586257686043; Actual: 3.0; ❌
Predicted: 2.380312056982569; Actual: 2.0; ✅
Predicted: 2.372521035747385; Actual: 1.0; ❌
Predicted: 2.3757023060602913; Actual: 3.0; ❌
Predicted: 2.379762467386333; Actual: 3.0; ❌
Predicted: 2.126683786411953; Actual: 2.0; ✅
Predicted: 2.4418077407271928; Actual: 2.0; ✅
Predicted: 2.3834595513465344; Actual: 3.0; ❌
Predicted: 2.361385805339181; Actual: 3.0; ❌
Predicted: 3.0019892332454274; Actual: 3.0; ✅
Predicted: 2.378608341341679; Actual: 1.0; ❌
Predicted: 2.3781609148287646; Actual: 2.0; ✅
Predicted: 2.3829947508592357; Actual: 2.0; ✅
Predicted: 2.3818133001124693; Actual: 1.0; ❌
Predicted: 2.3850375449933843; Actual: 3.0; ❌
Predicted: 2.384832058709986; Actual: 1.0; ❌
Predicted: 2.377768700712803; Actual: 2.0; ✅
Predicted: 2.35863471360477; Actual: 3.0; ❌
Predicted: 2.376264007771267; Actual: 3.0; ❌
Predicted: 2.3729377228491835; Actual: 3.0; ❌
Predicted: 2.383148604054265; Actual: 2.0; ✅
Predicted: 2.3798866894900157; Actual: 1.0; ❌
Predicted: 2.3773161979716777; Actual: 3.0; ❌
Predicted: 2.9866132263921124; Actual: 3.0; ✅
Predicted: 2.3779631774903707; Actual: 3.0; ❌
Predicted: 2.3977449541970537; Actual: 2.0; ✅
Predicted: 2.3864534476669226; Actual: 2.0; ✅
Predicted: 2.3767388453754896; Actual: 3.0; ❌
Predicted: 2.3784039924768154; Actual: 1.0; ❌
Predicted: 2.418523919661587; Actual: 2.0; ✅
Predicted: 2.3767215227105583; Actual: 3.0; ❌
Predicted: 2.39393082496296; Actual: 3.0; ❌
Predicted: 2.3622393114113907; Actual: 3.0; ❌
Predicted: 2.4342761754448388; Actual: 3.0; ❌
Predicted: 2.3769451685621257; Actual: 3.0; ❌
Predicted: 2.3783504160543374; Actual: 1.0; ❌
Predicted: 2.3458936455036596; Actual: 2.0; ✅
Predicted: 2.378429544809799; Actual: 1.0; ❌
Predicted: 2.377768901933294; Actual: 2.0; ✅
Predicted: 2.3767691516666827; Actual: 3.0; ❌
Predicted: 2.3836512896807442; Actual: 3.0; ❌
Predicted: 2.322530199658486; Actual: 3.0; ❌
Predicted: 1.0019990521612028; Actual: 1.0; ✅
Predicted: 2.382498250723046; Actual: 3.0; ❌
Predicted: 2.3763985102500267; Actual: 2.0; ✅
Predicted: 2.5259874656231776; Actual: 3.0; ✅
Predicted: 2.376149622771302; Actual: 3.0; ❌
Predicted: 2.377396311901252; Actual: 1.0; ❌
Predicted: 2.3793835386532156; Actual: 2.0; ✅
Predicted: 2.3606162784224844; Actual: 3.0; ❌
Predicted: 2.3814119691443114; Actual: 3.0; ❌
Predicted: 2.377068918167396; Actual: 3.0; ❌
Predicted: 2.3760107013447023; Actual: 2.0; ✅
Predicted: 2.377018938713197; Actual: 2.0; ✅
Predicted: 2.433668224132235; Actual: 2.0; ✅
Predicted: 2.393896555926648; Actual: 3.0; ❌
Predicted: 2.3822411188012325; Actual: 3.0; ❌
Predicted: 2.4393525355516905; Actual: 1.0; ❌
Predicted: 2.385597393166997; Actual: 3.0; ❌
Predicted: 2.3752135111621433; Actual: 2.0; ✅
Predicted: 2.3770106322867077; Actual: 3.0; ❌
Predicted: 2.3767356358005243; Actual: 2.0; ✅
Predicted: 2.3766562405026646; Actual: 1.0; ❌
Predicted: 2.3752135049902616; Actual: 2.0; ✅
Predicted: 2.380009400657404; Actual: 3.0; ❌
Predicted: 2.3767350436511565; Actual: 1.0; ❌
Predicted: 2.3935095800498893; Actual: 3.0; ❌
Predicted: 2.3790735786051056; Actual: 3.0; ❌
Predicted: 2.392183567668747; Actual: 3.0; ❌
Predicted: 2.298883787847433; Actual: 3.0; ❌
Predicted: 2.380755516521282; Actual: 3.0; ❌
Predicted: 2.3803804000929185; Actual: 2.0; ✅
Predicted: 2.3845882612730507; Actual: 2.0; ✅
Predicted: 2.035967757635288; Actual: 3.0; ❌
Predicted: 2.3769597606665127; Actual: 3.0; ❌
Predicted: 2.383541052566202; Actual: 3.0; ❌
Predicted: 2.2370530732655496; Actual: 1.0; ❌
Predicted: 2.341199481892555; Actual: 2.0; ✅
Predicted: 2.377880409465908; Actual: 3.0; ❌
Predicted: 2.371929472858039; Actual: 2.0; ✅
Predicted: 2.3771364279377925; Actual: 3.0; ❌
Predicted: 2.381417918949047; Actual: 2.0; ✅
Predicted: 2.377189613492322; Actual: 1.0; ❌
MSE: 0.5518441483652463
Accuracy: 32.0
Epoch 3 completed
Epoch 4 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 2.4407440584188493; Actual: 2.0; ✅
Predicted: 2.37720922931491; Actual: 2.0; ✅
Predicted: 2.37759338793605; Actual: 3.0; ❌
Predicted: 2.324234651408472; Actual: 1.0; ❌
Predicted: 2.272146341972473; Actual: 2.0; ✅
Predicted: 2.3820484258246832; Actual: 3.0; ❌
Predicted: 2.376847412702589; Actual: 3.0; ❌
Predicted: 2.369147303064864; Actual: 3.0; ❌
Predicted: 2.378245552278286; Actual: 1.0; ❌
Predicted: 2.3755970840368406; Actual: 2.0; ✅
Predicted: 2.3770210980595334; Actual: 3.0; ❌
Predicted: 2.37770552122825; Actual: 3.0; ❌
Predicted: 2.410588602997914; Actual: 3.0; ❌
Predicted: 2.407117743528701; Actual: 3.0; ❌
Predicted: 2.3751638589860153; Actual: 3.0; ❌
Predicted: 2.366450653062611; Actual: 3.0; ❌
Predicted: 2.3884213055478614; Actual: 3.0; ❌
Predicted: 2.378529994203889; Actual: 1.0; ❌
Predicted: 2.24558526851957; Actual: 3.0; ❌
Predicted: 2.3840052734654935; Actual: 3.0; ❌
Predicted: 2.3785329977819303; Actual: 3.0; ❌
Predicted: 2.378790138376238; Actual: 1.0; ❌
Predicted: 2.2374569803618516; Actual: 3.0; ❌
Predicted: 2.381490211182628; Actual: 3.0; ❌
Predicted: 2.378394003626567; Actual: 2.0; ✅
Predicted: 2.5109143969251098; Actual: 3.0; ✅
Predicted: 2.384543942480358; Actual: 3.0; ❌
Predicted: 2.3768375957537335; Actual: 3.0; ❌
Predicted: 2.377270288235455; Actual: 3.0; ❌
Predicted: 2.376833844399311; Actual: 3.0; ❌
Predicted: 2.379699983804034; Actual: 3.0; ❌
Predicted: 2.3757312050862245; Actual: 3.0; ❌
Predicted: 2.3629059716779364; Actual: 2.0; ✅
Predicted: 2.4257766488090122; Actual: 3.0; ❌
Predicted: 2.403198373554407; Actual: 1.0; ❌
Predicted: 2.378585976010226; Actual: 1.0; ❌
Predicted: 2.3766642214261453; Actual: 1.0; ❌
Predicted: 2.376222876791827; Actual: 3.0; ❌
Predicted: 2.387528426003359; Actual: 3.0; ❌
Predicted: 2.3786044439297593; Actual: 1.0; ❌
Predicted: 2.3769886305115158; Actual: 2.0; ✅
Predicted: 2.419954708420244; Actual: 1.0; ❌
Predicted: 2.3752002808049575; Actual: 1.0; ❌
Predicted: 2.390025631039434; Actual: 2.0; ✅
Predicted: 2.377029689305219; Actual: 2.0; ✅
Predicted: 2.5542193937967075; Actual: 2.0; ❌
Predicted: 2.2568503746127115; Actual: 3.0; ❌
Predicted: 2.3783853629514944; Actual: 3.0; ❌
Predicted: 2.3778019243095008; Actual: 3.0; ❌
Predicted: 2.380060576899152; Actual: 3.0; ❌
Predicted: 2.37477168721333; Actual: 3.0; ❌
Predicted: 2.393083146022624; Actual: 1.0; ❌
Predicted: 2.378301609497668; Actual: 3.0; ❌
Predicted: 2.3779050699838145; Actual: 1.0; ❌
Predicted: 2.379310129967454; Actual: 2.0; ✅
Predicted: 2.375932115332322; Actual: 3.0; ❌
Predicted: 2.376448249661684; Actual: 3.0; ❌
Predicted: 2.3791194144115364; Actual: 3.0; ❌
Predicted: 2.3776220184884194; Actual: 3.0; ❌
Predicted: 2.3774789112926324; Actual: 3.0; ❌
Predicted: 2.382208240366076; Actual: 3.0; ❌
Predicted: 2.378992666500802; Actual: 3.0; ❌
Predicted: 2.380765497637308; Actual: 3.0; ❌
Predicted: 2.379202521433852; Actual: 3.0; ❌
Predicted: 2.3771961882499504; Actual: 2.0; ✅
Predicted: 2.376796781195687; Actual: 3.0; ❌
Predicted: 1.9673818078299223; Actual: 2.0; ✅
Predicted: 2.374313035454265; Actual: 2.0; ✅
Predicted: 2.3768786199804794; Actual: 1.0; ❌
Predicted: 2.3796152366881533; Actual: 1.0; ❌
Predicted: 2.353834567746057; Actual: 2.0; ✅
Predicted: 2.376276601370357; Actual: 3.0; ❌
Predicted: 2.363637678353633; Actual: 2.0; ✅
Predicted: 2.363996985598327; Actual: 2.0; ✅
Predicted: 2.376905434450795; Actual: 1.0; ❌
Predicted: 2.372527285409101; Actual: 2.0; ✅
Predicted: 2.377682500112698; Actual: 1.0; ❌
Predicted: 2.4054189035508315; Actual: 3.0; ❌
Predicted: 2.948651012198824; Actual: 3.0; ✅
Predicted: 2.376718057806188; Actual: 3.0; ❌
Predicted: 2.381044435292606; Actual: 3.0; ❌
Predicted: 2.3766030487287053; Actual: 2.0; ✅
Predicted: 2.3772618861026373; Actual: 3.0; ❌
Predicted: 2.381925817727882; Actual: 2.0; ✅
Predicted: 2.375576568853217; Actual: 3.0; ❌
Predicted: 2.3338072365113716; Actual: 3.0; ❌
Predicted: 2.376957476980011; Actual: 1.0; ❌
Predicted: 2.3501525541156894; Actual: 2.0; ✅
Predicted: 2.3892266073086397; Actual: 1.0; ❌
Predicted: 2.3787970737944937; Actual: 2.0; ✅
Predicted: 2.377446267447804; Actual: 2.0; ✅
Predicted: 2.3790567196199115; Actual: 2.0; ✅
Predicted: 2.3763159767063233; Actual: 3.0; ❌
Predicted: 2.3762029010794525; Actual: 3.0; ❌
Predicted: 2.3824427239109602; Actual: 3.0; ❌
Predicted: 2.3764351153466587; Actual: 2.0; ✅
Predicted: 2.392717303329683; Actual: 3.0; ❌
Predicted: 2.377181152484208; Actual: 2.0; ✅
Predicted: 2.3885794202501485; Actual: 3.0; ❌
Predicted: 2.3859600538666137; Actual: 3.0; ❌
Predicted: 3.0102538266601355; Actual: 3.0; ✅
Predicted: 2.3399310471524797; Actual: 2.0; ✅
Predicted: 2.380012526222165; Actual: 3.0; ❌
Predicted: 2.376566046962412; Actual: 2.0; ✅
Predicted: 2.394724267027347; Actual: 2.0; ✅
Predicted: 2.3815181454890726; Actual: 3.0; ❌
Predicted: 2.3846788178057747; Actual: 3.0; ❌
Predicted: 2.3952576746330716; Actual: 3.0; ❌
Predicted: 2.385207420955135; Actual: 3.0; ❌
Predicted: 2.3823889557052125; Actual: 3.0; ❌
Predicted: 2.378080232146725; Actual: 3.0; ❌
Predicted: 2.362908065274708; Actual: 2.0; ✅
Predicted: 2.377186431057774; Actual: 3.0; ❌
Predicted: 1.6202527311069146; Actual: 1.0; ❌
Predicted: 2.3771732982015457; Actual: 3.0; ❌
Predicted: 2.3772819170021777; Actual: 2.0; ✅
Predicted: 2.37642335681029; Actual: 2.0; ✅
Predicted: 2.3856587348257996; Actual: 3.0; ❌
Predicted: 2.380312154712504; Actual: 2.0; ✅
Predicted: 2.3725210311748715; Actual: 1.0; ❌
Predicted: 2.375702343790813; Actual: 3.0; ❌
Predicted: 2.379762551846429; Actual: 3.0; ❌
Predicted: 2.1266837168304966; Actual: 2.0; ✅
Predicted: 2.441807904105437; Actual: 2.0; ✅
Predicted: 2.383459637900103; Actual: 3.0; ❌
Predicted: 2.361385631997959; Actual: 3.0; ❌
Predicted: 3.0019892686386873; Actual: 3.0; ✅
Predicted: 2.378608412064433; Actual: 1.0; ❌
Predicted: 2.3781609944079385; Actual: 2.0; ✅
Predicted: 2.3829948318327054; Actual: 2.0; ✅
Predicted: 2.381813378615148; Actual: 1.0; ❌
Predicted: 2.3850376607784924; Actual: 3.0; ❌
Predicted: 2.38483213932753; Actual: 1.0; ❌
Predicted: 2.377768772046325; Actual: 2.0; ✅
Predicted: 2.3586347952637006; Actual: 3.0; ❌
Predicted: 2.376264056770828; Actual: 3.0; ❌
Predicted: 2.37293790805339; Actual: 3.0; ❌
Predicted: 2.3831486870124183; Actual: 2.0; ✅
Predicted: 2.3798867739796905; Actual: 1.0; ❌
Predicted: 2.3773162587076957; Actual: 3.0; ❌
Predicted: 2.9866136170091506; Actual: 3.0; ✅
Predicted: 2.3779632576406073; Actual: 3.0; ❌
Predicted: 2.397745181582381; Actual: 2.0; ✅
Predicted: 2.386453501425258; Actual: 2.0; ✅
Predicted: 2.37673889799098; Actual: 3.0; ❌
Predicted: 2.3784040789159038; Actual: 1.0; ❌
Predicted: 2.418524135088953; Actual: 2.0; ✅
Predicted: 2.376721590583324; Actual: 3.0; ❌
Predicted: 2.3939309312154253; Actual: 3.0; ❌
Predicted: 2.3622393339106833; Actual: 3.0; ❌
Predicted: 2.4342762585032354; Actual: 3.0; ❌
Predicted: 2.376945228822179; Actual: 3.0; ❌
Predicted: 2.3783504711410344; Actual: 1.0; ❌
Predicted: 2.3458937019125536; Actual: 2.0; ✅
Predicted: 2.378429626421297; Actual: 1.0; ❌
Predicted: 2.3777689650493636; Actual: 2.0; ✅
Predicted: 2.3767692090109276; Actual: 3.0; ❌
Predicted: 2.3836513926317036; Actual: 3.0; ❌
Predicted: 2.322530375587262; Actual: 3.0; ❌
Predicted: 1.0019981614027753; Actual: 1.0; ✅
Predicted: 2.3824983260703263; Actual: 3.0; ❌
Predicted: 2.3763985604557383; Actual: 2.0; ✅
Predicted: 2.5259875474881457; Actual: 3.0; ✅
Predicted: 2.3761496671356177; Actual: 3.0; ❌
Predicted: 2.3773963733851726; Actual: 1.0; ❌
Predicted: 2.3793836288907895; Actual: 2.0; ✅
Predicted: 2.360616284789445; Actual: 3.0; ❌
Predicted: 2.381412021038286; Actual: 3.0; ❌
Predicted: 2.377068977006823; Actual: 3.0; ❌
Predicted: 2.3760107511811097; Actual: 2.0; ✅
Predicted: 2.3770190003009053; Actual: 2.0; ✅
Predicted: 2.4336686373863285; Actual: 2.0; ✅
Predicted: 2.393896800190018; Actual: 3.0; ❌
Predicted: 2.382241222969216; Actual: 3.0; ❌
Predicted: 2.4393530016648923; Actual: 1.0; ❌
Predicted: 2.385597512571197; Actual: 3.0; ❌
Predicted: 2.37521354470954; Actual: 2.0; ✅
Predicted: 2.3770106879165347; Actual: 3.0; ❌
Predicted: 2.376735690014803; Actual: 2.0; ✅
Predicted: 2.3766562949760535; Actual: 1.0; ❌
Predicted: 2.375213547674419; Actual: 2.0; ✅
Predicted: 2.380009501394214; Actual: 3.0; ❌
Predicted: 2.37673509868544; Actual: 1.0; ❌
Predicted: 2.3935098441618194; Actual: 3.0; ❌
Predicted: 2.3790736583356136; Actual: 3.0; ❌
Predicted: 2.3921836346503613; Actual: 3.0; ❌
Predicted: 2.298883384782323; Actual: 3.0; ❌
Predicted: 2.3807556052837255; Actual: 3.0; ❌
Predicted: 2.380380493243203; Actual: 2.0; ✅
Predicted: 2.384588371175651; Actual: 2.0; ✅
Predicted: 2.0359719662419105; Actual: 3.0; ❌
Predicted: 2.376959821837727; Actual: 3.0; ❌
Predicted: 2.3835411764476677; Actual: 3.0; ❌
Predicted: 2.23705277784446; Actual: 1.0; ❌
Predicted: 2.3411993742357935; Actual: 2.0; ✅
Predicted: 2.3778804802985993; Actual: 3.0; ❌
Predicted: 2.3719294953910826; Actual: 2.0; ✅
Predicted: 2.377136481048387; Actual: 3.0; ❌
Predicted: 2.3814180165767134; Actual: 2.0; ✅
Predicted: 2.377189679784069; Actual: 1.0; ❌
MSE: 0.5518440756640745
Accuracy: 32.0
Epoch 4 completed
Epoch 5 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 2.440744108011446; Actual: 2.0; ✅
Predicted: 2.377209271592258; Actual: 2.0; ✅
Predicted: 2.377593435025647; Actual: 3.0; ❌
Predicted: 2.3242348390858143; Actual: 1.0; ❌
Predicted: 2.272146032658054; Actual: 2.0; ✅
Predicted: 2.382048111587848; Actual: 3.0; ❌
Predicted: 2.3768474523492498; Actual: 3.0; ❌
Predicted: 2.3691472812632504; Actual: 3.0; ❌
Predicted: 2.378245644416175; Actual: 1.0; ❌
Predicted: 2.375597106676485; Actual: 2.0; ✅
Predicted: 2.3770211392313434; Actual: 3.0; ❌
Predicted: 2.3777055762682173; Actual: 3.0; ❌
Predicted: 2.4105886406330606; Actual: 3.0; ❌
Predicted: 2.4071180452288665; Actual: 3.0; ❌
Predicted: 2.3751638944410995; Actual: 3.0; ❌
Predicted: 2.3664503636905625; Actual: 3.0; ❌
Predicted: 2.388421331465832; Actual: 3.0; ❌
Predicted: 2.37853004895064; Actual: 1.0; ❌
Predicted: 2.245581628463664; Actual: 3.0; ❌
Predicted: 2.3840053490021713; Actual: 3.0; ❌
Predicted: 2.3785330418734874; Actual: 3.0; ❌
Predicted: 2.378790195915281; Actual: 1.0; ❌
Predicted: 2.237456842133877; Actual: 3.0; ❌
Predicted: 2.381490261256502; Actual: 3.0; ❌
Predicted: 2.3783940654036817; Actual: 2.0; ✅
Predicted: 2.510914374599853; Actual: 3.0; ✅
Predicted: 2.3845439833220943; Actual: 3.0; ❌
Predicted: 2.3768376368399697; Actual: 3.0; ❌
Predicted: 2.3772703335280148; Actual: 3.0; ❌
Predicted: 2.3768338854498783; Actual: 3.0; ❌
Predicted: 2.379700026199092; Actual: 3.0; ❌
Predicted: 2.3757312454150936; Actual: 3.0; ❌
Predicted: 2.3629057427991715; Actual: 2.0; ✅
Predicted: 2.4257769053369103; Actual: 3.0; ❌
Predicted: 2.403198393161035; Actual: 1.0; ❌
Predicted: 2.3785860245564994; Actual: 1.0; ❌
Predicted: 2.376664262038248; Actual: 1.0; ❌
Predicted: 2.376222914449878; Actual: 3.0; ❌
Predicted: 2.3875285388017047; Actual: 3.0; ❌
Predicted: 2.3786045160833966; Actual: 1.0; ❌
Predicted: 2.3769886712883537; Actual: 2.0; ✅
Predicted: 2.419954647706789; Actual: 1.0; ❌
Predicted: 2.3752003130218498; Actual: 1.0; ❌
Predicted: 2.3900257662182294; Actual: 2.0; ✅
Predicted: 2.377029735772977; Actual: 2.0; ✅
Predicted: 2.5542194278514656; Actual: 2.0; ❌
Predicted: 2.256850511933698; Actual: 3.0; ❌
Predicted: 2.3783851915435292; Actual: 3.0; ❌
Predicted: 2.3778019775227266; Actual: 3.0; ❌
Predicted: 2.380060674612512; Actual: 3.0; ❌
Predicted: 2.37477174677387; Actual: 3.0; ❌
Predicted: 2.3930831911172405; Actual: 1.0; ❌
Predicted: 2.378301661393021; Actual: 3.0; ❌
Predicted: 2.3779051141448186; Actual: 1.0; ❌
Predicted: 2.379310176757501; Actual: 2.0; ✅
Predicted: 2.3759321507464977; Actual: 3.0; ❌
Predicted: 2.3764482866649916; Actual: 3.0; ❌
Predicted: 2.3791194522778585; Actual: 3.0; ❌
Predicted: 2.377622072822106; Actual: 3.0; ❌
Predicted: 2.377478963789066; Actual: 3.0; ❌
Predicted: 2.3822083113790615; Actual: 3.0; ❌
Predicted: 2.3789927149568584; Actual: 3.0; ❌
Predicted: 2.3807655394243272; Actual: 3.0; ❌
Predicted: 2.3792025831988206; Actual: 3.0; ❌
Predicted: 2.3771962304754104; Actual: 2.0; ✅
Predicted: 2.376796821287483; Actual: 3.0; ❌
Predicted: 1.9673816356138938; Actual: 2.0; ✅
Predicted: 2.374313047354915; Actual: 2.0; ✅
Predicted: 2.3768786566316615; Actual: 1.0; ❌
Predicted: 2.37961529562769; Actual: 1.0; ❌
Predicted: 2.353834458614665; Actual: 2.0; ✅
Predicted: 2.3762766170534295; Actual: 3.0; ❌
Predicted: 2.3636377232097026; Actual: 2.0; ✅
Predicted: 2.3639969899825353; Actual: 2.0; ✅
Predicted: 2.3769054790805204; Actual: 1.0; ❌
Predicted: 2.372527337278109; Actual: 2.0; ✅
Predicted: 2.3776825535565287; Actual: 1.0; ❌
Predicted: 2.4054190544256966; Actual: 3.0; ❌
Predicted: 2.9486510793609892; Actual: 3.0; ✅
Predicted: 2.376718100094236; Actual: 3.0; ❌
Predicted: 2.381044518151332; Actual: 3.0; ❌
Predicted: 2.3766030900135027; Actual: 2.0; ✅
Predicted: 2.3772619373774493; Actual: 3.0; ❌
Predicted: 2.3819258949835276; Actual: 2.0; ✅
Predicted: 2.375576559403433; Actual: 3.0; ❌
Predicted: 2.3338071571860985; Actual: 3.0; ❌
Predicted: 2.3769575232059017; Actual: 1.0; ❌
Predicted: 2.350152382968263; Actual: 2.0; ✅
Predicted: 2.38922664754194; Actual: 1.0; ❌
Predicted: 2.3787971348661165; Actual: 2.0; ✅
Predicted: 2.3774463226953615; Actual: 2.0; ✅
Predicted: 2.3790567725463583; Actual: 2.0; ✅
Predicted: 2.376316016989071; Actual: 3.0; ❌
Predicted: 2.3762029269729252; Actual: 3.0; ❌
Predicted: 2.3824428085163465; Actual: 3.0; ❌
Predicted: 2.376435150159172; Actual: 2.0; ✅
Predicted: 2.392717387716345; Actual: 3.0; ❌
Predicted: 2.377181195321058; Actual: 2.0; ✅
Predicted: 2.3885794592208938; Actual: 3.0; ❌
Predicted: 2.385960172825835; Actual: 3.0; ❌
Predicted: 3.010253243154545; Actual: 3.0; ✅
Predicted: 2.339930858544581; Actual: 2.0; ✅
Predicted: 2.3800126087945794; Actual: 3.0; ❌
Predicted: 2.3765660868578578; Actual: 2.0; ✅
Predicted: 2.3947244062405764; Actual: 2.0; ✅
Predicted: 2.3815182257904044; Actual: 3.0; ❌
Predicted: 2.3846788544820923; Actual: 3.0; ❌
Predicted: 2.3952577702062485; Actual: 3.0; ❌
Predicted: 2.38520752484882; Actual: 3.0; ❌
Predicted: 2.3823890493246687; Actual: 3.0; ❌
Predicted: 2.3780802725549846; Actual: 3.0; ❌
Predicted: 2.3629080502597355; Actual: 2.0; ✅
Predicted: 2.3771864821823385; Actual: 3.0; ❌
Predicted: 1.6202345562332914; Actual: 1.0; ❌
Predicted: 2.377173335972735; Actual: 3.0; ❌
Predicted: 2.37728190552165; Actual: 2.0; ✅
Predicted: 2.376423392923078; Actual: 2.0; ✅
Predicted: 2.385658818173508; Actual: 3.0; ❌
Predicted: 2.380312219210992; Actual: 2.0; ✅
Predicted: 2.372520943283023; Actual: 1.0; ❌
Predicted: 2.375702347665723; Actual: 3.0; ❌
Predicted: 2.3797626043767415; Actual: 3.0; ❌
Predicted: 2.1266839076930393; Actual: 2.0; ✅
Predicted: 2.441807943823728; Actual: 2.0; ✅
Predicted: 2.3834597108798814; Actual: 3.0; ❌
Predicted: 2.3613850463284116; Actual: 3.0; ❌
Predicted: 3.001988625688454; Actual: 3.0; ✅
Predicted: 2.3786084628167767; Actual: 1.0; ❌
Predicted: 2.378161055347916; Actual: 2.0; ✅
Predicted: 2.3829948862350703; Actual: 2.0; ✅
Predicted: 2.3818134212648316; Actual: 1.0; ❌
Predicted: 2.385037730881934; Actual: 3.0; ❌
Predicted: 2.3848321751898496; Actual: 1.0; ❌
Predicted: 2.37776882352466; Actual: 2.0; ✅
Predicted: 2.3586348362401273; Actual: 3.0; ❌
Predicted: 2.376264091876515; Actual: 3.0; ❌
Predicted: 2.372938033027961; Actual: 3.0; ❌
Predicted: 2.3831487460292595; Actual: 2.0; ✅
Predicted: 2.3798868229113457; Actual: 1.0; ❌
Predicted: 2.377316305490757; Actual: 3.0; ❌
Predicted: 2.9866130880723993; Actual: 3.0; ✅
Predicted: 2.377963315176904; Actual: 3.0; ❌
Predicted: 2.397745321818234; Actual: 2.0; ✅
Predicted: 2.3864535207261346; Actual: 2.0; ✅
Predicted: 2.3767389376718007; Actual: 3.0; ❌
Predicted: 2.3784041348689353; Actual: 1.0; ❌
Predicted: 2.418524191766326; Actual: 2.0; ✅
Predicted: 2.3767216365003274; Actual: 3.0; ❌
Predicted: 2.3939309469251966; Actual: 3.0; ❌
Predicted: 2.362239332282198; Actual: 3.0; ❌
Predicted: 2.434276199880826; Actual: 3.0; ❌
Predicted: 2.3769452751348106; Actual: 3.0; ❌
Predicted: 2.378350509827359; Actual: 1.0; ❌
Predicted: 2.345893756797432; Actual: 2.0; ✅
Predicted: 2.3784296900010964; Actual: 1.0; ❌
Predicted: 2.3777690117991863; Actual: 2.0; ✅
Predicted: 2.376769251525253; Actual: 3.0; ❌
Predicted: 2.383651445653324; Actual: 3.0; ❌
Predicted: 2.3225305332054242; Actual: 3.0; ❌
Predicted: 1.0019991679194777; Actual: 1.0; ✅
Predicted: 2.3824983628991503; Actual: 3.0; ❌
Predicted: 2.376398586361097; Actual: 2.0; ✅
Predicted: 2.525987228487416; Actual: 3.0; ✅
Predicted: 2.3761496928498804; Actual: 3.0; ❌
Predicted: 2.3773964181936345; Actual: 1.0; ❌
Predicted: 2.3793836839495874; Actual: 2.0; ✅
Predicted: 2.360616277878541; Actual: 3.0; ❌
Predicted: 2.381412044386068; Actual: 3.0; ❌
Predicted: 2.3770690205312275; Actual: 3.0; ❌
Predicted: 2.3760107863167317; Actual: 2.0; ✅
Predicted: 2.3770190472896675; Actual: 2.0; ✅
Predicted: 2.4336691511749904; Actual: 2.0; ✅
Predicted: 2.3938969523416573; Actual: 3.0; ❌
Predicted: 2.3822412199618346; Actual: 3.0; ❌
Predicted: 2.439353241788534; Actual: 1.0; ❌
Predicted: 2.3855975889316348; Actual: 3.0; ❌
Predicted: 2.3752135398736693; Actual: 2.0; ✅
Predicted: 2.3770107305984824; Actual: 3.0; ❌
Predicted: 2.3767357301803775; Actual: 2.0; ✅
Predicted: 2.376656335231879; Actual: 1.0; ❌
Predicted: 2.3752135739782654; Actual: 2.0; ✅
Predicted: 2.3800095729076713; Actual: 3.0; ❌
Predicted: 2.3767351396732006; Actual: 1.0; ❌
Predicted: 2.393510009632032; Actual: 3.0; ❌
Predicted: 2.3790737120848826; Actual: 3.0; ❌
Predicted: 2.3921836712720896; Actual: 3.0; ❌
Predicted: 2.2988828717417977; Actual: 3.0; ❌
Predicted: 2.3807556382636963; Actual: 3.0; ❌
Predicted: 2.3803805522519306; Actual: 2.0; ✅
Predicted: 2.384588473942266; Actual: 2.0; ✅
Predicted: 2.035974973399511; Actual: 3.0; ❌
Predicted: 2.376959866239994; Actual: 3.0; ❌
Predicted: 2.383541252756325; Actual: 3.0; ❌
Predicted: 2.237052504962485; Actual: 1.0; ❌
Predicted: 2.3411991925099147; Actual: 2.0; ✅
Predicted: 2.3778805329356834; Actual: 3.0; ❌
Predicted: 2.371929496283068; Actual: 2.0; ✅
Predicted: 2.3771365151027686; Actual: 3.0; ❌
Predicted: 2.381418102481517; Actual: 2.0; ✅
Predicted: 2.3771897314870913; Actual: 1.0; ❌
MSE: 0.5518439686547771
Accuracy: 32.0
Epoch 5 completed
Epoch 6 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 2.4407443813732153; Actual: 2.0; ✅
Predicted: 2.377209334952567; Actual: 2.0; ✅
Predicted: 2.3775935061675124; Actual: 3.0; ❌
Predicted: 2.3242350135137495; Actual: 1.0; ❌
Predicted: 2.2721458058110895; Actual: 2.0; ✅
Predicted: 2.38204814518045; Actual: 3.0; ❌
Predicted: 2.376847511737812; Actual: 3.0; ❌
Predicted: 2.3691473322185628; Actual: 3.0; ❌
Predicted: 2.3782458026764526; Actual: 1.0; ❌
Predicted: 2.3755971541099448; Actual: 2.0; ✅
Predicted: 2.377021199065204; Actual: 3.0; ❌
Predicted: 2.377705653033046; Actual: 3.0; ❌
Predicted: 2.410588800775382; Actual: 3.0; ❌
Predicted: 2.4071182891595155; Actual: 3.0; ❌
Predicted: 2.3751639539599196; Actual: 3.0; ❌
Predicted: 2.366450303920376; Actual: 3.0; ❌
Predicted: 2.3884214024711037; Actual: 3.0; ❌
Predicted: 2.3785301290246164; Actual: 1.0; ❌
Predicted: 2.2455806754065377; Actual: 3.0; ❌
Predicted: 2.3840054986272325; Actual: 3.0; ❌
Predicted: 2.378533119452039; Actual: 3.0; ❌
Predicted: 2.3787902642174172; Actual: 1.0; ❌
Predicted: 2.2374567777897703; Actual: 3.0; ❌
Predicted: 2.381490359777152; Actual: 3.0; ❌
Predicted: 2.3783941502326402; Actual: 2.0; ✅
Predicted: 2.5109146178941777; Actual: 3.0; ✅
Predicted: 2.384544091962248; Actual: 3.0; ❌
Predicted: 2.3768376958675415; Actual: 3.0; ❌
Predicted: 2.3772703995345483; Actual: 3.0; ❌
Predicted: 2.3768339468279676; Actual: 3.0; ❌
Predicted: 2.3797001144814174; Actual: 3.0; ❌
Predicted: 2.3757313054367946; Actual: 3.0; ❌
Predicted: 2.362905735262976; Actual: 2.0; ✅
Predicted: 2.4257774293639596; Actual: 3.0; ❌
Predicted: 2.403198512852587; Actual: 1.0; ❌
Predicted: 2.3785861060532594; Actual: 1.0; ❌
Predicted: 2.3766643194826864; Actual: 1.0; ❌
Predicted: 2.376222970399733; Actual: 3.0; ❌
Predicted: 2.3875287359145796; Actual: 3.0; ❌
Predicted: 2.3786046294473557; Actual: 1.0; ❌
Predicted: 2.376988729534192; Actual: 2.0; ✅
Predicted: 2.419954832994389; Actual: 1.0; ❌
Predicted: 2.375200362269306; Actual: 1.0; ❌
Predicted: 2.3900260039796835; Actual: 2.0; ✅
Predicted: 2.377029800443842; Actual: 2.0; ✅
Predicted: 2.5542199281449696; Actual: 2.0; ❌
Predicted: 2.2568505202051377; Actual: 3.0; ❌
Predicted: 2.3783852836221415; Actual: 3.0; ❌
Predicted: 2.377802044980434; Actual: 3.0; ❌
Predicted: 2.3800608289886256; Actual: 3.0; ❌
Predicted: 2.374771836646045; Actual: 3.0; ❌
Predicted: 2.393083288966821; Actual: 1.0; ❌
Predicted: 2.3783017405630282; Actual: 3.0; ❌
Predicted: 2.3779051815782486; Actual: 1.0; ❌
Predicted: 2.379310254247541; Actual: 2.0; ✅
Predicted: 2.3759322087332273; Actual: 3.0; ❌
Predicted: 2.3764483396374168; Actual: 3.0; ❌
Predicted: 2.379119541047098; Actual: 3.0; ❌
Predicted: 2.3776221526405674; Actual: 3.0; ❌
Predicted: 2.3774790347344403; Actual: 3.0; ❌
Predicted: 2.3822083974805115; Actual: 3.0; ❌
Predicted: 2.3789927930720203; Actual: 3.0; ❌
Predicted: 2.3807656688147207; Actual: 3.0; ❌
Predicted: 2.379202667895207; Actual: 3.0; ❌
Predicted: 2.3771962931066994; Actual: 2.0; ✅
Predicted: 2.3767968848550796; Actual: 3.0; ❌
Predicted: 1.9673815545188678; Actual: 2.0; ✅
Predicted: 2.3743130944520603; Actual: 2.0; ✅
Predicted: 2.3768787151739588; Actual: 1.0; ❌
Predicted: 2.379615388644355; Actual: 1.0; ❌
Predicted: 2.3538344912497884; Actual: 2.0; ✅
Predicted: 2.3762767112470264; Actual: 3.0; ❌
Predicted: 2.363637773906974; Actual: 2.0; ✅
Predicted: 2.363997133702231; Actual: 2.0; ✅
Predicted: 2.3769055400796346; Actual: 1.0; ❌
Predicted: 2.3725274425915597; Actual: 2.0; ✅
Predicted: 2.3776826286156307; Actual: 1.0; ❌
Predicted: 2.4054194107836313; Actual: 3.0; ❌
Predicted: 2.9486518004084576; Actual: 3.0; ✅
Predicted: 2.3767181625638405; Actual: 3.0; ❌
Predicted: 2.381044654585632; Actual: 3.0; ❌
Predicted: 2.376603149499879; Actual: 2.0; ✅
Predicted: 2.377262018084996; Actual: 3.0; ❌
Predicted: 2.381926029915864; Actual: 2.0; ✅
Predicted: 2.375576602821229; Actual: 3.0; ❌
Predicted: 2.333807138297939; Actual: 3.0; ❌
Predicted: 2.376957587463983; Actual: 1.0; ❌
Predicted: 2.3501523985422987; Actual: 2.0; ✅
Predicted: 2.3892267521258073; Actual: 1.0; ❌
Predicted: 2.3787972258574492; Actual: 2.0; ✅
Predicted: 2.377446396190679; Actual: 2.0; ✅
Predicted: 2.3790568641967473; Actual: 2.0; ✅
Predicted: 2.3763160792017253; Actual: 3.0; ❌
Predicted: 2.3762029771988016; Actual: 3.0; ❌
Predicted: 2.3824429435052688; Actual: 3.0; ❌
Predicted: 2.3764352014811676; Actual: 2.0; ✅
Predicted: 2.3927175787372494; Actual: 3.0; ❌
Predicted: 2.3771812580874063; Actual: 2.0; ✅
Predicted: 2.388579567273168; Actual: 3.0; ❌
Predicted: 2.3859602884414386; Actual: 3.0; ❌
Predicted: 3.0102541022127665; Actual: 3.0; ✅
Predicted: 2.3399308073874483; Actual: 2.0; ✅
Predicted: 2.380012718589025; Actual: 3.0; ❌
Predicted: 2.3765661444803596; Actual: 2.0; ✅
Predicted: 2.394724681601189; Actual: 2.0; ✅
Predicted: 2.3815183525896506; Actual: 3.0; ❌
Predicted: 2.3846789965957123; Actual: 3.0; ❌
Predicted: 2.3952578862954237; Actual: 3.0; ❌
Predicted: 2.385207701060174; Actual: 3.0; ❌
Predicted: 2.382389146641568; Actual: 3.0; ❌
Predicted: 2.3780803468259757; Actual: 3.0; ❌
Predicted: 2.362908076847228; Actual: 2.0; ✅
Predicted: 2.3771865510875188; Actual: 3.0; ❌
Predicted: 1.6202299752991571; Actual: 1.0; ❌
Predicted: 2.377173394791928; Actual: 3.0; ❌
Predicted: 2.3772819569907746; Actual: 2.0; ✅
Predicted: 2.376423447012607; Actual: 2.0; ✅
Predicted: 2.3856589334110914; Actual: 3.0; ❌
Predicted: 2.3803123252692364; Actual: 2.0; ✅
Predicted: 2.372520961037693; Actual: 1.0; ❌
Predicted: 2.3757023941918822; Actual: 3.0; ❌
Predicted: 2.379762696884495; Actual: 3.0; ❌
Predicted: 2.126683769381356; Actual: 2.0; ✅
Predicted: 2.441808139193625; Actual: 2.0; ✅
Predicted: 2.383459800480023; Actual: 3.0; ❌
Predicted: 2.361384983810372; Actual: 3.0; ❌
Predicted: 3.0019888411921904; Actual: 3.0; ✅
Predicted: 2.3786085384531663; Actual: 1.0; ❌
Predicted: 2.3781611394407824; Actual: 2.0; ✅
Predicted: 2.3829949738158223; Actual: 2.0; ✅
Predicted: 2.3818135088892896; Actual: 1.0; ❌
Predicted: 2.3850378582176197; Actual: 3.0; ❌
Predicted: 2.384832267263369; Actual: 1.0; ❌
Predicted: 2.3777688997430304; Actual: 2.0; ✅
Predicted: 2.358634928341036; Actual: 3.0; ❌
Predicted: 2.376264144287578; Actual: 3.0; ❌
Predicted: 2.3729382333884326; Actual: 3.0; ❌
Predicted: 2.383148834850039; Actual: 2.0; ✅
Predicted: 2.3798869164175045; Actual: 1.0; ❌
Predicted: 2.3773163695813704; Actual: 3.0; ❌
Predicted: 2.9866137201898293; Actual: 3.0; ✅
Predicted: 2.377963400910237; Actual: 3.0; ❌
Predicted: 2.397745571259027; Actual: 2.0; ✅
Predicted: 2.386453583354976; Actual: 2.0; ✅
Predicted: 2.3767389934187966; Actual: 3.0; ❌
Predicted: 2.378404228963705; Actual: 1.0; ❌
Predicted: 2.418524448448907; Actual: 2.0; ✅
Predicted: 2.376721709845417; Actual: 3.0; ❌
Predicted: 2.3939310767418704; Actual: 3.0; ❌
Predicted: 2.3622393611431396; Actual: 3.0; ❌
Predicted: 2.434276320166688; Actual: 3.0; ❌
Predicted: 2.3769453387565385; Actual: 3.0; ❌
Predicted: 2.37835056895898; Actual: 1.0; ❌
Predicted: 2.3458938134286145; Actual: 2.0; ✅
Predicted: 2.3784297759494253; Actual: 1.0; ❌
Predicted: 2.377769078906712; Actual: 2.0; ✅
Predicted: 2.3767693124856217; Actual: 3.0; ❌
Predicted: 2.383651561368632; Actual: 3.0; ❌
Predicted: 2.3225307132438835; Actual: 3.0; ❌
Predicted: 1.001997779387308; Actual: 1.0; ✅
Predicted: 2.3824984480967393; Actual: 3.0; ❌
Predicted: 2.376398642753796; Actual: 2.0; ✅
Predicted: 2.52598741594214; Actual: 3.0; ✅
Predicted: 2.376149741922372; Actual: 3.0; ❌
Predicted: 2.3773964837642305; Actual: 1.0; ❌
Predicted: 2.3793837830748763; Actual: 2.0; ✅
Predicted: 2.360616287823639; Actual: 3.0; ❌
Predicted: 2.3814121035878286; Actual: 3.0; ❌
Predicted: 2.3770690831047063; Actual: 3.0; ❌
Predicted: 2.3760108397796684; Actual: 2.0; ✅
Predicted: 2.377019112406106; Actual: 2.0; ✅
Predicted: 2.433669534769069; Actual: 2.0; ✅
Predicted: 2.3938972199152846; Actual: 3.0; ❌
Predicted: 2.3822413521889034; Actual: 3.0; ❌
Predicted: 2.4393537658217506; Actual: 1.0; ❌
Predicted: 2.3855977191614266; Actual: 3.0; ❌
Predicted: 2.375213583414551; Actual: 2.0; ✅
Predicted: 2.377010789345411; Actual: 3.0; ❌
Predicted: 2.3767357878172235; Actual: 2.0; ✅
Predicted: 2.3766563931727216; Actual: 1.0; ❌
Predicted: 2.375213620780094; Actual: 2.0; ✅
Predicted: 2.3800096808827744; Actual: 3.0; ❌
Predicted: 2.3767351981256186; Actual: 1.0; ❌
Predicted: 2.3935102987020684; Actual: 3.0; ❌
Predicted: 2.3790737983017864; Actual: 3.0; ❌
Predicted: 2.392183745933423; Actual: 3.0; ❌
Predicted: 2.298882500825466; Actual: 3.0; ❌
Predicted: 2.3807557414194127; Actual: 3.0; ❌
Predicted: 2.3803806539981944; Actual: 2.0; ✅
Predicted: 2.3845885850168855; Actual: 2.0; ✅
Predicted: 2.0359794751445914; Actual: 3.0; ❌
Predicted: 2.3769599315277166; Actual: 3.0; ❌
Predicted: 2.383541388668694; Actual: 3.0; ❌
Predicted: 2.2370522056661812; Actual: 1.0; ❌
Predicted: 2.341199105370813; Actual: 2.0; ✅
Predicted: 2.3778806082107082; Actual: 3.0; ❌
Predicted: 2.3719295244869993; Actual: 2.0; ✅
Predicted: 2.377136572980176; Actual: 3.0; ❌
Predicted: 2.3814182026232813; Actual: 2.0; ✅
Predicted: 2.3771898012786585; Actual: 1.0; ❌
MSE: 0.5518439054100545
Accuracy: 32.0
Epoch 6 completed
Epoch 7 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 2.440744611336223; Actual: 2.0; ✅
Predicted: 2.3772093727778763; Actual: 2.0; ✅
Predicted: 2.3775935488299935; Actual: 3.0; ❌
Predicted: 2.3242350818496798; Actual: 1.0; ❌
Predicted: 2.2721457498293613; Actual: 2.0; ✅
Predicted: 2.3820483345320493; Actual: 3.0; ❌
Predicted: 2.3768475471818507; Actual: 3.0; ❌
Predicted: 2.369147390698975; Actual: 3.0; ❌
Predicted: 2.378245903937921; Actual: 1.0; ❌
Predicted: 2.3755971869559147; Actual: 2.0; ✅
Predicted: 2.37702123415761; Actual: 3.0; ❌
Predicted: 2.3777056969424506; Actual: 3.0; ❌
Predicted: 2.4105889311772937; Actual: 3.0; ❌
Predicted: 2.4071183649456076; Actual: 3.0; ❌
Predicted: 2.375163991633679; Actual: 3.0; ❌
Predicted: 2.3664503937724; Actual: 3.0; ❌
Predicted: 2.388421455647463; Actual: 3.0; ❌
Predicted: 2.378530176166816; Actual: 1.0; ❌
Predicted: 2.2455816163609565; Actual: 3.0; ❌
Predicted: 2.3840056001780017; Actual: 3.0; ❌
Predicted: 2.378533169624743; Actual: 3.0; ❌
Predicted: 2.378790298977891; Actual: 1.0; ❌
Predicted: 2.237456787332616; Actual: 3.0; ❌
Predicted: 2.3814904264701657; Actual: 3.0; ❌
Predicted: 2.378394198274801; Actual: 2.0; ✅
Predicted: 2.510914855859179; Actual: 3.0; ✅
Predicted: 2.384544172732902; Actual: 3.0; ❌
Predicted: 2.376837730251028; Actual: 3.0; ❌
Predicted: 2.377270438311549; Actual: 3.0; ❌
Predicted: 2.376833983421509; Actual: 3.0; ❌
Predicted: 2.379700175489203; Actual: 3.0; ❌
Predicted: 2.3757313411288545; Actual: 3.0; ❌
Predicted: 2.362905843311922; Actual: 2.0; ✅
Predicted: 2.425777789050884; Actual: 3.0; ❌
Predicted: 2.4031986145982294; Actual: 1.0; ❌
Predicted: 2.3785861576400102; Actual: 1.0; ❌
Predicted: 2.3766643526282825; Actual: 1.0; ❌
Predicted: 2.376223003636932; Actual: 3.0; ❌
Predicted: 2.3875288630155476; Actual: 3.0; ❌
Predicted: 2.3786046988840224; Actual: 1.0; ❌
Predicted: 2.3769887633440883; Actual: 2.0; ✅
Predicted: 2.419955036273258; Actual: 1.0; ❌
Predicted: 2.375200391991921; Actual: 1.0; ❌
Predicted: 2.3900261577358664; Actual: 2.0; ✅
Predicted: 2.377029837384552; Actual: 2.0; ✅
Predicted: 2.554220377398649; Actual: 2.0; ❌
Predicted: 2.2568504589499274; Actual: 3.0; ❌
Predicted: 2.378385455654023; Actual: 3.0; ❌
Predicted: 2.37780208112858; Actual: 3.0; ❌
Predicted: 2.3800609238221058; Actual: 3.0; ❌
Predicted: 2.374771890507928; Actual: 3.0; ❌
Predicted: 2.39308335752343; Actual: 1.0; ❌
Predicted: 2.378301788296055; Actual: 3.0; ❌
Predicted: 2.377905222254399; Actual: 1.0; ❌
Predicted: 2.379310302980176; Actual: 2.0; ✅
Predicted: 2.3759322449983644; Actual: 3.0; ❌
Predicted: 2.3764483704269064; Actual: 3.0; ❌
Predicted: 2.3791196047863976; Actual: 3.0; ❌
Predicted: 2.3776221997529516; Actual: 3.0; ❌
Predicted: 2.3774790744954633; Actual: 3.0; ❌
Predicted: 2.3822084420616654; Actual: 3.0; ❌
Predicted: 2.3789928415497603; Actual: 3.0; ❌
Predicted: 2.3807657684659294; Actual: 3.0; ❌
Predicted: 2.3792027158193707; Actual: 3.0; ❌
Predicted: 2.3771963302780463; Actual: 2.0; ✅
Predicted: 2.376796923972664; Actual: 3.0; ❌
Predicted: 1.967381565406599; Actual: 2.0; ✅
Predicted: 2.374313132384294; Actual: 2.0; ✅
Predicted: 2.3768787513348824; Actual: 1.0; ❌
Predicted: 2.3796154457481857; Actual: 1.0; ❌
Predicted: 2.3538345765652973; Actual: 2.0; ✅
Predicted: 2.3762767912014287; Actual: 3.0; ❌
Predicted: 2.3636377986339907; Actual: 2.0; ✅
Predicted: 2.363997265537299; Actual: 2.0; ✅
Predicted: 2.3769055745201912; Actual: 1.0; ❌
Predicted: 2.3725275147135707; Actual: 2.0; ✅
Predicted: 2.377682671736629; Actual: 1.0; ❌
Predicted: 2.405419667242796; Actual: 3.0; ❌
Predicted: 2.948652438820222; Actual: 3.0; ✅
Predicted: 2.3767181995532867; Actual: 3.0; ❌
Predicted: 2.3810447401539894; Actual: 3.0; ❌
Predicted: 2.3766031842116027; Actual: 2.0; ✅
Predicted: 2.3772620675644855; Actual: 3.0; ❌
Predicted: 2.381926116900726; Actual: 2.0; ✅
Predicted: 2.3755766480606715; Actual: 3.0; ❌
Predicted: 2.3338071605848874; Actual: 3.0; ❌
Predicted: 2.376957624141264; Actual: 1.0; ❌
Predicted: 2.3501524991222715; Actual: 2.0; ✅
Predicted: 2.3892268294199637; Actual: 1.0; ❌
Predicted: 2.378797280001078; Actual: 2.0; ✅
Predicted: 2.377446436946696; Actual: 2.0; ✅
Predicted: 2.3790569230505265; Actual: 2.0; ✅
Predicted: 2.3763161169590474; Actual: 3.0; ❌
Predicted: 2.3762030110143875; Actual: 3.0; ❌
Predicted: 2.3824430268469596; Actual: 3.0; ❌
Predicted: 2.376435231832968; Actual: 2.0; ✅
Predicted: 2.3927177144383966; Actual: 3.0; ❌
Predicted: 2.377181295077387; Actual: 2.0; ✅
Predicted: 2.3885796484348547; Actual: 3.0; ❌
Predicted: 2.3859603364438398; Actual: 3.0; ❌
Predicted: 3.010255196222897; Actual: 3.0; ✅
Predicted: 2.339930854524821; Actual: 2.0; ✅
Predicted: 2.3800127794576986; Actual: 3.0; ❌
Predicted: 2.3765661781523324; Actual: 2.0; ✅
Predicted: 2.394724868391307; Actual: 2.0; ✅
Predicted: 2.381518430458137; Actual: 3.0; ❌
Predicted: 2.3846791106842105; Actual: 3.0; ❌
Predicted: 2.3952579464920056; Actual: 3.0; ❌
Predicted: 2.3852078131468044; Actual: 3.0; ❌
Predicted: 2.382389190318115; Actual: 3.0; ❌
Predicted: 2.378080395766248; Actual: 3.0; ❌
Predicted: 2.362908109191847; Actual: 2.0; ✅
Predicted: 2.377186589635806; Actual: 3.0; ❌
Predicted: 1.620234849562232; Actual: 1.0; ❌
Predicted: 2.3771734306480465; Actual: 3.0; ❌
Predicted: 2.377282010754407; Actual: 2.0; ✅
Predicted: 2.376423479291688; Actual: 2.0; ✅
Predicted: 2.385658998960202; Actual: 3.0; ❌
Predicted: 2.380312391740753; Actual: 2.0; ✅
Predicted: 2.372521021754447; Actual: 1.0; ❌
Predicted: 2.375702435630853; Actual: 3.0; ❌
Predicted: 2.3797627567366546; Actual: 3.0; ❌
Predicted: 2.1266835445606405; Actual: 2.0; ✅
Predicted: 2.4418083013860006; Actual: 2.0; ✅
Predicted: 2.3834598473339255; Actual: 3.0; ❌
Predicted: 2.3613852200522163; Actual: 3.0; ❌
Predicted: 3.0019893652058505; Actual: 3.0; ✅
Predicted: 2.378608583465017; Actual: 1.0; ❌
Predicted: 2.378161187217568; Actual: 2.0; ✅
Predicted: 2.3829950281305132; Actual: 2.0; ✅
Predicted: 2.381813569153942; Actual: 1.0; ❌
Predicted: 2.385037941710789; Actual: 3.0; ❌
Predicted: 2.3848323350873106; Actual: 1.0; ❌
Predicted: 2.377768944933463; Actual: 2.0; ✅
Predicted: 2.358634993631844; Actual: 3.0; ❌
Predicted: 2.376264175507698; Actual: 3.0; ❌
Predicted: 2.372938357406219; Actual: 3.0; ❌
Predicted: 2.3831488879973968; Actual: 2.0; ✅
Predicted: 2.3798869790102497; Actual: 1.0; ❌
Predicted: 2.377316405822198; Actual: 3.0; ❌
Predicted: 2.986614575236119; Actual: 3.0; ✅
Predicted: 2.3779634519282253; Actual: 3.0; ❌
Predicted: 2.397745733360905; Actual: 2.0; ✅
Predicted: 2.386453632047646; Actual: 2.0; ✅
Predicted: 2.3767390254495853; Actual: 3.0; ❌
Predicted: 2.378404288575537; Actual: 1.0; ❌
Predicted: 2.418524659313486; Actual: 2.0; ✅
Predicted: 2.3767217551525635; Actual: 3.0; ❌
Predicted: 2.3939311898937037; Actual: 3.0; ❌
Predicted: 2.3622393888730717; Actual: 3.0; ❌
Predicted: 2.4342764617847648; Actual: 3.0; ❌
Predicted: 2.376945374796859; Actual: 3.0; ❌
Predicted: 2.3783506046457608; Actual: 1.0; ❌
Predicted: 2.3458938386578247; Actual: 2.0; ✅
Predicted: 2.378429824129303; Actual: 1.0; ❌
Predicted: 2.3777691179776284; Actual: 2.0; ✅
Predicted: 2.376769347953702; Actual: 3.0; ❌
Predicted: 2.383651642615865; Actual: 3.0; ❌
Predicted: 2.322530801923404; Actual: 3.0; ❌
Predicted: 1.0019959792145705; Actual: 1.0; ✅
Predicted: 2.3824985090259236; Actual: 3.0; ❌
Predicted: 2.376398682312982; Actual: 2.0; ✅
Predicted: 2.5259877509841018; Actual: 3.0; ✅
Predicted: 2.3761497747504152; Actual: 3.0; ❌
Predicted: 2.377396522377963; Actual: 1.0; ❌
Predicted: 2.3793838478277585; Actual: 2.0; ✅
Predicted: 2.360616300573536; Actual: 3.0; ❌
Predicted: 2.381412147051257; Actual: 3.0; ❌
Predicted: 2.3770691195691365; Actual: 3.0; ❌
Predicted: 2.3760108719657413; Actual: 2.0; ✅
Predicted: 2.3770191495004402; Actual: 2.0; ✅
Predicted: 2.433669634176387; Actual: 2.0; ✅
Predicted: 2.3938973929371365; Actual: 3.0; ❌
Predicted: 2.3822414770090505; Actual: 3.0; ❌
Predicted: 2.4393541337650833; Actual: 1.0; ❌
Predicted: 2.385597802208806; Actual: 3.0; ❌
Predicted: 2.375213626460968; Actual: 2.0; ✅
Predicted: 2.3770108226649347; Actual: 3.0; ❌
Predicted: 2.376735821366741; Actual: 2.0; ✅
Predicted: 2.3766564269603854; Actual: 1.0; ❌
Predicted: 2.3752136511946405; Actual: 2.0; ✅
Predicted: 2.3800097456150975; Actual: 3.0; ❌
Predicted: 2.3767352320223067; Actual: 1.0; ❌
Predicted: 2.3935104850759172; Actual: 3.0; ❌
Predicted: 2.3790738516741436; Actual: 3.0; ❌
Predicted: 2.3921837971376765; Actual: 3.0; ❌
Predicted: 2.2988824128565866; Actual: 3.0; ❌
Predicted: 2.380755821030857; Actual: 3.0; ❌
Predicted: 2.380380719208569; Actual: 2.0; ✅
Predicted: 2.384588636921331; Actual: 2.0; ✅
Predicted: 2.0359821603863013; Actual: 3.0; ❌
Predicted: 2.37695997008215; Actual: 3.0; ❌
Predicted: 2.383541477042967; Actual: 3.0; ❌
Predicted: 2.2370520637706828; Actual: 1.0; ❌
Predicted: 2.341199115455047; Actual: 2.0; ✅
Predicted: 2.3778806519386397; Actual: 3.0; ❌
Predicted: 2.3719295503351856; Actual: 2.0; ✅
Predicted: 2.377136609826921; Actual: 3.0; ❌
Predicted: 2.3814182528123666; Actual: 2.0; ✅
Predicted: 2.377189840362738; Actual: 1.0; ❌
MSE: 0.551843900293407
Accuracy: 32.0
Epoch 7 completed
Epoch 8 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 2.4407444044412285; Actual: 2.0; ✅
Predicted: 2.3772093745297136; Actual: 2.0; ✅
Predicted: 2.377593550189842; Actual: 3.0; ❌
Predicted: 2.324235201993442; Actual: 1.0; ❌
Predicted: 2.2721454882929315; Actual: 2.0; ✅
Predicted: 2.3820477914335623; Actual: 3.0; ❌
Predicted: 2.3768475488522256; Actual: 3.0; ❌
Predicted: 2.3691473019665152; Actual: 3.0; ❌
Predicted: 2.3782458866321803; Actual: 1.0; ❌
Predicted: 2.3755971737134622; Actual: 2.0; ✅
Predicted: 2.3770212378222464; Actual: 3.0; ❌
Predicted: 2.3777057052344555; Actual: 3.0; ❌
Predicted: 2.4105888238236304; Actual: 3.0; ❌
Predicted: 2.407118595886149; Actual: 3.0; ❌
Predicted: 2.375163986405885; Actual: 3.0; ❌
Predicted: 2.366449988557208; Actual: 3.0; ❌
Predicted: 2.3884214229526637; Actual: 3.0; ❌
Predicted: 2.378530180514822; Actual: 1.0; ❌
Predicted: 2.2455767389442807; Actual: 3.0; ❌
Predicted: 2.3840055651049865; Actual: 3.0; ❌
Predicted: 2.3785331593816426; Actual: 3.0; ❌
Predicted: 2.378790320172757; Actual: 1.0; ❌
Predicted: 2.237456631581916; Actual: 3.0; ❌
Predicted: 2.381490403905083; Actual: 3.0; ❌
Predicted: 2.378394208981654; Actual: 2.0; ✅
Predicted: 2.510914563859046; Actual: 3.0; ✅
Predicted: 2.384544124624174; Actual: 3.0; ❌
Predicted: 2.3768377346237983; Actual: 3.0; ❌
Predicted: 2.3772704421573687; Actual: 3.0; ❌
Predicted: 2.3768339852754243; Actual: 3.0; ❌
Predicted: 2.3797001512699736; Actual: 3.0; ❌
Predicted: 2.375731343245389; Actual: 3.0; ❌
Predicted: 2.3629054814680726; Actual: 2.0; ✅
Predicted: 2.425777653301681; Actual: 3.0; ❌
Predicted: 2.403198520582908; Actual: 1.0; ❌
Predicted: 2.3785861504844736; Actual: 1.0; ❌
Predicted: 2.376664357900455; Actual: 1.0; ❌
Predicted: 2.376223005710926; Actual: 3.0; ❌
Predicted: 2.387528838294045; Actual: 3.0; ❌
Predicted: 2.378604696415062; Actual: 1.0; ❌
Predicted: 2.376988768039662; Actual: 2.0; ✅
Predicted: 2.4199547435516973; Actual: 1.0; ❌
Predicted: 2.375200392316052; Actual: 1.0; ❌
Predicted: 2.390026126496933; Actual: 2.0; ✅
Predicted: 2.3770298445275753; Actual: 2.0; ✅
Predicted: 2.5542199067650224; Actual: 2.0; ❌
Predicted: 2.256850672193964; Actual: 3.0; ❌
Predicted: 2.378385082153171; Actual: 3.0; ❌
Predicted: 2.3778020962319726; Actual: 3.0; ❌
Predicted: 2.3800609195905666; Actual: 3.0; ❌
Predicted: 2.374771892358525; Actual: 3.0; ❌
Predicted: 2.3930833275697223; Actual: 1.0; ❌
Predicted: 2.3783017889908473; Actual: 3.0; ❌
Predicted: 2.3779052227736703; Actual: 1.0; ❌
Predicted: 2.3793102971854934; Actual: 2.0; ✅
Predicted: 2.3759322413100987; Actual: 3.0; ❌
Predicted: 2.376448374565161; Actual: 3.0; ❌
Predicted: 2.379119572738832; Actual: 3.0; ❌
Predicted: 2.3776222036999513; Actual: 3.0; ❌
Predicted: 2.3774790847854104; Actual: 3.0; ❌
Predicted: 2.382208466309432; Actual: 3.0; ❌
Predicted: 2.378992837794771; Actual: 3.0; ❌
Predicted: 2.3807657001194618; Actual: 3.0; ❌
Predicted: 2.3792027266417777; Actual: 3.0; ❌
Predicted: 2.3771963327139174; Actual: 2.0; ✅
Predicted: 2.3767969219790643; Actual: 3.0; ❌
Predicted: 1.9673813725703577; Actual: 2.0; ✅
Predicted: 2.3743131021510875; Actual: 2.0; ✅
Predicted: 2.3768787490536165; Actual: 1.0; ❌
Predicted: 2.379615443286651; Actual: 1.0; ❌
Predicted: 2.35383436599004; Actual: 2.0; ✅
Predicted: 2.3762767176276682; Actual: 3.0; ❌
Predicted: 2.36363781788026; Actual: 2.0; ✅
Predicted: 2.3639971217336333; Actual: 2.0; ✅
Predicted: 2.3769055825475767; Actual: 1.0; ❌
Predicted: 2.3725274879327305; Actual: 2.0; ✅
Predicted: 2.377682679243345; Actual: 1.0; ❌
Predicted: 2.4054195368596867; Actual: 3.0; ❌
Predicted: 2.948651789129514; Actual: 3.0; ✅
Predicted: 2.3767182022575875; Actual: 3.0; ❌
Predicted: 2.381044730758872; Actual: 3.0; ❌
Predicted: 2.376603188427181; Actual: 2.0; ✅
Predicted: 2.377262065646493; Actual: 3.0; ❌
Predicted: 2.3819261000256855; Actual: 2.0; ✅
Predicted: 2.375576587172145; Actual: 3.0; ❌
Predicted: 2.3338070522617027; Actual: 3.0; ❌
Predicted: 2.3769576313266505; Actual: 1.0; ❌
Predicted: 2.3501522062827824; Actual: 2.0; ✅
Predicted: 2.3892267846013255; Actual: 1.0; ❌
Predicted: 2.3787972831085136; Actual: 2.0; ✅
Predicted: 2.377446449003552; Actual: 2.0; ✅
Predicted: 2.379056912309598; Actual: 2.0; ✅
Predicted: 2.3763161166985824; Actual: 3.0; ❌
Predicted: 2.376203000083409; Actual: 3.0; ❌
Predicted: 2.3824430217834283; Actual: 3.0; ❌
Predicted: 2.376435234166169; Actual: 2.0; ✅
Predicted: 2.3927176502061993; Actual: 3.0; ❌
Predicted: 2.377181298356753; Actual: 2.0; ✅
Predicted: 2.3885795979274556; Actual: 3.0; ❌
Predicted: 2.385960407117208; Actual: 3.0; ❌
Predicted: 3.0102533506883553; Actual: 3.0; ✅
Predicted: 2.3399306035275558; Actual: 2.0; ✅
Predicted: 2.380012797539032; Actual: 3.0; ❌
Predicted: 2.3765661820818775; Actual: 2.0; ✅
Predicted: 2.3947248041996017; Actual: 2.0; ✅
Predicted: 2.3815184270415513; Actual: 3.0; ❌
Predicted: 2.384679020700866; Actual: 3.0; ❌
Predicted: 2.3952579788988086; Actual: 3.0; ❌
Predicted: 2.3852077959750466; Actual: 3.0; ❌
Predicted: 2.3823892392918613; Actual: 3.0; ❌
Predicted: 2.3780803830444235; Actual: 3.0; ❌
Predicted: 2.362908057021511; Actual: 2.0; ✅
Predicted: 2.3771865998534523; Actual: 3.0; ❌
Predicted: 1.6202102565008518; Actual: 1.0; ❌
Predicted: 2.377173429886774; Actual: 3.0; ❌
Predicted: 2.3772819381563814; Actual: 2.0; ✅
Predicted: 2.3764234808190747; Actual: 2.0; ✅
Predicted: 2.3856590125477246; Actual: 3.0; ❌
Predicted: 2.3803123845688803; Actual: 2.0; ✅
Predicted: 2.3725208612506514; Actual: 1.0; ❌
Predicted: 2.3757023930033423; Actual: 3.0; ❌
Predicted: 2.379762744455437; Actual: 3.0; ❌
Predicted: 2.1266839981473127; Actual: 2.0; ✅
Predicted: 2.441808160363234; Actual: 2.0; ✅
Predicted: 2.3834598710791375; Actual: 3.0; ❌
Predicted: 2.3613843391553644; Actual: 3.0; ❌
Predicted: 3.0019881001446533; Actual: 3.0; ✅
Predicted: 2.378608586016657; Actual: 1.0; ❌
Predicted: 2.378161197347537; Actual: 2.0; ✅
Predicted: 2.382995024026893; Actual: 2.0; ✅
Predicted: 2.381813546037432; Actual: 1.0; ❌
Predicted: 2.385037921254669; Actual: 3.0; ❌
Predicted: 2.3848322963130286; Actual: 1.0; ❌
Predicted: 2.3777689480489244; Actual: 2.0; ✅
Predicted: 2.358634963122216; Actual: 3.0; ❌
Predicted: 2.3762641771721476; Actual: 3.0; ❌
Predicted: 2.3729383489593046; Actual: 3.0; ❌
Predicted: 2.3831488900288793; Actual: 2.0; ✅
Predicted: 2.3798869598666723; Actual: 1.0; ❌
Predicted: 2.377316414078772; Actual: 3.0; ❌
Predicted: 2.9866130563873834; Actual: 3.0; ✅
Predicted: 2.3779634548465993; Actual: 3.0; ❌
Predicted: 2.3977456980151386; Actual: 2.0; ✅
Predicted: 2.386453597452172; Actual: 2.0; ✅
Predicted: 2.3767390309983396; Actual: 3.0; ❌
Predicted: 2.3784042801592014; Actual: 1.0; ❌
Predicted: 2.4185244813972986; Actual: 2.0; ✅
Predicted: 2.3767217523075477; Actual: 3.0; ❌
Predicted: 2.3939310789543615; Actual: 3.0; ❌
Predicted: 2.362239355980464; Actual: 3.0; ❌
Predicted: 2.4342762407222343; Actual: 3.0; ❌
Predicted: 2.3769453827903884; Actual: 3.0; ❌
Predicted: 2.3783506050361596; Actual: 1.0; ❌
Predicted: 2.3458938679256915; Actual: 2.0; ✅
Predicted: 2.3784298365722325; Actual: 1.0; ❌
Predicted: 2.377769123017431; Actual: 2.0; ✅
Predicted: 2.3767693526086653; Actual: 3.0; ❌
Predicted: 2.3836516067687348; Actual: 3.0; ❌
Predicted: 2.3225308675592613; Actual: 3.0; ❌
Predicted: 1.0019990645697674; Actual: 1.0; ✅
Predicted: 2.382498479051055; Actual: 3.0; ❌
Predicted: 2.3763986649355155; Actual: 2.0; ✅
Predicted: 2.5259870383724183; Actual: 3.0; ✅
Predicted: 2.3761497647514975; Actual: 3.0; ❌
Predicted: 2.3773965258987246; Actual: 1.0; ❌
Predicted: 2.3793838326834194; Actual: 2.0; ✅
Predicted: 2.3606162790220266; Actual: 3.0; ❌
Predicted: 2.381412122592958; Actual: 3.0; ❌
Predicted: 2.377069124159241; Actual: 3.0; ❌
Predicted: 2.376010872577352; Actual: 2.0; ✅
Predicted: 2.3770191570167687; Actual: 2.0; ✅
Predicted: 2.433670060866383; Actual: 2.0; ✅
Predicted: 2.3938973578155665; Actual: 3.0; ❌
Predicted: 2.3822413333097874; Actual: 3.0; ❌
Predicted: 2.4393539715464496; Actual: 1.0; ❌
Predicted: 2.3855977888174467; Actual: 3.0; ❌
Predicted: 2.375213572835758; Actual: 2.0; ✅
Predicted: 2.3770108299102937; Actual: 3.0; ❌
Predicted: 2.376735825715908; Actual: 2.0; ✅
Predicted: 2.376656431137096; Actual: 1.0; ❌
Predicted: 2.3752136445370606; Actual: 2.0; ✅
Predicted: 2.380009747759239; Actual: 3.0; ❌
Predicted: 2.376735236843853; Actual: 1.0; ❌
Predicted: 2.393510448902756; Actual: 3.0; ❌
Predicted: 2.3790738479703952; Actual: 3.0; ❌
Predicted: 2.392183777869262; Actual: 3.0; ❌
Predicted: 2.298881974103672; Actual: 3.0; ❌
Predicted: 2.3807557659850107; Actual: 3.0; ❌
Predicted: 2.380380707696205; Actual: 2.0; ✅
Predicted: 2.3845886862095935; Actual: 2.0; ✅
Predicted: 2.03598228956769; Actual: 3.0; ❌
Predicted: 2.3769599732457403; Actual: 3.0; ❌
Predicted: 2.3835414576141707; Actual: 3.0; ❌
Predicted: 2.237051937642663; Actual: 1.0; ❌
Predicted: 2.341198913581561; Actual: 2.0; ✅
Predicted: 2.377880657915334; Actual: 3.0; ❌
Predicted: 2.371929522186955; Actual: 2.0; ✅
Predicted: 2.3771366040511754; Actual: 3.0; ❌
Predicted: 2.381418286378646; Actual: 2.0; ✅
Predicted: 2.3771898505845352; Actual: 1.0; ❌
MSE: 0.5518437935890665
Accuracy: 32.0
Epoch 8 completed
Epoch 9 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

Predicted: 2.4407444828718834; Actual: 2.0; ✅
Predicted: 2.3772094365251326; Actual: 2.0; ✅
Predicted: 2.37759361927335; Actual: 3.0; ❌
Predicted: 2.3242354746531015; Actual: 1.0; ❌
Predicted: 2.27214504107674; Actual: 2.0; ✅
Predicted: 2.38204734426682; Actual: 3.0; ❌
Predicted: 2.3768476069818294; Actual: 3.0; ❌
Predicted: 2.3691472723249922; Actual: 3.0; ❌
Predicted: 2.3782460224639044; Actual: 1.0; ❌
Predicted: 2.375597207287945; Actual: 2.0; ✅
Predicted: 2.3770212981332963; Actual: 3.0; ❌
Predicted: 2.3777057857913086; Actual: 3.0; ❌
Predicted: 2.410588881967467; Actual: 3.0; ❌
Predicted: 2.407119032021095; Actual: 3.0; ❌
Predicted: 2.375164038589148; Actual: 3.0; ❌
Predicted: 2.366449573623415; Actual: 3.0; ❌
Predicted: 2.388421461867858; Actual: 3.0; ❌
Predicted: 2.378530260756303; Actual: 1.0; ❌
Predicted: 2.2455715289641547; Actual: 3.0; ❌
Predicted: 2.3840056769952485; Actual: 3.0; ❌
Predicted: 2.3785332243736157; Actual: 3.0; ❌
Predicted: 2.3787904040060437; Actual: 1.0; ❌
Predicted: 2.237456432830356; Actual: 3.0; ❌
Predicted: 2.3814904780203303; Actual: 3.0; ❌
Predicted: 2.3783942993641243; Actual: 2.0; ✅
Predicted: 2.5109145377121243; Actual: 3.0; ✅
Predicted: 2.384544185861095; Actual: 3.0; ❌
Predicted: 2.37683779478947; Actual: 3.0; ❌
Predicted: 2.3772705085277046; Actual: 3.0; ❌
Predicted: 2.376834045472006; Actual: 3.0; ❌
Predicted: 2.3797002141562573; Actual: 3.0; ❌
Predicted: 2.3757314023852034; Actual: 3.0; ❌
Predicted: 2.3629051550848934; Actual: 2.0; ✅
Predicted: 2.4257780338336623; Actual: 3.0; ❌
Predicted: 2.4031985518684658; Actual: 1.0; ❌
Predicted: 2.378586221946621; Actual: 1.0; ❌
Predicted: 2.3766644173523552; Actual: 1.0; ❌
Predicted: 2.3762230609213923; Actual: 3.0; ❌
Predicted: 2.387529004668728; Actual: 3.0; ❌
Predicted: 2.3786048024452997; Actual: 1.0; ❌
Predicted: 2.376988827746019; Actual: 2.0; ✅
Predicted: 2.4199546620494012; Actual: 1.0; ❌
Predicted: 2.3752004395886743; Actual: 1.0; ❌
Predicted: 2.39002632593639; Actual: 2.0; ✅
Predicted: 2.377029912526673; Actual: 2.0; ✅
Predicted: 2.554219968503738; Actual: 2.0; ❌
Predicted: 2.2568508684060005; Actual: 3.0; ❌
Predicted: 2.378384840665739; Actual: 3.0; ❌
Predicted: 2.37780217389938; Actual: 3.0; ❌
Predicted: 2.380061063228898; Actual: 3.0; ❌
Predicted: 2.374771979772115; Actual: 3.0; ❌
Predicted: 2.3930833944432637; Actual: 1.0; ❌
Predicted: 2.378301865152446; Actual: 3.0; ❌
Predicted: 2.3779052875707993; Actual: 1.0; ❌
Predicted: 2.379310366010731; Actual: 2.0; ✅
Predicted: 2.375932293384291; Actual: 3.0; ❌
Predicted: 2.3764484287483345; Actual: 3.0; ❌
Predicted: 2.379119629184044; Actual: 3.0; ❌
Predicted: 2.3776222833422604; Actual: 3.0; ❌
Predicted: 2.3774791615447035; Actual: 3.0; ❌
Predicted: 2.382208569789026; Actual: 3.0; ❌
Predicted: 2.3789929090216395; Actual: 3.0; ❌
Predicted: 2.3807657633492485; Actual: 3.0; ❌
Predicted: 2.379202816993772; Actual: 3.0; ❌
Predicted: 2.377196394619628; Actual: 2.0; ✅
Predicted: 2.3767969808724847; Actual: 3.0; ❌
Predicted: 1.967381125234091; Actual: 2.0; ✅
Predicted: 2.3743131204239876; Actual: 2.0; ✅
Predicted: 2.3768788028883243; Actual: 1.0; ❌
Predicted: 2.379615529885094; Actual: 1.0; ❌
Predicted: 2.3538342114023885; Actual: 2.0; ✅
Predicted: 2.3762767426336233; Actual: 3.0; ❌
Predicted: 2.363637883271292; Actual: 2.0; ✅
Predicted: 2.3639971321198976; Actual: 2.0; ✅
Predicted: 2.3769056478194197; Actual: 1.0; ❌
Predicted: 2.372527564830365; Actual: 2.0; ✅
Predicted: 2.377682757481835; Actual: 1.0; ❌
Predicted: 2.405419762083161; Actual: 3.0; ❌
Predicted: 2.9486519026086864; Actual: 3.0; ✅
Predicted: 2.376718264243016; Actual: 3.0; ❌
Predicted: 2.3810448527063577; Actual: 3.0; ❌
Predicted: 2.3766032488973443; Actual: 2.0; ✅
Predicted: 2.3772621409772894; Actual: 3.0; ❌
Predicted: 2.3819262139347477; Actual: 2.0; ✅
Predicted: 2.375576574864147; Actual: 3.0; ❌
Predicted: 2.333806938696423; Actual: 3.0; ❌
Predicted: 2.376957698968531; Actual: 1.0; ❌
Predicted: 2.3501519628443286; Actual: 2.0; ✅
Predicted: 2.389226844887309; Actual: 1.0; ❌
Predicted: 2.378797372684068; Actual: 2.0; ✅
Predicted: 2.377446529755788; Actual: 2.0; ✅
Predicted: 2.3790569903019376; Actual: 2.0; ✅
Predicted: 2.3763161758289426; Actual: 3.0; ❌
Predicted: 2.3762030383485317; Actual: 3.0; ❌
Predicted: 2.382443146161182; Actual: 3.0; ❌
Predicted: 2.3764352851831374; Actual: 2.0; ✅
Predicted: 2.3927177758977223; Actual: 3.0; ❌
Predicted: 2.3771813611324344; Actual: 2.0; ✅
Predicted: 2.3885796564940827; Actual: 3.0; ❌
Predicted: 2.385960579674744; Actual: 3.0; ❌
Predicted: 3.010252540986243; Actual: 3.0; ✅
Predicted: 2.3399303332893346; Actual: 2.0; ✅
Predicted: 2.3800129182501366; Actual: 3.0; ❌
Predicted: 2.3765662405221453; Actual: 2.0; ✅
Predicted: 2.3947250104731386; Actual: 2.0; ✅
Predicted: 2.3815185450557697; Actual: 3.0; ❌
Predicted: 2.3846790769688315; Actual: 3.0; ❌
Predicted: 2.395258118160022; Actual: 3.0; ❌
Predicted: 2.3852079490428286; Actual: 3.0; ❌
Predicted: 2.3823893752678784; Actual: 3.0; ❌
Predicted: 2.3780804426911017; Actual: 3.0; ❌
Predicted: 2.3629080363870405; Actual: 2.0; ✅
Predicted: 2.3771866746038404; Actual: 3.0; ❌
Predicted: 1.6201841525553646; Actual: 1.0; ❌
Predicted: 2.377173485328599; Actual: 3.0; ❌
Predicted: 2.3772819232273164; Actual: 2.0; ✅
Predicted: 2.3764235337666344; Actual: 2.0; ✅
Predicted: 2.3856591344425544; Actual: 3.0; ❌
Predicted: 2.3803124794662214; Actual: 2.0; ✅
Predicted: 2.372520736722676; Actual: 1.0; ❌
Predicted: 2.375702399769648; Actual: 3.0; ❌
Predicted: 2.3797628219069376; Actual: 3.0; ❌
Predicted: 2.1266842664267283; Actual: 2.0; ✅
Predicted: 2.441808222357789; Actual: 2.0; ✅
Predicted: 2.3834599774455425; Actual: 3.0; ❌
Predicted: 2.36138350207983; Actual: 3.0; ❌
Predicted: 3.0019871895333594; Actual: 3.0; ✅
Predicted: 2.3786086604332795; Actual: 1.0; ❌
Predicted: 2.3781612865220976; Actual: 2.0; ✅
Predicted: 2.3829951039605715; Actual: 2.0; ✅
Predicted: 2.3818136092669824; Actual: 1.0; ❌
Predicted: 2.3850380247443597; Actual: 3.0; ❌
Predicted: 2.384832349947158; Actual: 1.0; ❌
Predicted: 2.3777690235223172; Actual: 2.0; ✅
Predicted: 2.358635024130836; Actual: 3.0; ❌
Predicted: 2.3762642286404385; Actual: 3.0; ❌
Predicted: 2.372938532822056; Actual: 3.0; ❌
Predicted: 2.3831489765300278; Actual: 2.0; ✅
Predicted: 2.3798870322177077; Actual: 1.0; ❌
Predicted: 2.377316482499326; Actual: 3.0; ❌
Predicted: 2.9866123186880382; Actual: 3.0; ✅
Predicted: 2.3779635392382565; Actual: 3.0; ❌
Predicted: 2.3977459049592538; Actual: 2.0; ✅
Predicted: 2.3864536266882013; Actual: 2.0; ✅
Predicted: 2.3767390890721445; Actual: 3.0; ❌
Predicted: 2.3784043625380056; Actual: 1.0; ❌
Predicted: 2.4185245695204225; Actual: 2.0; ✅
Predicted: 2.3767218197894566; Actual: 3.0; ❌
Predicted: 2.393931104986435; Actual: 3.0; ❌
Predicted: 2.3622393545653138; Actual: 3.0; ❌
Predicted: 2.4342761604311103; Actual: 3.0; ❌
Predicted: 2.376945450537597; Actual: 3.0; ❌
Predicted: 2.3783506617929677; Actual: 1.0; ❌
Predicted: 2.345893947901603; Actual: 2.0; ✅
Predicted: 2.378429929553843; Actual: 1.0; ❌
Predicted: 2.377769191486372; Actual: 2.0; ✅
Predicted: 2.376769414874414; Actual: 3.0; ❌
Predicted: 2.383651685596938; Actual: 3.0; ❌
Predicted: 2.322531097419044; Actual: 3.0; ❌
Predicted: 1.002000463512723; Actual: 1.0; ✅
Predicted: 2.382498533912315; Actual: 3.0; ❌
Predicted: 2.376398703410358; Actual: 2.0; ✅
Predicted: 2.5259865879304737; Actual: 3.0; ✅
Predicted: 2.376149802747294; Actual: 3.0; ❌
Predicted: 2.3773965915650623; Actual: 1.0; ❌
Predicted: 2.379383913928136; Actual: 2.0; ✅
Predicted: 2.360616269576862; Actual: 3.0; ❌
Predicted: 2.3814121575025884; Actual: 3.0; ❌
Predicted: 2.3770691879037464; Actual: 3.0; ❌
Predicted: 2.3760109241253633; Actual: 2.0; ✅
Predicted: 2.3770192257698946; Actual: 2.0; ✅
Predicted: 2.4336708027085727; Actual: 2.0; ✅
Predicted: 2.393897582285989; Actual: 3.0; ❌
Predicted: 2.382241332770144; Actual: 3.0; ❌
Predicted: 2.4393543287898716; Actual: 1.0; ❌
Predicted: 2.3855979012974116; Actual: 3.0; ❌
Predicted: 2.3752135669973384; Actual: 2.0; ✅
Predicted: 2.377010892342113; Actual: 3.0; ❌
Predicted: 2.376735884537782; Actual: 2.0; ✅
Predicted: 2.3766564900982914; Actual: 1.0; ❌
Predicted: 2.375213683319789; Actual: 2.0; ✅
Predicted: 2.380009852699179; Actual: 3.0; ❌
Predicted: 2.3767352968615523; Actual: 1.0; ❌
Predicted: 2.393510692972668; Actual: 3.0; ❌
Predicted: 2.3790739269860657; Actual: 3.0; ❌
Predicted: 2.3921838320836213; Actual: 3.0; ❌
Predicted: 2.2988812337635793; Actual: 3.0; ❌
Predicted: 2.380755815877271; Actual: 3.0; ❌
Predicted: 2.3803807946493087; Actual: 2.0; ✅
Predicted: 2.384588835569642; Actual: 2.0; ✅
Predicted: 2.0359866968263334; Actual: 3.0; ❌
Predicted: 2.376960038329981; Actual: 3.0; ❌
Predicted: 2.383541570212031; Actual: 3.0; ❌
Predicted: 2.237051541285157; Actual: 1.0; ❌
Predicted: 2.3411986525640094; Actual: 2.0; ✅
Predicted: 2.3778807350102573; Actual: 3.0; ❌
Predicted: 2.3719295243048246; Actual: 2.0; ✅
Predicted: 2.377136654172538; Actual: 3.0; ❌
Predicted: 2.3814184114874406; Actual: 2.0; ✅
Predicted: 2.3771899261852067; Actual: 1.0; ❌
MSE: 0.55184363890146
Accuracy: 32.0
Epoch 9 completed
Epoch 10 started

Data passes per epoch progress:   0%|          | 0/100 [00:00<?, ?it/s]

KeyboardInterrupt:

In [110]:
wangMendelFuzzyNeuralNetwork.save_to_file('models/regular/biogas/model_37')

#### Testing

In [80]:
# wangMendelFuzzyNeuralNetwork.predict([0.1525, 0.3146, 0.4696, 0.0633])

c_initial = np.linspace(min_class, max_class, membership_functions_count).tolist()
s_initial = np.full(membership_functions_count, 0.2).tolist()

wangMendelFuzzyNeuralNetwork1 = WangMendelFuzzyNeuralNetwork(membership_functions_count,4, c_initial,
                                                             s_initial)
wangMendelFuzzyNeuralNetwork1.initialize_from_file('models/regular/biogas/model_33')

input_data = np.array(test_df.iloc[:, :-1].values, dtype=float)
expected_output_data = np.array(test_df.iloc[:, -1].values, dtype=float)

wangMendelFuzzyNeuralNetwork1.predict_and_validate(input_data, expected_output_data, detailed_output=True)

# wangMendelFuzzyNeuralNetwork.predict([0.1525, 0.3146, 0.4696, 0.0633])

Predicted: 2.4903815782479968; Actual: 2.0; ✅
Predicted: 2.455486109667136; Actual: 3.0; ❌
Predicted: 2.1351030184176603; Actual: 3.0; ❌
Predicted: 2.6518002641461442; Actual: 3.0; ✅
Predicted: 2.3786173799659833; Actual: 2.0; ✅
Predicted: 2.302693641542894; Actual: 3.0; ❌
Predicted: 2.6246466845481726; Actual: 2.0; ❌
Predicted: 2.384072183397112; Actual: 3.0; ❌
Predicted: 2.404095549759154; Actual: 2.0; ✅
Predicted: 2.3254205247335236; Actual: 2.0; ✅
Predicted: 2.4310235512572644; Actual: 2.0; ✅
Predicted: 2.3893061122592694; Actual: 3.0; ❌
Predicted: 2.354024956318377; Actual: 2.0; ✅
Predicted: 2.347452896180027; Actual: 3.0; ❌
Predicted: 2.408325915035274; Actual: 3.0; ❌
Predicted: 2.390381797081924; Actual: 3.0; ❌
Predicted: 2.4292490925483494; Actual: 3.0; ❌
Predicted: 2.3907311871227757; Actual: 1.0; ❌
Predicted: 2.3698690039290753; Actual: 3.0; ❌
Predicted: 2.363718244851912; Actual: 2.0; ✅
Predicted: 2.373184777661735; Actual: 3.0; ❌
Predicted: 2.3695497114747743; Actual: 2.0; ✅
Predicted: 2.4159398479628953; Actual: 3.0; ❌
Predicted: 2.303223089725171; Actual: 3.0; ❌
Predicted: 2.361676021566322; Actual: 2.0; ✅
Predicted: 2.308707293482652; Actual: 2.0; ✅
Predicted: 2.0973757076797286; Actual: 3.0; ❌
Predicted: 2.3082586179740434; Actual: 3.0; ❌
Predicted: 2.3192984578888494; Actual: 2.0; ✅
Predicted: 2.6969954714216358; Actual: 3.0; ✅
Predicted: 2.2898121464500587; Actual: 3.0; ❌
Predicted: 2.469704648968047; Actual: 3.0; ❌
Predicted: 2.27263876617703; Actual: 1.0; ❌
Predicted: 2.424687239866875; Actual: 2.0; ✅
Predicted: 2.358024895427334; Actual: 2.0; ✅
Predicted: 2.30795557822157; Actual: 2.0; ✅
Predicted: 2.116465790164007; Actual: 1.0; ❌
Predicted: 2.609962069148911; Actual: 3.0; ✅
Predicted: 2.3207162680088254; Actual: 3.0; ❌
Predicted: 2.3744432618951983; Actual: 3.0; ❌
Predicted: 2.319469359337636; Actual: 3.0; ❌
Predicted: 2.4325746031375424; Actual: 2.0; ✅
Predicted: 2.4124859253328137; Actual: 3.0; ❌
Predicted: 2.384108770661072; Actual: 3.0; ❌
Predicted: 2.4240032183934637; Actual: 1.0; ❌
Predicted: 2.684334381873365; Actual: 3.0; ✅
Predicted: 2.3982072342159917; Actual: 3.0; ❌
Predicted: 2.3748473331356075; Actual: 3.0; ❌
Predicted: 2.4524414398564747; Actual: 3.0; ❌
Predicted: 2.3621630603006833; Actual: 2.0; ✅
MSE: 0.4102137181828971
Accuracy: 40.0

[0.4102137181828971, 40.0]